import { notFound } from "next/navigation";
import { FlightForm } from "@/components/flight-form";
import { requireUser } from "@/lib/auth/require-user";
import { getAircraftOptions } from "@/lib/data/aircraft";
import { getFlight, getFlightNavigation } from "@/lib/data/flights";
import { getFlightAudit } from "@/lib/data/flight-audit";
import Link from "next/link";
import { deleteFlight, setFlightLock, updateFlight } from "../actions";
import { getFlightTracks } from "@/lib/data/tracks";
import { FlightTrackPlayer } from "@/components/flight-track-player";
import { TrackManager } from "@/components/track-manager";
import { attachKmlTrack, applyGpsTimes, deleteTrack, redetectFlightAirports } from "../actions";
import { formatDuration } from "@/lib/data/dashboard";
import { AirportDetectionControl } from "@/components/airport-detection-control";
import { billingLabel } from "@/lib/billing";
import { FlightAuditPanel } from "@/components/flight-audit-panel";
import { DeleteFlightButton } from "@/components/delete-flight-button";
import { sql } from "@/lib/db";
import { ensureDatabaseOptimizations } from "@/lib/db-optimization";
import { blockingComplianceIssues,fcl050FlightCompliance } from "@/lib/fcl050-compliance";
import { flightAuditChanges } from "@/lib/flight-audit";
import { integrityLabel,verifyFlightCertification } from "@/lib/certification-integrity";
import { certifyFlight, startCertifiedCorrection } from "../certification-actions";

type Context={q?:string;evidence?:string;role?:string;registration?:string;aircraftClass?:string;airport?:string;route?:string;routePair?:string;gps?:string;year?:string;sort?:string;from?:string;to?:string};
const contextQuery=(context:Context)=>{const query=new URLSearchParams();for(const [key,value] of Object.entries(context))if(value)query.set(key,value);return query.toString()};
const dateTime=(value:unknown)=>{const d=new Date(String(value??""));return Number.isNaN(d.getTime())?String(value??""):new Intl.DateTimeFormat("en-GB",{dateStyle:"medium",timeStyle:"short",timeZone:"Europe/Prague"}).format(d)};
const snapshot=(value:unknown)=>value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:{};
const metaFields=new Set(["record_revision","certified_at","correction_reason","locked_at"]);
const materialChanges=(before:Record<string,unknown>,after:Record<string,unknown>)=>flightAuditChanges(before,after).filter(change=>!metaFields.has(change.field));

export default async function FlightDetailPage({ params,searchParams }: { params: Promise<{ id: string }>;searchParams:Promise<Context> }) {
  const { userId } = await requireUser(); const id = Number((await params).id),context=await searchParams,query=contextQuery(context),suffix=query?`?${query}`:"";
  if (!Number.isSafeInteger(id) || id <= 0) notFound();
  await ensureDatabaseOptimizations();
  const [flight, aircraft, tracks,navigation,audit,certRows,revisionRows] = await Promise.all([
    getFlight(userId, id), getAircraftOptions(userId), getFlightTracks(userId, id),getFlightNavigation(userId,id,context),getFlightAudit(userId,id),
    sql`SELECT f.*,u.display_name pilot_name FROM flights f JOIN users u ON u.id=f.user_id WHERE f.id=${id} AND f.user_id=${userId} LIMIT 1` as Promise<Array<Record<string,unknown>>>,
    sql`SELECT revision_number,certification_hash,certification_version,certified_at,superseded_at,correction_reason,snapshot_data FROM flight_certified_revisions WHERE flight_id=${id} AND user_id=${userId} ORDER BY revision_number DESC` as Promise<Array<Record<string,unknown>>>
  ]);
  if (!flight) notFound(); const update = updateFlight.bind(null, id); const remove = deleteFlight.bind(null, id);
  const certification=certRows[0]??{},certified=Boolean(certification.certified_at),certificationHash=String(certification.certification_hash??""),recordRevision=Math.max(1,Number(certification.record_revision||1)),correctionReason=String(certification.correction_reason??"").trim(),correctionDraft=!certified&&recordRevision>1&&Boolean(correctionReason),certify=certifyFlight.bind(null,id),correct=startCertifiedCorrection.bind(null,id);
  const hasCertifiedHistory=certified||revisionRows.length>0,currentIntegrity=certified?verifyFlightCertification(certification,userId):null;
  const attach=attachKmlTrack.bind(null,id),apply=applyGpsTimes.bind(null,id),dropTrack=deleteTrack.bind(null,id),detect=redetectFlightAirports.bind(null,id),toggleLock=setFlightLock.bind(null,id),locked=Boolean(flight.locked_at)||certified;
  const structuredType=[String(certification.aircraft_make??"").trim(),String(certification.aircraft_model??"").trim()||flight.aircraft_type,String(certification.aircraft_variant??"").trim()].filter(Boolean).join(" ");
  const compliance=fcl050FlightCompliance({...flight,...certification},String(certification.pilot_name??"")),blockers=blockingComplianceIssues(compliance),warnings=compliance.filter(item=>item.severity==="warning"),easa=String(flight.evidence??"").trim().toUpperCase()==="EASA";
  const badge=certified?<span className="flight-lock-badge">CERTIFIED R{recordRevision}</span>:correctionDraft?<span className="flight-lock-badge">CORRECTION R{recordRevision}</span>:locked?<span className="flight-lock-badge">LOCKED</span>:null;
  return <><header className="page-header"><div><p className="eyebrow">FLIGHT {navigation.position}/{navigation.total}</p><h1>{flight.registration} · {flight.date} {badge}</h1><p className="muted">{flight.departure} → {flight.arrival} · {flight.role} · {flight.evidence}</p></div><div className="detail-navigation"><Link className="secondary-link" href={`/flights${suffix}`}>Back to flights</Link>{navigation.previousId?<Link className="secondary-link" href={`/flights/${navigation.previousId}${suffix}`}>← Previous</Link>:null}{navigation.nextId?<Link className="secondary-link" href={`/flights/${navigation.nextId}${suffix}`}>Next →</Link>:null}{hasCertifiedHistory?<Link className="secondary-link" href={`/flights/${id}/audit`}>Audit report</Link>:null}{!locked&&!hasCertifiedHistory?<DeleteFlightButton action={remove}/>:null}</div></header><section className="flight-summary detail-summary"><div><span>BLOCK</span><strong>{formatDuration(flight.block_minutes)}</strong><small>{flight.off_block}–{flight.on_block}</small></div><div><span>AIR</span><strong>{formatDuration(flight.air_minutes)}</strong><small>{flight.takeoff}–{flight.landing}</small></div><div><span>Flight cost</span><strong>{flight.price_per_hour?`${Math.round(flight.calculated_price).toLocaleString("en-GB")} CZK`:"—"}</strong><small>{flight.price_per_hour?`${Number(flight.price_per_hour).toLocaleString("en-GB")} CZK/h · ${billingLabel(flight.billing_basis)}`:"Hourly rate missing"}</small></div><div><span>Landings</span><strong>{flight.starts}</strong><small>{flight.task||'flight'}</small></div><div><span>GPS</span><strong>{flight.gps_km.toFixed(1)} km</strong><small>{flight.track_count} tracks</small></div></section>

  {easa?<section className="panel compliance-note"><p className="eyebrow">FCL.050 CERTIFICATION READINESS</p><h2>{blockers.length?`${blockers.length} blocking ${blockers.length===1?"issue":"issues"}`:"Ready to certify"}</h2><p className="muted">The certification action is enabled only when mandatory AMC1 FCL.050 record data and applicable countersignature details are present.</p>{blockers.length?<div className="audit-changes">{blockers.map(item=><div key={item.code}><b>{item.field.replaceAll("_"," ")}</b><del>{item.message}</del></div>)}</div>:<p className="form-success">Mandatory flight-record checks passed.</p>}{warnings.length?<div className="compliance-warnings">{warnings.map(item=><p className="muted" key={item.code}>Advisory: {item.message}</p>)}</div>:null}</section>:null}

  <section className={`panel flight-lock-panel ${locked?"locked":""}`}><div><p className="eyebrow">RECORD PROTECTION</p><h2>{certified?`Pilot-certified record · Revision ${recordRevision}`:correctionDraft?`Correction draft · Revision ${recordRevision}`:locked?"Flight is locked":"Flight is editable"}</h2><p>{certified?`Revision ${recordRevision} is frozen as a certified electronic logbook record${structuredType?` · ${structuredType}`:""}. It cannot be silently edited. To correct it, open a new revision and state the reason.`:correctionDraft?`This is an editable correction of certified revision ${recordRevision-1}. The previous certified version remains immutable in revision history. Correction reason: ${correctionReason}`:locked?"Flight details, airport detection and GPS changes are protected. You can certify the checked record or unlock it for a correction.":"Check the route, UTC times, aircraft identity, pilot function and remarks before certifying the record."}</p>{certified&&certificationHash?<small>SHA-256 integrity fingerprint: {certificationHash}</small>:null}{currentIntegrity?<p className={currentIntegrity.status==="verified"?"form-success":"form-error"}>{integrityLabel(currentIntegrity)}{currentIntegrity.status==="mismatch"?" — the current record no longer matches its stored fingerprint.":""}</p>:null}</div>
    {certified?<div className="record-protection-actions"><details className="certified-correction"><summary className="secondary-button">Correct certified flight</summary><form action={correct} className="stack-form"><label>Reason for correction<textarea name="reason" minLength={8} maxLength={1000} rows={3} required placeholder="Example: Incorrect number of landings entered."/></label><p className="muted">Revision {recordRevision} will remain permanently archived with its certification hash. A new editable revision {recordRevision+1} will be opened.</p><button className="primary-button">Open correction revision {recordRevision+1}</button></form></details></div>:<div className="record-protection-actions"><form action={toggleLock}><input type="hidden" name="lock" value={locked?"no":"yes"}/><button className={locked?"secondary-link":"secondary-button"}>{locked?"Unlock flight":"Lock checked flight"}</button></form><form action={certify}><input type="hidden" name="confirm" value="certify"/><button className="primary-button" disabled={easa&&blockers.length>0} title={easa&&blockers.length?"Resolve the FCL.050 issues above before certification.":undefined}>{correctionDraft?`Certify revision ${recordRevision}`:"Certify & freeze record"}</button></form></div>}
  </section>

  {revisionRows.length||certified?<details className="panel certified-revision-history" open={correctionDraft}><summary>Certified revision history</summary><div className="flight-audit-list">{certified?<article><header><div><strong>Revision {recordRevision} · Current certified version</strong><small>{dateTime(certification.certified_at)}</small></div><span className={`audit-action ${currentIntegrity?.status==="verified"?"created":"deleted"}`}>{currentIntegrity?integrityLabel(currentIntegrity):"certified"}</span></header><p className="muted">SHA-256 {certificationHash||"—"}</p></article>:<article><header><div><strong>Revision {recordRevision} · Correction draft</strong><small>{certification.correction_opened_at?dateTime(certification.correction_opened_at):"Opened for correction"}</small></div><span className="audit-action updated">draft</span></header><p>{correctionReason}</p></article>}{revisionRows.map(row=>{const old=snapshot(row.snapshot_data),revision=Number(row.revision_number),nextRow=revisionRows.find(candidate=>Number(candidate.revision_number)===revision+1),nextSnapshot=revision+1===recordRevision?certification:nextRow?snapshot(nextRow.snapshot_data):{},changes=Object.keys(nextSnapshot).length?materialChanges(old,nextSnapshot):[],integrity=verifyFlightCertification({...old,certification_hash:row.certification_hash,certification_version:row.certification_version},userId);return <article key={String(row.revision_number)}><header><div><strong>Revision {String(row.revision_number)} · Certified and superseded</strong><small>Certified {dateTime(row.certified_at)} · Superseded {dateTime(row.superseded_at)}</small></div><span className={`audit-action ${integrity.status==="verified"?"created":"deleted"}`}>{integrityLabel(integrity)}</span></header><div className="audit-changes"><div><b>Flight</b><ins>{String(old.registration??flight.registration)} · {String(old.departure??"—")} → {String(old.arrival??"—")}</ins></div><div><b>Times</b><ins>{String(old.off_block??"—")}–{String(old.on_block??"—")} UTC</ins></div><div><b>Reason superseded</b><ins>{String(row.correction_reason??"—")}</ins></div></div>{changes.length?<div><p className="eyebrow">CHANGED IN R{revision+1}</p><div className="audit-changes">{changes.map(change=><div key={change.field}><b>{change.label}</b><del>{change.before}</del><ins>{change.after}</ins></div>)}</div></div>:null}<p className="muted">SHA-256 {String(row.certification_hash??"—")}</p></article>})}</div></details>:null}

  {tracks.length?<>{!locked?<AirportDetectionControl action={detect} departure={flight.departure} arrival={flight.arrival}/>:null}<FlightTrackPlayer tracks={tracks}/></>:<section className="panel no-track"><p className="eyebrow">GPS</p><h2>No GPS track</h2></section>}{!locked?<TrackManager flightId={id} tracks={tracks} attachAction={attach} applyAction={apply} deleteAction={dropTrack}/>:null}{!locked?<details className="panel edit-flight" open><summary>Flight details</summary><FlightForm key={`${flight.id}:${flight.registration}:${flight.departure}:${flight.arrival}:${recordRevision}`} action={update} aircraft={aircraft} initial={flight}/></details>:<section className="panel locked-flight-note"><strong>{certified?"Editing is disabled for this certified revision.":"Editing is disabled while this flight is locked."}</strong><p>{certified?"Use Correct certified flight above. The certified revision will stay immutable and the correction will be stored as a new revision.":"Unlock it above if a correction is required. Both actions will remain in the audit trail."}</p></section>}<FlightAuditPanel events={audit}/></>;
}
