import { notFound,redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { FlightForm } from "@/components/flight-form";
import { requireUser } from "@/lib/auth/require-user";
import { getAircraftOptions } from "@/lib/data/aircraft";
import { getFlightDetailFast as getFlight,getFlightNavigationFast as getFlightNavigation } from "@/lib/data/flights-fast";
import Link from "next/link";
import { deleteFlight,setFlightLock,updateFlight,attachKmlTrack,applyGpsTimes,deleteTrack,redetectFlightAirports,saveFlightExpenses } from "../actions";
import { getFlightTrackSummaries } from "@/lib/data/flight-track-review";
import { LazyFlightTrackReview } from "@/components/lazy-flight-track-review";
import { TrackManager } from "@/components/track-manager";
import { formatDuration } from "@/lib/data/dashboard";
import { AirportDetectionControl } from "@/components/airport-detection-control";
import { billingLabel } from "@/lib/billing";
import { DeleteFlightButton } from "@/components/delete-flight-button";
import { ensureDatabaseOptimizations } from "@/lib/db-optimization";
import { blockingComplianceIssues,fcl050FlightCompliance } from "@/lib/fcl050-compliance";
import { certifyFlight,startCertifiedCorrection } from "../certification-actions";
import { measureServerTask } from "@/lib/performance";
import { FlightDetailWorkspace } from "@/components/flight-detail-workspace";
import { ReadonlyLogbookEntry } from "@/components/readonly-logbook-entry";
import { sql } from "@/lib/db";
import { cancelInstructorApproval,requestInstructorApproval } from "../instructor-actions";
import { cancelSafetyInvitation,inviteCrewMember } from "../shared-actions";
import { CREW_ROLES } from "@/lib/crew";
import { costTotalsLabel,type FlightExpenseRecord } from "@/lib/flight-expenses";
import { FlightExpensesStandalone } from "@/components/flight-expenses-standalone";

type Context={q?:string;category?:string;evidence?:string;role?:string;registration?:string;aircraftClass?:string;airport?:string;route?:string;routePair?:string;gps?:string;year?:string;sort?:string;from?:string;to?:string;tab?:string};
const contextQuery=(context:Context)=>{const query=new URLSearchParams();for(const [key,value] of Object.entries(context))if(value&&key!=="tab")query.set(key,value);return query.toString()};
const storedObject=(value:unknown)=>{if(value&&typeof value==="object"&&!Array.isArray(value))return value as Record<string,unknown>;try{const parsed=JSON.parse(String(value||"{}"));return parsed&&typeof parsed==="object"&&!Array.isArray(parsed)?parsed as Record<string,unknown>:{} }catch{return{}}};

export default async function FlightDetailPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<Context>}){
  const {userId}=await requireUser();const id=Number((await params).id),context=await searchParams,query=contextQuery(context),suffix=query?`?${query}`:"";
  if(!Number.isSafeInteger(id)||id<=0)notFound();
  await ensureDatabaseOptimizations();
  const [flight,aircraft,trackSummaries,navigation,instructors,approvalRows,crewOptions,safetyRows,participantOwnRows,verificationRows,expenseRows]=await Promise.all([
    getFlight(userId,id),
    getAircraftOptions(userId),
    measureServerTask("flight-gps-summaries",()=>getFlightTrackSummaries(userId,id),400),
    getFlightNavigation(userId,id,context),
    sql`SELECT DISTINCT u.id,u.display_name FROM pilot_connections c JOIN users u ON u.id=CASE WHEN c.requester_user_id=${userId} THEN c.recipient_user_id ELSE c.requester_user_id END
      WHERE c.status='accepted' AND ((c.requester_user_id=${userId} AND (c.requester_label='instructor' OR c.relationship='recipient_instructor')) OR (c.recipient_user_id=${userId} AND (c.recipient_label='instructor' OR c.relationship='requester_instructor'))) ORDER BY u.display_name` as Promise<Array<Record<string,unknown>>>,
    sql`SELECT a.id,a.status,a.requested_at,a.decided_at,a.decision_note,a.record_revision,u.display_name instructor_name FROM instructor_flight_approvals a JOIN users u ON u.id=a.instructor_user_id JOIN flights f ON f.id=a.flight_id
      WHERE a.flight_id=${id} AND a.student_user_id=${userId} AND a.record_revision=COALESCE(f.record_revision,1) LIMIT 1` as Promise<Array<Record<string,unknown>>>,
    sql`SELECT u.id,u.display_name FROM pilot_connections c JOIN users u ON u.id=CASE WHEN c.requester_user_id=${userId} THEN c.recipient_user_id ELSE c.requester_user_id END WHERE c.status='accepted' AND (${userId} IN (c.requester_user_id,c.recipient_user_id)) ORDER BY u.display_name` as Promise<Array<Record<string,unknown>>>,
    sql`SELECT p.id,p.status,p.participant_role,p.participant_flight_id,u.display_name participant_name FROM flight_participations p JOIN users u ON u.id=p.participant_user_id JOIN flights f ON f.id=p.source_flight_id WHERE p.source_flight_id=${id} AND p.source_user_id=${userId} AND p.source_revision=COALESCE(f.record_revision,1) ORDER BY p.created_at` as Promise<Array<Record<string,unknown>>>,
    sql`SELECT own.id FROM flights own WHERE own.id=${id} AND own.user_id=${userId} AND (
      EXISTS(SELECT 1 FROM flight_participations p LEFT JOIN flights source ON source.id=p.source_flight_id AND source.user_id=p.source_user_id WHERE p.participant_user_id=${userId} AND (p.participant_flight_id=own.id OR (p.participant_flight_id IS NULL AND source.id IS NOT NULL AND source.date::text=own.date::text AND UPPER(TRIM(source.registration))=UPPER(TRIM(own.registration)) AND COALESCE(source.off_block,'')=COALESCE(own.off_block,'') AND UPPER(TRIM(COALESCE(source.departure,'')))=UPPER(TRIM(COALESCE(own.departure,''))) AND UPPER(TRIM(COALESCE(source.arrival,'')))=UPPER(TRIM(COALESCE(own.arrival,''))))))
      OR EXISTS(SELECT 1 FROM instructor_flight_approvals a JOIN flights source ON source.id=a.flight_id AND source.user_id=a.student_user_id WHERE a.instructor_user_id=${userId} AND a.status='approved' AND source.date::text=own.date::text AND UPPER(TRIM(source.registration))=UPPER(TRIM(own.registration)) AND COALESCE(source.off_block,'')=COALESCE(own.off_block,'') AND UPPER(TRIM(COALESCE(source.departure,'')))=UPPER(TRIM(COALESCE(own.departure,''))) AND UPPER(TRIM(COALESCE(source.arrival,'')))=UPPER(TRIM(COALESCE(own.arrival,''))))
    ) LIMIT 1` as Promise<Array<Record<string,unknown>>>,
    sql`SELECT v.id,v.signer_user_id,v.signed_at,v.credential_snapshot,u.display_name signer_name FROM flight_verifications v JOIN flights f ON f.id=v.flight_id AND f.user_id=v.flight_user_id LEFT JOIN users u ON u.id=v.signer_user_id WHERE v.flight_id=${id} AND v.flight_user_id=${userId} AND v.record_revision=COALESCE(f.record_revision,1) AND v.flight_hash=f.certification_hash AND v.status='signed' AND v.verification_role=CASE WHEN UPPER(COALESCE(f.role,''))='DUAL' THEN 'INSTRUCTOR' ELSE 'SUPERVISING PIC' END ORDER BY v.id DESC LIMIT 1` as Promise<Array<Record<string,unknown>>>,
    sql`SELECT id,category,label,amount_minor,currency,created_at::text created_at FROM flight_expenses WHERE user_id=${userId} AND flight_id=${id} ORDER BY id` as unknown as Promise<FlightExpenseRecord[]>,
  ]);
  if(!flight)notFound();
  const raw=flight as unknown as Record<string,unknown>,pilotName=String(raw.pilot_name??"");
  const expenses=expenseRows as FlightExpenseRecord[],update=updateFlight.bind(null,id),remove=deleteFlight.bind(null,id),saveExpenses=saveFlightExpenses.bind(null,id);
  async function removeParticipant(){
    "use server";
    const {userId:ownerId}=await requireUser();await ensureDatabaseOptimizations();
    const owned=await sql`SELECT own.id FROM flights own WHERE own.id=${id} AND own.user_id=${ownerId} AND own.certified_at IS NULL AND (
      EXISTS(SELECT 1 FROM flight_participations p LEFT JOIN flights source ON source.id=p.source_flight_id AND source.user_id=p.source_user_id WHERE p.participant_user_id=${ownerId} AND (p.participant_flight_id=own.id OR (p.participant_flight_id IS NULL AND source.id IS NOT NULL AND source.date::text=own.date::text AND UPPER(TRIM(source.registration))=UPPER(TRIM(own.registration)) AND COALESCE(source.off_block,'')=COALESCE(own.off_block,'') AND UPPER(TRIM(COALESCE(source.departure,'')))=UPPER(TRIM(COALESCE(own.departure,''))) AND UPPER(TRIM(COALESCE(source.arrival,'')))=UPPER(TRIM(COALESCE(own.arrival,''))))))
      OR EXISTS(SELECT 1 FROM instructor_flight_approvals a JOIN flights source ON source.id=a.flight_id AND source.user_id=a.student_user_id WHERE a.instructor_user_id=${ownerId} AND a.status='approved' AND source.date::text=own.date::text AND UPPER(TRIM(source.registration))=UPPER(TRIM(own.registration)) AND COALESCE(source.off_block,'')=COALESCE(own.off_block,'') AND UPPER(TRIM(COALESCE(source.departure,'')))=UPPER(TRIM(COALESCE(own.departure,''))) AND UPPER(TRIM(COALESCE(source.arrival,'')))=UPPER(TRIM(COALESCE(own.arrival,''))))
    ) AND NOT EXISTS(SELECT 1 FROM flight_participations outbound WHERE outbound.source_flight_id=own.id AND outbound.source_user_id=own.user_id AND outbound.status IN ('pending','accepted')) LIMIT 1` as Array<{id:number|string}>;
    if(!owned[0])return;
    const result=await sql.transaction([
      sql`UPDATE flights SET locked_at=NULL,locked_by_user_id=NULL WHERE id=${id} AND user_id=${ownerId} AND certified_at IS NULL`,
      sql`UPDATE flight_participations SET participant_flight_id=NULL WHERE participant_user_id=${ownerId} AND participant_flight_id=${id}`,
      sql`DELETE FROM track_points WHERE user_id=${ownerId} AND track_id IN(SELECT id FROM flight_tracks WHERE user_id=${ownerId} AND flight_id=${id})`,
      sql`DELETE FROM flight_tracks WHERE user_id=${ownerId} AND flight_id=${id}`,
      sql`DELETE FROM flight_verifications WHERE flight_id=${id} AND flight_user_id=${ownerId}`,
      sql`DELETE FROM flight_certified_revisions WHERE flight_id=${id} AND user_id=${ownerId}`,
      sql`DELETE FROM flights WHERE id=${id} AND user_id=${ownerId} AND certified_at IS NULL RETURNING id`,
    ]);
    if(!(result[6] as Array<{id:number|string}>)[0])return;
    revalidatePath("/dashboard");revalidatePath("/flights");revalidatePath("/map");revalidatePath("/data");revalidatePath("/export");redirect("/flights");
  }
  const certified=Boolean(flight.certified_at),recordRevision=Math.max(1,Number(flight.record_revision||1)),correctionReason=String(flight.correction_reason??"").trim(),correctionDraft=!certified&&recordRevision>1&&Boolean(correctionReason),certify=certifyFlight.bind(null,id),correct=startCertifiedCorrection.bind(null,id);
  const hasCertifiedHistory=certified||recordRevision>1||Boolean(correctionReason),participantOwned=Boolean(participantOwnRows[0]);
  const attach=attachKmlTrack.bind(null,id),apply=applyGpsTimes.bind(null,id),dropTrack=deleteTrack.bind(null,id),detect=redetectFlightAirports.bind(null,id),toggleLock=setFlightLock.bind(null,id),locked=Boolean(flight.locked_at)||certified;
  const compliance=fcl050FlightCompliance(raw,pilotName),blockers=blockingComplianceIssues(compliance),easa=String(flight.evidence??"").trim().toUpperCase()==="EASA";
  const badge=certified?<span className="flight-lock-badge">CERTIFIED R{recordRevision}</span>:correctionDraft?<span className="flight-lock-badge">CORRECTION R{recordRevision}</span>:locked?<span className="flight-lock-badge">LOCKED</span>:null;
  const displayDate=/^\d{4}-\d{2}-\d{2}$/.test(flight.date)?new Date(`${flight.date}T00:00:00`).toLocaleDateString("en-GB"):flight.date;
  const role=String(flight.role??"").trim().toUpperCase(),approval=approvalRows[0],verification=verificationRows[0],verificationCredentials=storedObject(verification?.credential_snapshot),inPersonSigned=Boolean(verification)&&String(verificationCredentials.source??"")==="In-person handwritten signature",flyTallySigned=Boolean(verification)&&!inPersonSigned,verificationName=inPersonSigned?String(verificationCredentials.identity??"Instructor"):String(verification?.signer_name??approval?.instructor_name??"Instructor"),trainingRole=["DUAL","SPIC","PICUS"].includes(role),requestApproval=requestInstructorApproval.bind(null,id),cancelApproval=cancelInstructorApproval.bind(null,id);
  const verificationState=verification?inPersonSigned?"in-person":"flytally":"";
  const approvalClass=verification?"approved":String(approval?.status??"");
  const approvalPanel=trainingRole?<section className={`panel instructor-approval-panel ${approvalClass}`}><div><p className="eyebrow">CREW VERIFICATION</p><h2>{verificationState==="in-person"?"SIGNED IN PERSON":verificationState==="flytally"?"SIGNED IN FLYTALLY":approval?.status==="pending"?"Waiting for instructor":approval?.status==="declined"?"Approval declined":"Instructor confirmation"}</h2><p className="muted">{verification?`${verificationName} signed certified revision R${recordRevision}${inPersonSigned?" in person on this device.":" through their FlyTally account."}`:approval?.status==="pending"?`Request sent automatically to ${String(approval.instructor_name)}. They can review, sign and add their own logbook entry.`:approval?.status==="declined"?`${String(approval.instructor_name)} declined the request${approval.decision_note?`: ${String(approval.decision_note)}`:"."}`:certified?"Use a connected FlyTally instructor, or let an instructor without FlyTally sign this certified revision directly on this device.":"Choose the actual instructor or supervising PIC in Logbook data. FlyTally will send the certified revision automatically when the name matches a connected instructor."}</p></div><div className="record-protection-actions">{verification?inPersonSigned?<Link className="secondary-button" href={`/flights/${id}/in-person-signature`}>View signature evidence</Link>:<Link className="secondary-button" href={`/flights/${id}/audit`}>View verification</Link>:approval?.status==="pending"?<form action={cancelApproval}><input type="hidden" name="approval_id" value={String(approval.id)}/><button className="secondary-button">Cancel request</button></form>:certified&&(!approval||["declined","cancelled","superseded"].includes(String(approval.status)))?<>{instructors.length?<form action={requestApproval} className="instructor-request-form">{instructors.length===1?<input type="hidden" name="instructor_id" value={String(instructors[0].id)}/>:<label>Instructor<select name="instructor_id" required>{instructors.map(row=><option value={String(row.id)} key={String(row.id)}>{String(row.display_name)}</option>)}</select></label>}<button className="primary-button">Request approval{instructors.length===1?` from ${String(instructors[0].display_name)}`:""}</button></form>:<Link className="secondary-button" href="/connections">Connect an instructor</Link>}<Link className="secondary-button" href={`/flights/${id}/in-person-signature`}>Instructor without FlyTally · Sign on this device</Link></>:null}</div></section>:null;
  const inviteCrew=inviteCrewMember.bind(null,id),cancelCrew=cancelSafetyInvitation.bind(null,id),availableRoles=CREW_ROLES.filter(item=>item!=="SAFETY PILOT"||role==="PIC");
  const crewPanel=certified?<details className="panel flight-secondary-panel"><summary><span><strong>Crew & logbook sharing</strong><small>{safetyRows.length?`${safetyRows.length} existing ${safetyRows.length===1?"invitation":"invitations"}`:"Invite another pilot only when needed"}</small></span></summary><div className="flight-secondary-panel-body"><p className="muted">Invite another connected pilot. They review the exact certified flight before creating their own editable draft.</p>{safetyRows.length?<div className="crew-invite-list">{safetyRows.map(member=><div key={String(member.id)}><span><strong>{String(member.participant_name)}</strong><small>{String(member.participant_role)} · {String(member.status)}</small></span>{member.status==="pending"?<form action={cancelCrew}><input type="hidden" name="participation_id" value={String(member.id)}/><button className="secondary-button">Cancel</button></form>:null}</div>)}</div>:null}{crewOptions.length?<form action={inviteCrew} className="instructor-request-form"><label>Pilot<select name="participant_id" required>{crewOptions.map(row=><option value={String(row.id)} key={String(row.id)}>{String(row.display_name)}</option>)}</select></label><label>Role<select name="participant_role" required>{availableRoles.map(item=><option key={item}>{item}</option>)}</select></label><button className="primary-button">Send invitation</button></form>:<Link className="secondary-button" href="/connections">Connect a pilot</Link>}</div></details>:null;
  const overview=<>
    <section className="flight-summary detail-summary"><div><span>BLOCK</span><strong>{formatDuration(flight.block_minutes)}</strong><small>{flight.off_block}–{flight.on_block}</small></div><div><span>AIR</span><strong>{formatDuration(flight.air_minutes)}</strong><small>{flight.takeoff}–{flight.landing}</small></div><div><span>Costs</span><strong>{costTotalsLabel(expenses,flight.price_per_hour?Number(flight.calculated_price||0):0)}</strong><small>{flight.price_per_hour?`${Number(flight.price_per_hour).toLocaleString("en-GB")} CZK/h · ${billingLabel(flight.billing_basis)}${expenses.length?` · ${expenses.length} additional`:""}`:expenses.length?`${expenses.length} additional expenses`:"Hourly rate missing"}</small></div><div><span>Landings</span><strong>{flight.starts}</strong><small>{flight.task||"flight"}</small></div><div><span>GPS</span><strong>{flight.gps_km.toFixed(1)} km</strong><small>{flight.track_count} tracks</small></div></section>
    {locked?<FlightExpensesStandalone action={saveExpenses} initial={expenses} aircraftCost={flight.price_per_hour?Number(flight.calculated_price||0):0}/>:null}
    <section className={`panel flight-lock-panel ${locked?"locked":""}`}><div><p className="eyebrow">RECORD STATUS</p><h2>{certified?`Certified revision ${recordRevision}`:correctionDraft?`Correction revision ${recordRevision}`:locked?"Locked":"Ready for review"}</h2><p className="muted">{certified?"This revision is protected. Use Correct flight only when a recorded value is wrong.":correctionDraft?correctionReason:locked?"Unlock the record to edit it.":"Review Logbook data, then certify the final record."}</p>{easa&&blockers.length?<div className="compliance-warnings"><strong>{blockers.length===1?"1 issue must be fixed before certification":`${blockers.length} issues must be fixed before certification`}</strong>{blockers.map(item=><p className="form-error" key={item.code}>{item.message}</p>)}<small>Open the Logbook data tab to correct the highlighted information.</small></div>:null}</div>
      {certified?<div className="record-protection-actions"><details className="certified-correction"><summary className="secondary-button">Correct flight</summary><form action={correct} className="stack-form"><label>Reason for correction<textarea name="reason" minLength={8} maxLength={1000} rows={3} required placeholder="Example: Incorrect number of landings entered."/></label><p className="muted">The current revision stays archived. A new editable revision {recordRevision+1} will be created.</p><button className="primary-button">Open correction R{recordRevision+1}</button></form></details></div>:<div className="record-protection-actions"><form action={toggleLock}><input type="hidden" name="lock" value={locked?"no":"yes"}/><button className="secondary-link">{locked?"Unlock record":"Lock without certification"}</button></form><form action={certify}><input type="hidden" name="confirm" value="certify"/><button className="primary-button" disabled={easa&&blockers.length>0} title={easa&&blockers.length?"Resolve the listed issues before certification.":undefined}>{correctionDraft?`Certify revision ${recordRevision}`:"Certify flight"}</button></form></div>}
    </section>
    {approvalPanel}
    {crewPanel}
  </>;
  const gps=<>{trackSummaries.length?<>{!locked?<AirportDetectionControl action={detect} departure={flight.departure} arrival={flight.arrival}/>:null}<LazyFlightTrackReview flightId={id} current={{offBlock:String(flight.off_block??""),takeoff:String(flight.takeoff??""),landing:String(flight.landing??""),onBlock:String(flight.on_block??""),landings:Number(flight.starts??0)}}/></>:<section className="panel no-track"><p className="eyebrow">GPS</p><h2>No GPS track</h2><p className="muted">This flight has no attached GPS data.</p></section>}{!locked?<TrackManager flightId={id} tracks={trackSummaries} attachAction={attach} applyAction={apply} deleteAction={dropTrack}/>:null}</>;
  const instructorOptions=instructors.map(row=>({name:String(row.display_name??"").trim()})).filter(item=>item.name);
  const logbookRaw=verification?{...raw,approval_id:verification.id,instructor_approval_name:verificationName}:raw;
  const logbook=!locked?<section className="panel logbook-edit-panel"><header><div><p className="eyebrow">LOGBOOK DATA</p><h2>Edit flight record</h2><p className="muted">Changes are saved only when you press Save flight at the end of the form.</p></div></header><FlightForm key={`${flight.id}:${flight.registration}:${flight.departure}:${flight.arrival}:${recordRevision}`} action={update} aircraft={aircraft} initial={flight} instructors={instructorOptions} expenses={expenses}/></section>:<ReadonlyLogbookEntry row={logbookRaw} pilotName={pilotName} certified={certified} easa={easa}/>;
  return <>
    <header className="page-header"><div><p className="eyebrow">FLIGHT {navigation.position}/{navigation.total}</p><h1>{flight.registration} · {displayDate} {badge}</h1><p className="muted">{flight.departure} → {flight.arrival} · {flight.role} · {flight.evidence}</p></div><div className="detail-navigation"><Link className="secondary-link" href={`/flights${suffix}`}>Back to flights</Link>{navigation.previousId?<Link className="secondary-link" href={`/flights/${navigation.previousId}${suffix}`}>← Previous</Link>:null}{navigation.nextId?<Link className="secondary-link" href={`/flights/${navigation.nextId}${suffix}`}>Next →</Link>:null}{hasCertifiedHistory?<Link className="secondary-link" href={`/flights/${id}/audit`}>Audit report</Link>:null}{participantOwned&&!certified?<DeleteFlightButton action={removeParticipant} label="Remove from my logbook" confirmLabel="Remove my entry"/>:!locked&&!hasCertifiedHistory?<DeleteFlightButton action={remove}/>:null}</div></header>
    <FlightDetailWorkspace overview={overview} gps={gps} logbook={logbook} gpsCount={trackSummaries.length} initialTab={context.tab==="logbook"?"logbook":context.tab==="gps"?"gps":"overview"}/>
  </>;
}
