import assert from "node:assert/strict";import test from "node:test";import fs from "node:fs";import path from "node:path";
const root=path.resolve(import.meta.dirname,".."),read=(file:string)=>fs.readFileSync(path.join(root,file),"utf8");
test("v1.32 removes request-path emergency cleanup and render-time self repair",()=>{const layout=read("app/(protected)/layout.tsx"),connections=read("app/(protected)/connections/page.tsx");assert.doesNotMatch(layout,/legacy-flight-380|legacy-instructor-approval-1|cleanupLegacyData/);assert.doesNotMatch(connections,/UPDATE flight_participations/);assert.match(connections,/Flight requests/);assert.match(connections,/\/connections\/shared\//)});
test("v1.32 backfills old instructor requests into participation workflow",()=>{const schema=read("lib/v132-schema.ts"),helper=read("lib/training-verification.ts");assert.match(schema,/INSERT INTO flight_participations/);assert.match(schema,/approval_id/);assert.match(schema,/UPDATE user_notifications/);assert.match(helper,/NOT EXISTS\(SELECT 1 FROM flight_verifications/)});
test("v1.32 stores structured FCL.140.A purpose and protects it in certification v3",()=>{const schema=read("lib/v132-schema.ts"),form=read("components/flight-form.tsx"),integrity=read("lib/certification-integrity.ts"),cert=read("app/(protected)/flights/certification-actions.ts");assert.match(schema,/purpose_code/);assert.match(form,/Training purpose/);assert.match(form,/LAPL recency does not depend on free-text wording/);assert.match(integrity,/purposeCode:text\(row\.purpose_code\)/);assert.match(cert,/certification_version=3/)});
test("v1.32 closes pending connected requests when an in-person signature is used",()=>{const route=read("app/(protected)/flights/[id]/in-person-signature/page.tsx");assert.match(route,/UPDATE flight_participations SET status='cancelled'/);assert.match(route,/Completed with an in-person signature on the pilot device/)});
test("v1.32 moves dashboard aggregation into PostgreSQL",()=>{const dashboard=read("lib/data/dashboard.ts");assert.match(dashboard,/FILTER\(WHERE/);assert.match(dashboard,/jsonb_agg/);assert.doesNotMatch(dashboard,/rawRows\.map/)});
test("v1.32 print supports optional range and derives FI signature from verification evidence",()=>{const hub=read("components/data-hub.tsx"),print=read("app/(protected)/print/page.tsx");assert.match(hub,/name="from"/);assert.match(hub,/name="to"/);assert.match(print,/flight_verifications/);assert.match(print,/FI SIGNED:/)});
test("v1.32 adds a web verification CI gate",()=>{const workflow=read(".github/workflows/verify-web.yml"),pkg=JSON.parse(read("package.json"));assert.match(workflow,/npm ci/);assert.match(workflow,/npm run typecheck/);assert.match(workflow,/npm run build/);assert.equal(pkg.version,"1.32.0")});
