import assert from "node:assert/strict";import test from "node:test";import fs from "node:fs";import path from "node:path";import { isLaplRefresherPurpose } from "../lib/flight-purpose.ts";import { releaseAtLeast } from "./release-version.ts";
const root=path.resolve(import.meta.dirname,".."),read=(file:string)=>fs.readFileSync(path.join(root,file),"utf8");
test("v1.32.2 structured FCL.140.A purpose remains a behavioral marker",()=>{assert.equal(isLaplRefresherPurpose("LAPL_FCL140A_REFRESHER"),true);assert.equal(isLaplRefresherPurpose(""),false)});
test("v1.32.2 LAPL rolling recency includes eligible ULL time and landings",()=>{const page=read("app/(protected)/credentials/page.tsx");assert.match(page,/UPPER\(COALESCE\(f\.evidence,''\)\)='ULL'/);assert.match(page,/UPPER\(COALESCE\(f\.aircraft_class,''\)\)='ULL'/);assert.match(page,/ull_flight_minutes/);assert.match(page,/ull_landings/);assert.match(page,/CAA-ZLP-165 §2\.1\.9/)});
test("v1.32.2 ULL never satisfies the one-hour FI refresher requirement",()=>{const page=read("app/(protected)/credentials/page.tsx");assert.match(page,/UPPER\(COALESCE\(f\.evidence,''\)\)<>'ULL'/);assert.match(page,/LAPL_FCL140A_REFRESHER/);assert.match(page,/v\.flight_hash=f\.certification_hash/);assert.match(page,/ULL does not count for this 1 hour/)});
test("v1.32.2 retains legacy refresher text only as fallback when structured purpose is absent",()=>{const page=read("app/(protected)/credentials/page.tsx");assert.match(page,/COALESCE\(f\.purpose_code,''\)=''/);assert.match(page,/refresher\[\[:space:\]\]\+training/)});
test("v1.32.2 instructor verification can be revoked and signed again from unified request UI",()=>{const page=read("app/(protected)/connections/shared/[id]/page.tsx");assert.match(page,/revokeFlightVerification/);assert.match(page,/name="verification_id"/);assert.match(page,/Revoke verification/);assert.match(page,/VERIFICATION REVOKED/);assert.match(page,/Sign again/)});
test("v1.32.2 print derives FCL.140.A marker from structured purpose",()=>{const print=read("app/(protected)/print/page.tsx");assert.match(print,/isLaplRefresherPurpose/);assert.match(print,/f\.purpose_code/);assert.match(print,/FCL\.140\.A REFRESHER/)});
test("v1.32.2 closure features remain present in subsequent release family",()=>{assert.ok(releaseAtLeast(JSON.parse(read("package.json")).version,1,32,2))});
