import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
const form=fs.readFileSync("components/flight-form.tsx","utf8"),actions=fs.readFileSync("app/(protected)/flights/actions.ts","utf8"),schema=fs.readFileSync("lib/v159-schema.ts","utf8"),backup=fs.readFileSync("lib/account-backup.ts","utf8"),trash=fs.readFileSync("lib/flight-trash.ts","utf8"),layout=fs.readFileSync("app/layout.tsx","utf8"),pkg=JSON.parse(fs.readFileSync("package.json","utf8"));
test("v1.59 metadata and final UX layer are active",()=>{const [major,minor]=String(pkg.version).split(".").map(Number);assert.ok(major>1||(major===1&&minor>=59));assert.ok(layout.indexOf("v159-flight-entry-structure.css")>layout.indexOf("v158-flight-entry-polish.css"))});
test("flight entry keeps regulatory movement evidence in experience while B4 moves optional time detail",()=>{for(const label of ["Flight essentials","Flight experience","Role details","Aircraft & logbook","Optional details","Costs","Notes"])assert.ok(form.includes(label));const experience=form.indexOf("Flight experience"),roleDetails=form.indexOf("Role details"),logbook=form.indexOf("Aircraft & logbook"),optional=form.indexOf("Optional details");for(const field of ["Day landings","Night landings","movementEvidenceRecorded"])assert.ok(form.indexOf(field)>experience&&form.indexOf(field)<roleDetails,`${field} must stay inside Flight experience`);for(const field of ["Night time","IFR time"])assert.ok(form.indexOf(field)>optional,`${field} must be inside Optional details`);assert.ok(form.indexOf("verificationName")>roleDetails&&form.indexOf("verificationName")<logbook);const purposePicker=form.indexOf("<FlightPurposePicker",optional);assert.ok(purposePicker>logbook&&purposePicker>optional)});
test("expenses are user-owned financial metadata outside flight certification fields",()=>{assert.match(schema,/FOREIGN KEY\(flight_id,user_id\) REFERENCES flights\(id,user_id\) ON DELETE CASCADE/);assert.match(actions,/flight_expenses/);assert.doesNotMatch(fs.readFileSync("lib/flight-input.ts","utf8"),/expenseCategory|flight_expenses/);assert.doesNotMatch(fs.readFileSync("lib/certification-integrity.ts","utf8"),/flight_expenses|expenseCategory/)});
test("backup and trash preserve structured expense rows regardless of later portable-backup format additions",()=>{assert.match(backup,/flight_expenses/);assert.match(trash,/expenses_data/);assert.match(trash,/restored_expenses/)});
test("v1.59 retains regulatory and aircraft integrity safety nets",()=>{for(const path of ["tests/v151-regulatory-correctness.test.ts","tests/v1511-legacy-recency.test.ts","tests/v1512-recency-provenance.test.ts","tests/v1513-automatic-ull-credit.test.ts","tests/v1531-aircraft-state.test.ts","tests/v1543-aircraft-catalog.test.ts","tests/v156-mobile-layout-audit.test.ts","tests/v158-flight-entry-polish.test.ts"])assert.equal(fs.existsSync(path),true,`${path} must remain`)});
