import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
const form=fs.readFileSync("components/flight-form.tsx","utf8"),actions=fs.readFileSync("app/(protected)/flights/actions.ts","utf8"),schema=fs.readFileSync("lib/v159-schema.ts","utf8"),backup=fs.readFileSync("lib/account-backup.ts","utf8"),trash=fs.readFileSync("lib/flight-trash.ts","utf8"),layout=fs.readFileSync("app/layout.tsx","utf8"),pkg=JSON.parse(fs.readFileSync("package.json","utf8"));
test("v1.59 metadata and final UX layer are active",()=>{assert.equal(pkg.version,"1.59.0");assert.ok(layout.indexOf("v159-flight-entry-structure.css")>layout.indexOf("v158-flight-entry-polish.css"))});
test("flight entry groups experience instead of splitting EASA movement fields",()=>{for(const label of ["Flight essentials","Flight experience","Crew & training","Aircraft & logbook","Costs","Notes"])assert.ok(form.includes(label));const experience=form.indexOf("Flight experience"),crew=form.indexOf("Crew & training"),logbook=form.indexOf("Aircraft & logbook");for(const field of ["Day landings","Night landings","Night time","IFR time","movementEvidenceRecorded"])assert.ok(form.indexOf(field)>experience&&form.indexOf(field)<crew,`${field} must be inside Flight experience`);assert.ok(form.indexOf("verificationName")>crew&&form.indexOf("verificationName")<logbook)});
test("expenses are user-owned financial metadata outside flight certification fields",()=>{assert.match(schema,/FOREIGN KEY\(flight_id,user_id\) REFERENCES flights\(id,user_id\) ON DELETE CASCADE/);assert.match(actions,/flight_expenses/);assert.doesNotMatch(fs.readFileSync("lib/flight-input.ts","utf8"),/expenseCategory|flight_expenses/);assert.doesNotMatch(fs.readFileSync("lib/certification-integrity.ts","utf8"),/flight_expenses|expenseCategory/)});
test("backup and trash preserve structured expense rows",()=>{assert.match(backup,/version:8/);assert.match(backup,/flight_expenses/);assert.match(trash,/expenses_data/);assert.match(trash,/restored_expenses/)});
test("v1.59 retains regulatory and aircraft integrity safety nets",()=>{for(const path of ["tests/v151-regulatory-correctness.test.ts","tests/v1511-legacy-recency.test.ts","tests/v1512-recency-provenance.test.ts","tests/v1513-automatic-ull-credit.test.ts","tests/v1531-aircraft-state.test.ts","tests/v1543-aircraft-catalog.test.ts","tests/v156-mobile-layout-audit.test.ts","tests/v158-flight-entry-polish.test.ts"])assert.equal(fs.existsSync(path),true,`${path} must remain`)});
