"use server";
import { revalidatePath } from "next/cache";
import { requireUser } from "@/lib/auth/require-user";
import { sql } from "@/lib/db";
const s=(f:FormData,k:string)=>String(f.get(k)??"").trim(); const n=(f:FormData,k:string)=>{const v=Number(s(f,k));return Number.isFinite(v)?v:null};
export async function saveAircraft(form:FormData){const {userId}=await requireUser();const id=n(form,"id"),reg=s(form,"registration").toUpperCase();if(!reg)return;if(id)await sql`UPDATE aircraft SET registration=${reg},aircraft_type=${s(form,"aircraft_type")},icao_type=${s(form,"icao_type")},aircraft_class=${s(form,"aircraft_class")},evidence=${s(form,"evidence")},default_price_per_hour=${n(form,"default_price_per_hour")},default_role=${s(form,"default_role")||"PIC"},billing_basis=${s(form,"billing_basis")||"BLOCK"},note=${s(form,"note")},updated_at=NOW() WHERE id=${id} AND user_id=${userId}`;else await sql`INSERT INTO aircraft(user_id,registration,aircraft_type,icao_type,aircraft_class,evidence,default_price_per_hour,default_role,billing_basis,active,note,created_at,updated_at) VALUES(${userId},${reg},${s(form,"aircraft_type")},${s(form,"icao_type")},${s(form,"aircraft_class")},${s(form,"evidence")},${n(form,"default_price_per_hour")},${s(form,"default_role")||"PIC"},${s(form,"billing_basis")||"BLOCK"},1,${s(form,"note")},NOW(),NOW()) ON CONFLICT(user_id,registration) DO UPDATE SET aircraft_type=EXCLUDED.aircraft_type,icao_type=EXCLUDED.icao_type,aircraft_class=EXCLUDED.aircraft_class,evidence=EXCLUDED.evidence,default_price_per_hour=EXCLUDED.default_price_per_hour,default_role=EXCLUDED.default_role,billing_basis=EXCLUDED.billing_basis,note=EXCLUDED.note,updated_at=NOW()`;revalidatePath("/database");}
export async function toggleAircraft(form:FormData){const {userId}=await requireUser();await sql`UPDATE aircraft SET active=CASE WHEN active=1 THEN 0 ELSE 1 END,updated_at=NOW() WHERE id=${n(form,"id")} AND user_id=${userId}`;revalidatePath("/database");}
export async function saveRate(form:FormData){const {userId}=await requireUser();const reg=s(form,"registration").toUpperCase(),valid=s(form,"valid_from")||null;if(!reg)return;await sql`INSERT INTO rates(user_id,registration,aircraft_type,valid_from,price_per_hour,dry_price_per_hour,source) VALUES(${userId},${reg},${s(form,"aircraft_type")},${valid},${n(form,"price_per_hour")},${n(form,"dry_price_per_hour")},${s(form,"source")||"Ruční"}) ON CONFLICT(user_id,registration,valid_from) DO UPDATE SET aircraft_type=EXCLUDED.aircraft_type,price_per_hour=EXCLUDED.price_per_hour,dry_price_per_hour=EXCLUDED.dry_price_per_hour,source=EXCLUDED.source`;revalidatePath("/database");}
export async function deleteRate(form:FormData){const {userId}=await requireUser();await sql`DELETE FROM rates WHERE id=${n(form,"id")} AND user_id=${userId}`;revalidatePath("/database");}
export async function saveAirport(form:FormData){const {userId}=await requireUser();const ident=s(form,"ident").toUpperCase();if(!ident)return;await sql`INSERT INTO airports(user_id,ident,name,municipality,iso_country,latitude_deg,longitude_deg,active,closed,source,updated_at) VALUES(${userId},${ident},${s(form,"name")},${s(form,"municipality")},${s(form,"iso_country").toUpperCase()},${n(form,"latitude_deg")},${n(form,"longitude_deg")},1,0,'Ruční',NOW()) ON CONFLICT(user_id,ident) DO UPDATE SET name=EXCLUDED.name,municipality=EXCLUDED.municipality,iso_country=EXCLUDED.iso_country,latitude_deg=EXCLUDED.latitude_deg,longitude_deg=EXCLUDED.longitude_deg,active=1,updated_at=NOW()`;revalidatePath("/database");}
