"use server";
import { revalidatePath } from "next/cache";
import { requireUser } from "@/lib/auth/require-user";
import { sql } from "@/lib/db";
import { serializeBilling } from "@/lib/billing";
import { validIsoDate } from "@/lib/rate-history";
import { airportCodeMigrations,canonicalAirportIdent } from "@/lib/airport-catalog";
const s=(f:FormData,k:string)=>String(f.get(k)??"").trim(); const n=(f:FormData,k:string)=>{const v=Number(s(f,k));return Number.isFinite(v)?v:null};
function refreshPricing(){revalidatePath("/database");revalidatePath("/flights/new");revalidatePath("/flights");revalidatePath("/dashboard");}
export async function saveAircraft(form:FormData){const {userId}=await requireUser();const id=n(form,"id"),reg=s(form,"registration").toUpperCase(),billing=serializeBilling(s(form,"billing_basis"),s(form,"billing_share"));if(!reg)return;if(id){await sql`UPDATE aircraft SET aircraft_type=${s(form,"aircraft_type")},icao_type=${s(form,"icao_type")},aircraft_class=${s(form,"aircraft_class")},evidence=${s(form,"evidence")},default_role=${s(form,"default_role")||"PIC"},billing_basis=${billing},note=${s(form,"note")},updated_at=NOW() WHERE id=${id} AND user_id=${userId} AND UPPER(TRIM(registration))=${reg}`}else{const initialPrice=n(form,"initial_price_per_hour"),validFrom=s(form,"initial_valid_from"),queries=[sql`INSERT INTO aircraft(user_id,registration,aircraft_type,icao_type,aircraft_class,evidence,default_price_per_hour,default_role,billing_basis,active,note,created_at,updated_at) VALUES(${userId},${reg},${s(form,"aircraft_type")},${s(form,"icao_type")},${s(form,"aircraft_class")},${s(form,"evidence")},${initialPrice},${s(form,"default_role")||"PIC"},${billing},1,${s(form,"note")},NOW(),NOW()) ON CONFLICT(user_id,registration) DO UPDATE SET aircraft_type=EXCLUDED.aircraft_type,icao_type=EXCLUDED.icao_type,aircraft_class=EXCLUDED.aircraft_class,evidence=EXCLUDED.evidence,default_role=EXCLUDED.default_role,billing_basis=EXCLUDED.billing_basis,note=EXCLUDED.note,active=1,updated_at=NOW()`];if(initialPrice!==null&&initialPrice>0&&validIsoDate(validFrom))queries.push(sql`INSERT INTO rates(user_id,registration,aircraft_type,valid_from,price_per_hour,dry_price_per_hour,source) VALUES(${userId},${reg},${s(form,"aircraft_type")},${validFrom},${initialPrice},NULL,'Initial rate') ON CONFLICT(user_id,registration,valid_from) DO UPDATE SET aircraft_type=EXCLUDED.aircraft_type,price_per_hour=EXCLUDED.price_per_hour,source=EXCLUDED.source`);await sql.transaction(queries)}refreshPricing();}
export async function toggleAircraft(form:FormData){const {userId}=await requireUser();await sql`UPDATE aircraft SET active=CASE WHEN active=1 THEN 0 ELSE 1 END,updated_at=NOW() WHERE id=${n(form,"id")} AND user_id=${userId}`;revalidatePath("/database");revalidatePath("/flights/new");revalidatePath("/flights");}
export async function saveRate(form:FormData){const {userId}=await requireUser();const reg=s(form,"registration").toUpperCase(),valid=s(form,"valid_from"),price=n(form,"price_per_hour");if(!reg||!validIsoDate(valid)||price===null||price<=0)return;await sql`INSERT INTO rates(user_id,registration,aircraft_type,valid_from,price_per_hour,dry_price_per_hour,source) VALUES(${userId},${reg},${s(form,"aircraft_type")},${valid},${price},${n(form,"dry_price_per_hour")},${s(form,"source")||"Aircraft rate change"}) ON CONFLICT(user_id,registration,valid_from) DO UPDATE SET aircraft_type=EXCLUDED.aircraft_type,price_per_hour=EXCLUDED.price_per_hour,dry_price_per_hour=EXCLUDED.dry_price_per_hour,source=EXCLUDED.source`;refreshPricing();}
export async function deleteRate(form:FormData){const {userId}=await requireUser();await sql`DELETE FROM rates WHERE id=${n(form,"id")} AND user_id=${userId}`;refreshPricing();}
export async function saveAirport(form:FormData){const {userId}=await requireUser();const ident=canonicalAirportIdent(s(form,"ident"));if(!ident)return;await sql`INSERT INTO airports(user_id,ident,name,municipality,iso_country,latitude_deg,longitude_deg,active,closed,source,updated_at) VALUES(${userId},${ident},${s(form,"name")},${s(form,"municipality")},${s(form,"iso_country").toUpperCase()},${n(form,"latitude_deg")},${n(form,"longitude_deg")},1,0,'Manual',NOW()) ON CONFLICT(user_id,ident) DO UPDATE SET name=EXCLUDED.name,municipality=EXCLUDED.municipality,iso_country=EXCLUDED.iso_country,latitude_deg=EXCLUDED.latitude_deg,longitude_deg=EXCLUDED.longitude_deg,active=1,updated_at=NOW()`;revalidatePath("/database");}
export async function toggleAirport(form:FormData){const {userId}=await requireUser();await sql`UPDATE airports SET active=CASE WHEN active=1 THEN 0 ELSE 1 END,updated_at=NOW() WHERE id=${n(form,"id")} AND user_id=${userId}`;revalidatePath("/database");}
export async function applySafeProfileRepairs(){const {userId}=await requireUser();await sql`UPDATE flights f SET evidence=COALESCE(NULLIF(TRIM(f.evidence),''),a.evidence),aircraft_type=COALESCE(NULLIF(TRIM(f.aircraft_type),''),a.aircraft_type),aircraft_class=COALESCE(NULLIF(TRIM(f.aircraft_class),''),a.aircraft_class),role=COALESCE(NULLIF(TRIM(f.role),''),a.default_role),price_per_hour=COALESCE(f.price_per_hour,(SELECT r.price_per_hour FROM rates r WHERE r.user_id=f.user_id AND UPPER(TRIM(r.registration))=UPPER(TRIM(f.registration)) AND (r.valid_from IS NULL OR r.valid_from='' OR r.valid_from<=f.date) ORDER BY r.valid_from DESC NULLS LAST,r.id DESC LIMIT 1),a.default_price_per_hour) FROM aircraft a WHERE f.user_id=${userId} AND f.locked_at IS NULL AND a.user_id=f.user_id AND UPPER(TRIM(a.registration))=UPPER(TRIM(f.registration)) AND (NULLIF(TRIM(f.evidence),'') IS NULL OR NULLIF(TRIM(f.aircraft_type),'') IS NULL OR NULLIF(TRIM(f.aircraft_class),'') IS NULL OR NULLIF(TRIM(f.role),'') IS NULL OR f.price_per_hour IS NULL OR f.price_per_hour<=0)`;revalidatePath("/database");revalidatePath("/dashboard");revalidatePath("/flights");}

export async function canonicalizeFlightAirportCodes(form:FormData){
  const {userId}=await requireUser();if(s(form,"confirm")!=="canonicalize-airports")return;
  const rows=await sql`SELECT code FROM (
    SELECT DISTINCT UPPER(TRIM(departure)) code FROM flights WHERE user_id=${userId} AND UPPER(TRIM(COALESCE(departure,''))) ~ '^CZ-[0-9]{4}$'
    UNION SELECT DISTINCT UPPER(TRIM(arrival)) code FROM flights WHERE user_id=${userId} AND UPPER(TRIM(COALESCE(arrival,''))) ~ '^CZ-[0-9]{4}$'
  ) codes ORDER BY code` as Array<{code:string}>;
  const migrations=airportCodeMigrations(rows.map(row=>String(row.code)));if(!migrations.length)return;
  const queries=migrations.flatMap(item=>[
    sql`UPDATE flights SET departure=CASE WHEN UPPER(TRIM(COALESCE(departure,'')))=${item.from} THEN ${item.to} ELSE departure END,arrival=CASE WHEN UPPER(TRIM(COALESCE(arrival,'')))=${item.from} THEN ${item.to} ELSE arrival END WHERE user_id=${userId} AND locked_at IS NULL AND (UPPER(TRIM(COALESCE(departure,'')))=${item.from} OR UPPER(TRIM(COALESCE(arrival,'')))=${item.from})`,
    sql`UPDATE user_settings SET home_airport=${item.to} WHERE user_id=${userId} AND UPPER(TRIM(COALESCE(home_airport,'')))=${item.from}`,
  ]);
  await sql.transaction(queries);console.info("canonical-airport-codes",{userId,migrations:migrations.length});
  revalidatePath("/database");revalidatePath("/dashboard");revalidatePath("/flights");revalidatePath("/flights/new");revalidatePath("/map");revalidatePath("/print");revalidatePath("/export");
}
