import { requireUser } from "@/lib/auth/require-user";
import { getDatabaseDataV164 as getDatabaseData } from "@/lib/data/database-v164";
import { canonicalizeFlightAirportCodes,deleteRate,saveAircraft,saveAircraftWithResult,saveAirport,saveRate,toggleAircraft,toggleAirport } from "./actions";
import { DataQualityPanel } from "@/components/data-quality-panel";
import Link from "next/link";
import { searchAirportCatalog } from "@/lib/airport-catalog";
import { AircraftManager } from "@/components/aircraft-manager";
import { DetailsNavigation } from "@/components/details-navigation";
export const metadata={title:"Aircraft & airports | FlyTally"}; const t=(v:unknown)=>String(v??"");
type Params={airportSearch?:string;airportPage?:string};
const airportHref=(query:string,page:number)=>`/database?${new URLSearchParams({airportSearch:query,airportPage:String(page)})}`;
export default async function DatabasePage({searchParams}:{searchParams:Promise<Params>}){const {userId}=await requireUser(),params=await searchParams,airportSearch=String(params.airportSearch||"").trim(),catalog=searchAirportCatalog(airportSearch,Number(params.airportPage||1),50);const data=await getDatabaseData(userId);return <>
  <header className="page-header"><div><p className="eyebrow">LOGBOOK DATA</p><h1>Aircraft & airports</h1><p className="muted page-lead">Manage aircraft profiles, hourly rates and the airport catalogue used by your flights.</p></div></header>
  <DetailsNavigation label="Aircraft and airport sections" items={[{id:"aircraft",label:"Aircraft"},{id:"custom-airports",label:"Custom airports"},{id:"airport-catalogue",label:"Airport catalogue"},{id:"data-health",label:"Data health"}]}/>
  {data.issues.length?<DataQualityPanel issues={data.issues} airportStats={data.airportStats}/>:null}{data.codeMigrations.length?<details className="panel airport-code-migration"><summary><span><strong>Standardize airport codes</strong><small>Review older codes before updating historical flights.</small></span><b>{data.codeMigrations.length}</b></summary><div className="table-scroll"><table><thead><tr><th>Current</th><th>New</th><th>Airport</th><th>Departures</th><th>Arrivals</th></tr></thead><tbody>{data.codeMigrations.map(item=><tr key={item.from}><td><code>{item.from}</code></td><td><strong>{item.to}</strong></td><td>{item.name||"—"}</td><td>{item.departures}</td><td>{item.arrivals}</td></tr>)}</tbody></table></div><form action={canonicalizeFlightAirportCodes} className="migration-confirm"><input type="hidden" name="confirm" value="canonicalize-airports"/><button className="primary-button">Update historical flight codes</button></form></details>:null}<div className="data-tabs">
  <details className="panel" id="aircraft" open><summary><span><strong>Aircraft</strong><small>Profiles, defaults and hourly-rate history.</small></span><b>{data.aircraft.length}</b></summary><AircraftManager aircraft={data.aircraft} rates={data.rates} saveAction={saveAircraftWithResult} toggleAction={toggleAircraft} saveRateAction={saveRate} deleteRateAction={deleteRate}/></details>
  <details className="panel" id="custom-airports"><summary><span><strong>Custom airports</strong><small>Your own airfields and locations not found in the catalogue.</small></span><b>{data.airports.length}</b></summary><form action={saveAirport} className="inline-editor"><input name="ident" placeholder="ICAO / code" required/><input name="name" placeholder="Name"/><input name="municipality" placeholder="City"/><input name="iso_country" placeholder="Country"/><input name="latitude_deg" type="number" step="any" placeholder="Latitude"/><input name="longitude_deg" type="number" step="any" placeholder="Longitude"/><button className="primary-button">Add / update</button></form><div className="table-scroll"><table><thead><tr><th>Code</th><th>Name</th><th>City</th><th>Country</th><th>Coordinates</th><th>Status</th></tr></thead><tbody>{data.airports.map(a=><tr key={t(a.id)}><td><strong>{t(a.ident)}</strong></td><td>{t(a.name)}</td><td>{t(a.municipality)}</td><td>{t(a.iso_country)}</td><td>{t(a.latitude_deg)}, {t(a.longitude_deg)}</td><td><form action={toggleAirport}><input type="hidden" name="id" value={t(a.id)}/><button className={Number(a.active)?"status-on":"status-off"}>{Number(a.active)?"Active":"Inactive"}</button></form></td></tr>)}</tbody></table></div></details>
  <details className="panel airport-catalog-panel" id="airport-catalogue" open={Boolean(airportSearch)}><summary><span><strong>Airport catalogue</strong><small>Search the built-in worldwide reference catalogue.</small></span><b>{catalog.total.toLocaleString("en-GB")}</b></summary><form method="get" className="airport-search"><label>Search by code, name, city or country<input name="airportSearch" defaultValue={airportSearch} placeholder="LKPR, Letnany, Prague, CZ"/></label><button className="primary-button">Search</button>{airportSearch?<Link className="secondary-link" href="/database">Clear</Link>:null}</form><div className="table-scroll"><table><thead><tr><th>ID / ICAO</th><th>Name</th><th>City</th><th>Country / region</th><th>Type</th><th>Coordinates</th></tr></thead><tbody>{catalog.rows.map(airport=><tr key={airport.ident}><td><strong>{airport.ident}</strong></td><td>{airport.name||"—"}</td><td>{airport.municipality||"—"}</td><td>{airport.country||"—"}<small>{airport.region}</small></td><td>{airport.type.replaceAll("_"," ")}</td><td>{airport.lat.toFixed(6)}, {airport.lon.toFixed(6)}</td></tr>)}{!catalog.rows.length?<tr><td colSpan={6} className="empty-state">No airports found.</td></tr>)}</tbody></table></div><div className="pagination"><span>{catalog.total.toLocaleString("en-GB")} airports</span><Link aria-disabled={catalog.page<=1} href={airportHref(airportSearch,catalog.page-1)}>← Previous</Link><strong>{catalog.page} / {catalog.pages}</strong><Link aria-disabled={catalog.page>=catalog.pages} href={airportHref(airportSearch,catalog.page+1)}>Next →</Link></div></details>
  <details className="panel" id="data-health"><summary><span><strong>Data health summary</strong><small>Advanced counts for duplicates, rates, routes and GPS records.</small></span></summary><div className="metric-grid compact-metrics"><article className="metric"><span>Total flights</span><strong>{t(data.quality.total)}</strong></article><article className="metric"><span>Possible duplicates</span><strong>{t(data.quality.duplicate_flights)}</strong></article><article className="metric"><span>Flights without rate</span><strong>{t(data.quality.missing_price)}</strong></article><article className="metric"><span>Historical rates</span><strong>{t(data.quality.historical_rates)}</strong><small>{t(data.quality.future_rates)} future</small></article><article className="metric"><span>Invalid rates</span><strong>{Number(data.quality.invalid_rate_dates||0)+Number(data.quality.invalid_rates||0)}</strong></article><article className="metric"><span>Incomplete routes</span><strong>{t(data.quality.missing_route)}</strong></article><article className="metric"><span>Invalid BLOCK</span><strong>{t(data.quality.invalid_block_time)}</strong></article><article className="metric"><span>Empty GPS tracks</span><strong>{t(data.quality.empty_tracks)}</strong></article></div></details>
  </div></>}
