import { requireUser } from "@/lib/auth/require-user";
import { getDatabaseData } from "@/lib/data/database";
import { applySafeProfileRepairs,deleteRate,saveAircraft,saveAirport,saveRate,toggleAircraft,toggleAirport } from "./actions";
import { DataQualityPanel } from "@/components/data-quality-panel";
import Link from "next/link";
import { searchAirportCatalog } from "@/lib/airport-catalog";
import { AircraftManager } from "@/components/aircraft-manager";
export const metadata={title:"Databáze | Letový zápisník"}; const t=(v:unknown)=>String(v??"");
type Params={airportSearch?:string;airportPage?:string};
const airportHref=(query:string,page:number)=>`/database?${new URLSearchParams({airportSearch:query,airportPage:String(page)})}`;
export default async function DatabasePage({searchParams}:{searchParams:Promise<Params>}){const {userId}=await requireUser(),params=await searchParams,airportSearch=String(params.airportSearch||"").trim(),catalog=searchAirportCatalog(airportSearch,Number(params.airportPage||1),50);const data=await getDatabaseData(userId);return <>
  <header className="page-header"><div><p className="eyebrow">SPRÁVA DAT</p><h1>Databáze</h1><p className="muted">Letadla, historické sazby, letiště a kontrola kvality</p></div></header><DataQualityPanel issues={data.issues} airportStats={data.airportStats} repairAction={applySafeProfileRepairs}/><div className="data-tabs">
  <details className="panel" open><summary>Kontrola kvality dat</summary><div className="metric-grid compact-metrics"><article><span>Lety celkem</span><strong>{t(data.quality.total)}</strong></article><article><span>Možné duplicity</span><strong>{t(data.quality.duplicate_flights)}</strong></article><article><span>Bez ceny</span><strong>{t(data.quality.missing_price)}</strong></article><article><span>Neúplná trasa</span><strong>{t(data.quality.missing_route)}</strong></article><article><span>Neplatný BLOCK</span><strong>{t(data.quality.invalid_block_time)}</strong></article><article><span>Prázdné GPS</span><strong>{t(data.quality.empty_tracks)}</strong></article></div><p className="muted">Diagnostika nic sama nemění ani nemaže. Záznamy opravte v seznamu a detailu letů.</p></details>
  <details className="panel" open><summary>Letadla <b>{data.aircraft.length}</b></summary><p className="muted">Každé letadlo má vlastní profil, předvolby účtování a cenu. Historické změny ceny zapisujte níže do sekce Sazby.</p><AircraftManager aircraft={data.aircraft} saveAction={saveAircraft} toggleAction={toggleAircraft}/></details>
  <details className="panel"><summary>Sazby <b>{data.rates.length}</b></summary><form action={saveRate} className="inline-editor"><input name="registration" placeholder="Registrace" required/><input name="aircraft_type" placeholder="Typ"/><label>Platí od<input name="valid_from" type="date"/></label><input name="price_per_hour" type="number" step="0.01" placeholder="Cena/h"/><input name="dry_price_per_hour" type="number" step="0.01" placeholder="Dry cena/h"/><input name="source" placeholder="Zdroj"/><button className="primary-button">Uložit sazbu</button></form><div className="table-scroll"><table><thead><tr><th>Registrace</th><th>Platí od</th><th>Cena</th><th>Dry</th><th>Zdroj</th><th></th></tr></thead><tbody>{data.rates.map(r=><tr key={t(r.id)}><td>{t(r.registration)}</td><td>{t(r.valid_from)||"—"}</td><td>{Number(r.price_per_hour||0).toLocaleString('cs-CZ')} Kč</td><td>{Number(r.dry_price_per_hour||0).toLocaleString('cs-CZ')} Kč</td><td>{t(r.source)}</td><td><form action={deleteRate}><input type="hidden" name="id" value={t(r.id)}/><button className="icon-danger">Smazat</button></form></td></tr>)}</tbody></table></div></details>
  <details className="panel"><summary>Vlastní letiště <b>{data.airports.length}</b></summary><form action={saveAirport} className="inline-editor"><input name="ident" placeholder="ICAO / kód" required/><input name="name" placeholder="Název"/><input name="municipality" placeholder="Město"/><input name="iso_country" placeholder="Země"/><input name="latitude_deg" type="number" step="any" placeholder="Latitude"/><input name="longitude_deg" type="number" step="any" placeholder="Longitude"/><button className="primary-button">Přidat / aktualizovat</button></form><div className="table-scroll"><table><thead><tr><th>Kód</th><th>Název</th><th>Město</th><th>Země</th><th>Souřadnice</th><th>Stav</th></tr></thead><tbody>{data.airports.map(a=><tr key={t(a.id)}><td><strong>{t(a.ident)}</strong></td><td>{t(a.name)}</td><td>{t(a.municipality)}</td><td>{t(a.iso_country)}</td><td>{t(a.latitude_deg)}, {t(a.longitude_deg)}</td><td><form action={toggleAirport}><input type="hidden" name="id" value={t(a.id)}/><button className={Number(a.active)?"status-on":"status-off"}>{Number(a.active)?"Aktivní":"Neaktivní"}</button></form></td></tr>)}</tbody></table></div></details>
  <details className="panel airport-catalog-panel" open={Boolean(airportSearch)}><summary>Kompletní katalog letišť <b>{catalog.total.toLocaleString("cs-CZ")}</b></summary><form method="get" className="airport-search"><label>Hledat podle kódu, názvu, města nebo země<input name="airportSearch" defaultValue={airportSearch} placeholder="např. LKPR, Letňany, Praha, CZ"/></label><button className="primary-button">Vyhledat</button>{airportSearch?<Link className="secondary-link" href="/database">Vymazat</Link>:null}</form><p className="muted">Katalog OurAirports je pouze pro vyhledávání a automatickou GPS detekci. Zobrazuje se nejvýše 50 výsledků na stránku.</p><div className="table-scroll"><table><thead><tr><th>ID / ICAO</th><th>Název</th><th>Město</th><th>Země / region</th><th>Typ</th><th>Souřadnice</th></tr></thead><tbody>{catalog.rows.map(airport=><tr key={airport.ident}><td><strong>{airport.ident}</strong></td><td>{airport.name||"—"}</td><td>{airport.municipality||"—"}</td><td>{airport.country||"—"}<small>{airport.region}</small></td><td>{airport.type.replaceAll("_"," ")}</td><td>{airport.lat.toFixed(6)}, {airport.lon.toFixed(6)}</td></tr>)}{!catalog.rows.length?<tr><td colSpan={6} className="empty-state">V katalogu nebylo nic nalezeno.</td></tr>:null}</tbody></table></div><div className="pagination"><span>{catalog.total.toLocaleString("cs-CZ")} letišť</span><Link aria-disabled={catalog.page<=1} href={airportHref(airportSearch,catalog.page-1)}>← Předchozí</Link><strong>{catalog.page} / {catalog.pages}</strong><Link aria-disabled={catalog.page>=catalog.pages} href={airportHref(airportSearch,catalog.page+1)}>Další →</Link></div></details>
  </div></>}
