import { requireUser } from "@/lib/auth/require-user";
import { sql } from "@/lib/db";
import { credentialValidity } from "@/lib/credential-validity";
import { licenceProfileMap,parsePilotPreferences } from "@/lib/logbook-print";
import { addDocumentCredential,addPilotLicence,addQualification,archivePilotCredential,deleteExpiry,saveDocumentCredential,savePilotLicence,toggleExpiry } from "@/app/(protected)/profile/actions";

export const metadata={title:"Licences | FlyTally"};
const t=(v:unknown)=>String(v??"").trim();
const today=new Date().toISOString().slice(0,10);
const hm=(value:number)=>`${Math.floor(Math.max(0,value)/60)}:${String(Math.max(0,value)%60).padStart(2,"0")}`;
type DocMeta={kind?:string;number?:string;authority?:string;issuedDate?:string;detail?:string;validityMode?:string;note?:string};
function docMeta(value:unknown):DocMeta{try{const parsed=JSON.parse(t(value));return parsed&&typeof parsed==="object"&&!Array.isArray(parsed)?parsed:{note:t(value)}}catch{return{note:t(value)}}}
const badge=(status:string)=>status==="expired"?"status-off":status==="incomplete"?"record-status":"status-on";

export default async function CredentialsPage(){
  const{userId}=await requireUser();
  const[licences,qualifications,documents,settings,laplRows]=await Promise.all([
    sql`SELECT * FROM pilot_licences WHERE user_id=${userId} AND active=TRUE ORDER BY licence_type,id` as Promise<Array<Record<string,unknown>>>,
    sql`SELECT * FROM pilot_qualifications WHERE user_id=${userId} AND active=TRUE ORDER BY qualification_type,id` as Promise<Array<Record<string,unknown>>>,
    sql`SELECT id,label,expiry_date::text expiry_date,warning_days,note,active FROM user_expiries WHERE user_id=${userId} AND UPPER(TRIM(category))<>'LICENCE' AND active=1 ORDER BY expiry_date,label,id` as Promise<Array<Record<string,unknown>>>,
    sql`SELECT preferences_json FROM user_settings WHERE user_id=${userId} LIMIT 1` as Promise<Array<Record<string,unknown>>>,
    sql`SELECT
      COALESCE(SUM(CASE WHEN UPPER(COALESCE(f.aircraft_class,'')) IN ('SEP','TMG') AND UPPER(COALESCE(f.role,'')) IN ('PIC','DUAL','SOLO') THEN CASE WHEN f.off_block~'^([01][0-9]|2[0-3]):[0-5][0-9]$' AND f.on_block~'^([01][0-9]|2[0-3]):[0-5][0-9]$' THEN MOD((split_part(f.on_block,':',1)::int*60+split_part(f.on_block,':',2)::int)-(split_part(f.off_block,':',1)::int*60+split_part(f.off_block,':',2)::int)+1440,1440) ELSE 0 END ELSE 0 END),0)::int flight_minutes,
      COALESCE(SUM(CASE WHEN UPPER(COALESCE(f.aircraft_class,'')) IN ('SEP','TMG') AND UPPER(COALESCE(f.role,'')) IN ('PIC','DUAL','SOLO') THEN GREATEST(COALESCE(f.landings_day,0),0)+GREATEST(COALESCE(f.landings_night,0),0) ELSE 0 END),0)::int landings,
      COALESCE(SUM(CASE WHEN UPPER(COALESCE(f.aircraft_class,'')) IN ('SEP','TMG') AND UPPER(COALESCE(f.role,''))='DUAL' AND CONCAT_WS(' ',COALESCE(f.task,''),COALESCE(f.note,''))~*'(FCL[.]140[.]A|LAPL[[:space:]]+recency|recency[[:space:]]+training|refresher[[:space:]]+training)' AND EXISTS(SELECT 1 FROM flight_verifications v WHERE v.flight_id=f.id AND v.flight_user_id=f.user_id AND v.record_revision=COALESCE(f.record_revision,1) AND v.verification_role='INSTRUCTOR' AND v.status='signed') THEN CASE WHEN f.off_block~'^([01][0-9]|2[0-3]):[0-5][0-9]$' AND f.on_block~'^([01][0-9]|2[0-3]):[0-5][0-9]$' THEN MOD((split_part(f.on_block,':',1)::int*60+split_part(f.on_block,':',2)::int)-(split_part(f.off_block,':',1)::int*60+split_part(f.off_block,':',2)::int)+1440,1440) ELSE 0 END ELSE 0 END),0)::int refresher_minutes
      FROM flights f WHERE f.user_id=${userId} AND f.certified_at IS NOT NULL AND CASE WHEN f.date~'^\\d{4}-\\d{2}-\\d{2}$' THEN f.date::date ELSE NULL END>=CURRENT_DATE-INTERVAL '2 years'` as Promise<Array<Record<string,unknown>>>,
  ]);
  const preferences=parsePilotPreferences(settings[0]?.preferences_json),profiles=licenceProfileMap(preferences),lapl=laplRows[0]??{},laplMinutes=Number(lapl.flight_minutes)||0,laplLandings=Number(lapl.landings)||0,laplRefresher=Number(lapl.refresher_minutes)||0,laplMet=laplMinutes>=720&&laplLandings>=12&&laplRefresher>=60,hasLapl=licences.some(item=>t(item.licence_type).toUpperCase()==="LAPL(A)");
  return <>
    <header className="page-header"><div><p className="eyebrow">PILOT LICENCES</p><h1>Licences</h1><p className="muted">Licences, qualifications, signing identity, medical and language documents in one place.</p></div></header>

    {hasLapl?<section className="panel expiry-panel"><div className="section-heading"><div><p className="eyebrow">LAPL(A) RECENCY</p><h2>Rolling 2-year privileges</h2><p className="muted">FlyTally evaluates certified SEP/TMG entries in the previous 2 years. A proficiency check is an alternative route and is not inferred automatically here.</p></div><span className={laplMet?"status-on":"record-status"}>{laplMet?"Requirements met":"Review recency"}</span></div><div className="credential-list"><div className="credential-card"><div className="credential-summary"><div className="credential-main"><span>FCL.140.A</span><strong>{hm(laplMinutes)} / 12:00 flight time</strong><small>PIC, DUAL or supervised solo on SEP/TMG</small></div><div className="credential-validity"><b className={laplLandings>=12?"status-on":"record-status"}>{laplLandings} / 12 landings</b><small>{hm(laplRefresher)} / 1:00 verified refresher</small></div></div></div></div><p className="muted">For FlyTally to count the refresher hour, use a DUAL flight with a task/remark such as “FCL.140.A refresher training” and have the instructor sign that certified revision.</p></section>:null}

    <section className="panel expiry-panel"><div className="section-heading"><div><p className="eyebrow">LICENCES</p><h2>Licences & signing identity</h2><p className="muted">Each licence carries its own logbook address and qualifications. Part-FCL LAPL(A) is treated as unlimited; its SEP/TMG privileges are monitored through rolling recency instead of an artificial expiry date.</p></div><span>{licences.length}</span></div>
      <div className="credential-list">{licences.map(item=>{const id=Number(item.id),profile=profiles[`pilot-${id}`]??{},scope=t(profile.scope)||(/ULL/.test(t(item.licence_type).toUpperCase())?"ULL":"EASA"),address=t(profile.address)||(scope==="ULL"?t(preferences.ull_address):t(preferences.easa_address)||t(preferences.pilot_address)),isLapl=t(item.licence_type).toUpperCase()==="LAPL(A)",validity=isLapl?{status:"valid",label:"Unlimited"}:credentialValidity({mode:item.validity_mode,validUntil:item.valid_until,recencyUntil:item.recency_until},today),quals=qualifications.filter(q=>Number(q.licence_id)===id);return <details className="credential-card" key={id}>
        <summary className="credential-summary"><div className="credential-main"><span>{scope} · {t(item.country)||"Country not set"}</span><strong>{t(item.licence_type)} · {t(item.licence_number)}</strong><small>{t(item.authority)||"Issuing authority not set"} · {quals.length} qualification{quals.length===1?"":"s"}</small></div><div className="credential-validity"><b className={badge(validity.status)}>{validity.label}</b><small>{address?"Logbook identity complete":"Address missing"}</small></div><span className="credential-chevron" aria-hidden="true">⌄</span></summary>
        <div className="credential-editor"><form action={savePilotLicence} className="form-grid settings-grid"><input type="hidden" name="id" value={id}/><label>Licence<input name="licence_type" list="licence-types" defaultValue={t(item.licence_type)} required/></label><label>Licence number<input name="licence_number" defaultValue={t(item.licence_number)} required/></label><label>Issuing authority<input name="authority" defaultValue={t(item.authority)}/></label><label>Country<input name="country" maxLength={3} defaultValue={t(item.country)}/></label><label>Logbook<select name="logbook_scope" defaultValue={scope}><option>EASA</option><option>ULL</option><option value="OTHER">Other / no print header</option></select></label>{isLapl?<><input type="hidden" name="validity_mode" value="unlimited"/><div><strong>Licence validity</strong><small>Unlimited · LAPL(A) privileges depend on rolling recency.</small></div></>:<><label>Validity<select name="validity_mode" defaultValue={t(item.validity_mode)||"unlimited"}><option value="unlimited">Unlimited</option><option value="date">Expiry date</option><option value="recency">Recency</option></select></label><label>Valid until<input type="date" name="valid_until" defaultValue={t(item.valid_until).slice(0,10)}/></label><label>Recency until<input type="date" name="recency_until" defaultValue={t(item.recency_until).slice(0,10)}/></label></>}<label className="wide">Holder address<textarea name="holder_address" rows={2} defaultValue={address} placeholder="Address printed in this logbook"/></label><div className="form-actions wide"><button className="primary-button">Save licence</button></div></form>
          <div className="qualification-list">{quals.map(q=>{const laplPrivilege=isLapl&&/^(SEP|TMG)/.test(t(q.qualification_type).toUpperCase()),state=laplPrivilege?{status:laplMet?"valid":"incomplete",label:"Recency based"}:credentialValidity({mode:q.validity_mode,validUntil:q.valid_until,recencyUntil:q.recency_until},today);return <div key={t(q.id)}><span><strong>{t(q.qualification_type)}</strong><small>{t(q.certificate_reference)||"No certificate reference"} · {state.label}</small></span><form action={archivePilotCredential}><input type="hidden" name="id" value={t(q.id)}/><input type="hidden" name="kind" value="qualification"/><button className="secondary-button">Archive</button></form></div>})}</div>
          <details className="credential-create"><summary>Add qualification</summary><form action={addQualification} className="form-grid settings-grid"><input type="hidden" name="licence_id" value={id}/><label>Qualification<input name="qualification_type" list="qualification-types" placeholder="FI(A), SEP(land)…" required/></label><label>Certificate reference<input name="certificate_reference"/></label>{isLapl?<><input type="hidden" name="validity_mode" value="unlimited"/><div><strong>LAPL class privilege</strong><small>SEP/TMG is monitored through rolling recency rather than an expiry date.</small></div></>:<><label>Validity<select name="validity_mode" defaultValue="date"><option value="unlimited">Unlimited</option><option value="date">Expiry date</option><option value="recency">Recency</option></select></label><label>Valid until<input type="date" name="valid_until"/></label><label>Recency until<input type="date" name="recency_until"/></label></>}<div className="form-actions wide"><button className="primary-button">Add qualification</button></div></form></details>
          <form action={archivePilotCredential} className="credential-record-actions"><input type="hidden" name="id" value={id}/><input type="hidden" name="kind" value="licence"/><button className="secondary-link">Archive licence</button></form>
        </div></details>})}{!licences.length?<p className="empty-state">No licences yet. Add your first licence below.</p>:null}</div>
      <details className="credential-create"><summary>Add licence</summary><form action={addPilotLicence} className="form-grid settings-grid"><label>Licence<input name="licence_type" list="licence-types" placeholder="PPL(A)" required/></label><label>Licence number<input name="licence_number" required/></label><label>Issuing authority<input name="authority" placeholder="CAA / issuing authority"/></label><label>Country<input name="country" maxLength={3} placeholder="CZE"/></label><label>Logbook<select name="logbook_scope" defaultValue="EASA"><option>EASA</option><option>ULL</option><option value="OTHER">Other / no print header</option></select></label><label>Validity<select name="validity_mode" defaultValue="unlimited"><option value="unlimited">Unlimited</option><option value="date">Expiry date</option><option value="recency">Recency</option></select><small>Part-FCL licences are normally unlimited. Use expiry only where the document itself has one.</small></label><label>Valid until<input type="date" name="valid_until"/></label><label>Recency until<input type="date" name="recency_until"/></label><label className="wide">Holder address<textarea name="holder_address" rows={2} placeholder="Address printed in the matching logbook"/></label><div className="form-actions wide"><button className="primary-button">Add licence</button></div></form></details>
      <datalist id="licence-types"><option value="LAPL(A)"/><option value="PPL(A)"/><option value="CPL(A)"/><option value="ATPL(A)"/><option value="ULL"/></datalist><datalist id="qualification-types"><option value="SEP(land)"/><option value="TMG"/><option value="Night rating"/><option value="IR(A)"/><option value="FI(A)"/><option value="CRI(A)"/><option value="IRI(A)"/><option value="FE(A)"/></datalist>
    </section>

    <section className="panel expiry-panel"><div className="section-heading"><div><p className="eyebrow">DOCUMENTS</p><h2>Medical, language & other documents</h2><p className="muted">Choose a common credential or enter your own. Numbers, authority and validity remain attached to the record.</p></div><span>{documents.length}</span></div>
      <div className="credential-list">{documents.map(item=>{const meta=docMeta(item.note),mode=meta.validityMode==="unlimited"||t(item.expiry_date)==="9999-12-31"?"unlimited":"date",validity=credentialValidity({mode,validUntil:item.expiry_date},today);return <details className="credential-card" key={t(item.id)}><summary className="credential-summary"><div className="credential-main"><span>Document</span><strong>{t(item.label)}</strong><small>{meta.number||"No number"}{meta.detail?` · ${meta.detail}`:""}</small></div><div className="credential-validity"><b className={badge(validity.status)}>{validity.label}</b><small>{meta.authority||"Authority not set"}</small></div><span className="credential-chevron" aria-hidden="true">⌄</span></summary><div className="credential-editor"><form action={saveDocumentCredential} className="form-grid settings-grid"><input type="hidden" name="id" value={t(item.id)}/><label>Document<input name="label" defaultValue={t(item.label)} required/></label><label>Number<input name="document_number" defaultValue={meta.number||""}/></label><label>Issuing authority<input name="authority" defaultValue={meta.authority||""}/></label><label>Issued<input type="date" name="issued_date" defaultValue={meta.issuedDate||""}/></label><label>Validity<select name="validity_mode" defaultValue={mode}><option value="unlimited">Unlimited</option><option value="date">Expiry date</option></select></label><label>Valid until<input type="date" name="valid_until" defaultValue={mode==="unlimited"?"":t(item.expiry_date).slice(0,10)}/></label><label>Warning days<input type="number" min="1" max="365" name="warning_days" defaultValue={Number(item.warning_days)||30}/></label><label>Details<input name="detail" defaultValue={meta.detail||""}/></label><label className="wide">Notes<textarea name="document_note" rows={2} defaultValue={meta.note||""}/></label><div className="form-actions wide"><button className="primary-button">Save document</button></div></form><div className="credential-record-actions"><form action={toggleExpiry}><input type="hidden" name="id" value={t(item.id)}/><button className="secondary-link">Archive</button></form><form action={deleteExpiry}><input type="hidden" name="id" value={t(item.id)}/><button className="secondary-link">Delete</button></form></div></div></details>})}{!documents.length?<p className="empty-state">No medical, language or other documents yet.</p>:null}</div>
      <details className="credential-create"><summary>Add medical, language or other document</summary><form action={addDocumentCredential} className="form-grid settings-grid"><label>Document<select name="document_type" defaultValue="Medical Class 2"><option>Medical Class 1</option><option>Medical Class 2</option><option>LAPL Medical</option><option>ICAO English Language Proficiency</option><option>Radiotelephony Licence</option><option value="">Custom document</option></select></label><label>Custom name<input name="custom_label" placeholder="Only for a custom document"/></label><label>Number<input name="document_number"/></label><label>Issuing authority<input name="authority"/></label><label>Issued<input type="date" name="issued_date"/></label><label>Validity<select name="validity_mode" defaultValue="date"><option value="date">Expiry date</option><option value="unlimited">Unlimited</option></select></label><label>Valid until<input type="date" name="valid_until"/></label><label>Details<input name="detail" placeholder="e.g. ICAO Level 6"/></label><label>Warning days<input type="number" name="warning_days" min="1" max="365" defaultValue="30"/></label><label className="wide">Notes<textarea name="document_note" rows={2}/></label><div className="form-actions wide"><button className="primary-button">Add document</button></div></form></details>
    </section>
  </>;
}
