import { requireUser } from "@/lib/auth/require-user";
import { sql } from "@/lib/db";
import { credentialValidity } from "@/lib/credential-validity";
import { licenceProfileMap,parsePilotPreferences } from "@/lib/logbook-print";
import { addDocumentCredential,addPilotLicence,addQualification,archivePilotCredential,deleteExpiry,saveDocumentCredential,savePilotLicence,toggleExpiry } from "@/app/(protected)/profile/actions";

export const metadata={title:"Credentials | FlyTally"};
const t=(v:unknown)=>String(v??"").trim();
const today=new Date().toISOString().slice(0,10);
type DocMeta={kind?:string;number?:string;authority?:string;issuedDate?:string;detail?:string;validityMode?:string;note?:string};
function docMeta(value:unknown):DocMeta{try{const parsed=JSON.parse(t(value));return parsed&&typeof parsed==="object"&&!Array.isArray(parsed)?parsed:{note:t(value)}}catch{return{note:t(value)}}}
const badge=(status:string)=>status==="expired"?"status-off":status==="incomplete"?"record-status":"status-on";

export default async function CredentialsPage(){
  const{userId}=await requireUser();
  const[licences,qualifications,documents,settings]=await Promise.all([
    sql`SELECT * FROM pilot_licences WHERE user_id=${userId} AND active=TRUE ORDER BY licence_type,id` as Promise<Array<Record<string,unknown>>>,
    sql`SELECT * FROM pilot_qualifications WHERE user_id=${userId} AND active=TRUE ORDER BY qualification_type,id` as Promise<Array<Record<string,unknown>>>,
    sql`SELECT id,label,expiry_date::text expiry_date,warning_days,note,active FROM user_expiries WHERE user_id=${userId} AND UPPER(TRIM(category))<>'LICENCE' AND active=1 ORDER BY expiry_date,label,id` as Promise<Array<Record<string,unknown>>>,
    sql`SELECT preferences_json FROM user_settings WHERE user_id=${userId} LIMIT 1` as Promise<Array<Record<string,unknown>>>,
  ]);
  const preferences=parsePilotPreferences(settings[0]?.preferences_json),profiles=licenceProfileMap(preferences);
  return <>
    <header className="page-header"><div><p className="eyebrow">PILOT CREDENTIALS</p><h1>Credentials</h1><p className="muted">Licences, qualifications and documents in one place. Licence identity is also used for your printed logbook and verified approvals.</p></div></header>

    <section className="panel expiry-panel"><div className="section-heading"><div><p className="eyebrow">LICENCES</p><h2>Licences & signing identity</h2><p className="muted">Each licence carries its own logbook address and qualifications. Unlimited licences do not require an artificial expiry date.</p></div><span>{licences.length}</span></div>
      <div className="credential-list">{licences.map(item=>{const id=Number(item.id),profile=profiles[`pilot-${id}`]??{},scope=t(profile.scope)||(/ULL/.test(t(item.licence_type).toUpperCase())?"ULL":"EASA"),address=t(profile.address)||(scope==="ULL"?t(preferences.ull_address):t(preferences.easa_address)||t(preferences.pilot_address)),validity=credentialValidity({mode:item.validity_mode,validUntil:item.valid_until,recencyUntil:item.recency_until},today),quals=qualifications.filter(q=>Number(q.licence_id)===id);return <details className="credential-card" key={id}>
        <summary className="credential-summary"><div className="credential-main"><span>{scope} · {t(item.country)||"Country not set"}</span><strong>{t(item.licence_type)} · {t(item.licence_number)}</strong><small>{t(item.authority)||"Issuing authority not set"} · {quals.length} qualification{quals.length===1?"":"s"}</small></div><div className="credential-validity"><b className={badge(validity.status)}>{validity.label}</b><small>{address?"Logbook identity complete":"Address missing"}</small></div><span className="credential-chevron" aria-hidden="true">⌄</span></summary>
        <div className="credential-editor"><form action={savePilotLicence} className="form-grid settings-grid"><input type="hidden" name="id" value={id}/><label>Licence<input name="licence_type" list="licence-types" defaultValue={t(item.licence_type)} required/></label><label>Licence number<input name="licence_number" defaultValue={t(item.licence_number)} required/></label><label>Issuing authority<input name="authority" defaultValue={t(item.authority)}/></label><label>Country<input name="country" maxLength={3} defaultValue={t(item.country)}/></label><label>Logbook<select name="logbook_scope" defaultValue={scope}><option>EASA</option><option>ULL</option><option value="OTHER">Other / no print header</option></select></label><label>Validity<select name="validity_mode" defaultValue={t(item.validity_mode)||"unlimited"}><option value="unlimited">Unlimited</option><option value="date">Expiry date</option><option value="recency">Recency</option></select></label><label>Valid until<input type="date" name="valid_until" defaultValue={t(item.valid_until).slice(0,10)}/></label><label>Recency until<input type="date" name="recency_until" defaultValue={t(item.recency_until).slice(0,10)}/></label><label className="wide">Holder address<textarea name="holder_address" rows={2} defaultValue={address} placeholder="Address printed in this logbook"/></label><div className="form-actions wide"><button className="primary-button">Save licence</button></div></form>
          <div className="qualification-list">{quals.map(q=>{const state=credentialValidity({mode:q.validity_mode,validUntil:q.valid_until,recencyUntil:q.recency_until},today);return <div key={t(q.id)}><span><strong>{t(q.qualification_type)}</strong><small>{t(q.certificate_reference)||"No certificate reference"} · {state.label}</small></span><form action={archivePilotCredential}><input type="hidden" name="id" value={t(q.id)}/><input type="hidden" name="kind" value="qualification"/><button className="secondary-button">Archive</button></form></div>})}</div>
          <details className="credential-create"><summary>Add qualification</summary><form action={addQualification} className="form-grid settings-grid"><input type="hidden" name="licence_id" value={id}/><label>Qualification<input name="qualification_type" list="qualification-types" placeholder="FI(A), SEP(land)…" required/></label><label>Certificate reference<input name="certificate_reference"/></label><label>Validity<select name="validity_mode" defaultValue="date"><option value="unlimited">Unlimited</option><option value="date">Expiry date</option><option value="recency">Recency</option></select></label><label>Valid until<input type="date" name="valid_until"/></label><label>Recency until<input type="date" name="recency_until"/></label><div className="form-actions wide"><button className="primary-button">Add qualification</button></div></form></details>
          <form action={archivePilotCredential} className="credential-record-actions"><input type="hidden" name="id" value={id}/><input type="hidden" name="kind" value="licence"/><button className="secondary-link">Archive licence</button></form>
        </div></details>})}{!licences.length?<p className="empty-state">No licences yet. Add your first licence below.</p>:null}</div>
      <details className="credential-create"><summary>Add licence</summary><form action={addPilotLicence} className="form-grid settings-grid"><label>Licence<input name="licence_type" list="licence-types" placeholder="PPL(A)" required/></label><label>Licence number<input name="licence_number" required/></label><label>Issuing authority<input name="authority" placeholder="CAA / issuing authority"/></label><label>Country<input name="country" maxLength={3} placeholder="CZE"/></label><label>Logbook<select name="logbook_scope" defaultValue="EASA"><option>EASA</option><option>ULL</option><option value="OTHER">Other / no print header</option></select></label><label>Validity<select name="validity_mode" defaultValue="unlimited"><option value="unlimited">Unlimited</option><option value="date">Expiry date</option><option value="recency">Recency</option></select></label><label>Valid until<input type="date" name="valid_until"/></label><label>Recency until<input type="date" name="recency_until"/></label><label className="wide">Holder address<textarea name="holder_address" rows={2} placeholder="Address printed in the matching logbook"/></label><div className="form-actions wide"><button className="primary-button">Add licence</button></div></form></details>
      <datalist id="licence-types"><option value="LAPL(A)"/><option value="PPL(A)"/><option value="CPL(A)"/><option value="ATPL(A)"/><option value="ULL"/></datalist><datalist id="qualification-types"><option value="SEP(land)"/><option value="TMG"/><option value="Night rating"/><option value="IR(A)"/><option value="FI(A)"/><option value="CRI(A)"/><option value="IRI(A)"/><option value="FE(A)"/></datalist>
    </section>

    <section className="panel expiry-panel"><div className="section-heading"><div><p className="eyebrow">DOCUMENTS</p><h2>Medical, language & other documents</h2><p className="muted">Choose a common credential or enter your own. Numbers, authority and validity remain attached to the record.</p></div><span>{documents.length}</span></div>
      <div className="credential-list">{documents.map(item=>{const meta=docMeta(item.note),mode=meta.validityMode==="unlimited"||t(item.expiry_date)==="9999-12-31"?"unlimited":"date",validity=credentialValidity({mode,validUntil:item.expiry_date},today);return <details className="credential-card" key={t(item.id)}><summary className="credential-summary"><div className="credential-main"><span>Document</span><strong>{t(item.label)}</strong><small>{meta.number||"No number"}{meta.detail?` · ${meta.detail}`:""}</small></div><div className="credential-validity"><b className={badge(validity.status)}>{validity.label}</b><small>{meta.authority||"Authority not set"}</small></div><span className="credential-chevron" aria-hidden="true">⌄</span></summary><div className="credential-editor"><form action={saveDocumentCredential} className="form-grid settings-grid"><input type="hidden" name="id" value={t(item.id)}/><label>Document<input name="label" defaultValue={t(item.label)} required/></label><label>Number<input name="document_number" defaultValue={meta.number||""}/></label><label>Issuing authority<input name="authority" defaultValue={meta.authority||""}/></label><label>Issued<input type="date" name="issued_date" defaultValue={meta.issuedDate||""}/></label><label>Validity<select name="validity_mode" defaultValue={mode}><option value="unlimited">Unlimited</option><option value="date">Expiry date</option></select></label><label>Valid until<input type="date" name="valid_until" defaultValue={mode==="unlimited"?"":t(item.expiry_date).slice(0,10)}/></label><label>Warning days<input type="number" name="warning_days" min="1" max="365" defaultValue={t(item.warning_days)||"30"}/></label><label>Level / detail<input name="detail" defaultValue={meta.detail||""} placeholder="e.g. ICAO Level 6"/></label><label className="wide">Notes<input name="document_note" defaultValue={meta.note||""}/></label><div className="form-actions wide"><button className="primary-button">Save document</button></div></form><div className="credential-record-actions"><form action={toggleExpiry}><input type="hidden" name="id" value={t(item.id)}/><button className="secondary-link">Archive</button></form><details className="confirm-action"><summary>Delete…</summary><div><p>Permanently remove this document record.</p><form action={deleteExpiry}><input type="hidden" name="id" value={t(item.id)}/><button className="icon-danger">Delete permanently</button></form></div></details></div></div></details>})}{!documents.length?<p className="empty-state">No additional credentials or documents yet.</p>:null}</div>
      <details className="credential-create"><summary>Add document</summary><form action={addDocumentCredential} className="form-grid settings-grid"><label>Type<select name="document_type" defaultValue="Medical Class 2"><option>Medical Class 1</option><option>Medical Class 2</option><option>LAPL Medical</option><option>ICAO English Language Proficiency</option><option>Radiotelephony Licence</option><option>Insurance</option><option>Other</option></select></label><label>Custom name<input name="custom_label" placeholder="Optional – overrides type"/></label><label>Number<input name="document_number"/></label><label>Issuing authority<input name="authority"/></label><label>Issued<input type="date" name="issued_date"/></label><label>Validity<select name="validity_mode" defaultValue="date"><option value="unlimited">Unlimited</option><option value="date">Expiry date</option></select></label><label>Valid until<input type="date" name="valid_until"/></label><label>Warning days<input type="number" name="warning_days" min="1" max="365" defaultValue="30"/></label><label>Level / detail<input name="detail" placeholder="e.g. ICAO Level 4 / 5 / 6"/></label><label className="wide">Notes<input name="document_note"/></label><div className="form-actions wide"><button className="primary-button">Add document</button></div></form></details>
    </section>
  </>;
}
