import Link from "next/link";
import { requireUser } from "@/lib/auth/require-user";
import { getIntelligentLogbookAttention } from "@/lib/intelligent-logbook-service";

export const metadata={title:"Needs attention | FlyTally"};

export default async function NeedsAttentionPage(){
  const {userId}=await requireUser(),items=await getIntelligentLogbookAttention(userId),issueCount=items.reduce((sum,item)=>sum+item.insights.length,0),attentionCount=items.reduce((sum,item)=>sum+item.insights.filter(insight=>insight.tone==="attention").length,0),warningCount=items.reduce((sum,item)=>sum+item.insights.filter(insight=>insight.tone==="warning").length,0);
  return <>
    <header className="page-header"><div><p className="eyebrow">INTELLIGENT LOGBOOK</p><h1>Needs attention</h1><p className="muted">A read-only review of your recent stored flights. FlyTally explains what looks inconsistent, but never changes certified or regulatory data automatically.</p></div><div className="form-actions"><Link className="secondary-button" href="/flights">Back to flights</Link><Link className="primary-link" href="/flights/new">＋ Add flight</Link></div></header>
    <section className="flight-summary"><div><span>Flights flagged</span><strong>{items.length}</strong><small>Latest 500 records reviewed</small></div><div><span>Review</span><strong>{attentionCount}</strong><small>Explicit contradictions / incomplete data</small></div><div><span>Checks</span><strong>{warningCount}</strong><small>History or plausibility warnings</small></div><div><span>Total findings</span><strong>{issueCount}</strong></div></section>
    {items.length?<section className="panel"><div className="section-heading"><div><p className="eyebrow">EXISTING LOGBOOK</p><h2>Review queue</h2></div><span>{items.length}</span></div><div className="credential-list">{items.map(item=><article className="credential-card" style={{padding:"14px 16px"}} key={item.flightId}><div className="credential-main"><span>{item.date} · {item.registration} · {item.route}</span><strong>{item.insights.length} {item.insights.length===1?"finding":"findings"}</strong>{item.insights.map(insight=><div key={insight.code} style={{marginTop:"10px"}}><small><b>{insight.tone==="attention"?"REVIEW":insight.tone==="warning"?"CHECK":"INFO"} · {insight.title}</b></small><small>{insight.message}</small>{insight.evidence?.length?<small><b>Based on:</b> {insight.evidence.map(source=>`${source.label}: ${source.value}`).join(" · ")}</small>:null}</div>)}</div><div className="form-actions"><Link className="secondary-button" href={`/flights/${item.flightId}`}>View flight</Link></div></article>)}</div></section>:<section className="panel"><div className="flight-empty-state"><span aria-hidden="true">✓</span><h2>No current findings</h2><p>The latest 500 stored flights did not trigger any deterministic review or plausibility warnings.</p><Link className="secondary-button" href="/flights">Back to flights</Link></div></section>}
    <p className="muted">This view is advisory. History-based patterns are not regulatory classifications, and an unusual value can still be correct. CAT, NCC, SPO, PICUS and similar context remains pilot-entered evidence only.</p>
  </>;
}
