import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { spawnSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { after,before,test } from "node:test";
const enabled=process.env.FLYTALLY_POSTGRES_INTEGRATION==="1",databaseUrl=process.env.DATABASE_URL??"",root=path.resolve(import.meta.dirname,"../.."),schema=`ft_exp_${randomUUID().replaceAll("-","")}`,quoted=`"${schema}"`;
function raw(statement:string){return spawnSync("psql",[databaseUrl,"-X","-v","ON_ERROR_STOP=1","-qAt","-c",statement],{encoding:"utf8",env:{...process.env,PGCONNECT_TIMEOUT:"5"}})}
function run(statement:string){const result=raw(`SET search_path TO ${quoted};\n${statement}`);if(result.status!==0)throw new Error(result.stderr||result.stdout);return String(result.stdout??"").trim()}
before(()=>{if(!enabled)return;assert.ok(databaseUrl);let result=raw(`CREATE SCHEMA ${quoted};SET search_path TO ${quoted};CREATE TABLE users(id BIGINT PRIMARY KEY);CREATE TABLE flights(id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id));CREATE TABLE deleted_flights(id BIGSERIAL PRIMARY KEY);INSERT INTO users(id) VALUES(1),(2);INSERT INTO flights(id,user_id) VALUES(10,1),(20,2);`);if(result.status!==0)throw new Error(result.stderr||result.stdout);const source=fs.readFileSync(path.join(root,"lib/v159-schema.ts"),"utf8"),blocks=[...source.matchAll(/sql`([\s\S]*?)`/g)].map(match=>match[1]).filter(value=>value.startsWith("CREATE UNIQUE INDEX IF NOT EXISTS flights_id_user")||value.startsWith("CREATE TABLE IF NOT EXISTS flight_expenses")||value.startsWith("CREATE INDEX IF NOT EXISTS idx_flight_expenses")||value.startsWith("ALTER TABLE deleted_flights"));assert.equal(blocks.length,4);for(const block of blocks)run(block)});
after(()=>{if(enabled)raw(`DROP SCHEMA IF EXISTS ${quoted} CASCADE`)});
test("v1.59 database enforces expense ownership and cascade",{skip:!enabled},()=>{run(`INSERT INTO flight_expenses(user_id,flight_id,category,label,amount_minor,currency) VALUES(1,10,'LANDING','',1250,'EUR')`);assert.equal(run(`SELECT amount_minor||'|'||currency FROM flight_expenses WHERE user_id=1`),"1250|EUR");const cross=raw(`SET search_path TO ${quoted};INSERT INTO flight_expenses(user_id,flight_id,category,label,amount_minor,currency) VALUES(2,10,'HANDLING','',1000,'EUR')`);assert.notEqual(cross.status,0);run(`DELETE FROM flights WHERE id=10`);assert.equal(run(`SELECT COUNT(*) FROM flight_expenses`),"0")});
test("v1.59 database rejects invalid amount/currency and prepares trash payload",{skip:!enabled},()=>{let result=raw(`SET search_path TO ${quoted};INSERT INTO flight_expenses(user_id,flight_id,category,label,amount_minor,currency) VALUES(2,20,'PARKING','',0,'EUR')`);assert.notEqual(result.status,0);result=raw(`SET search_path TO ${quoted};INSERT INTO flight_expenses(user_id,flight_id,category,label,amount_minor,currency) VALUES(2,20,'PARKING','',100,'EU')`);assert.notEqual(result.status,0);assert.equal(run(`SELECT expenses_data::text FROM deleted_flights WHERE false`),"")});
