import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { spawnSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { after,before,test } from "node:test";
import { flightCertificationHash,verifyFlightCertification } from "../../lib/certification-integrity.ts";
import { verificationCryptographicStatus } from "../../lib/authority-verification.ts";
import { signVerificationPayload } from "../../lib/verification-signature.ts";
import { validateBackupCertificationHistory } from "../../lib/backup-certification.ts";
import { parsePortableBackup,portableBackupDigest,type PortableBackup } from "../../lib/portable-backup.ts";

const enabled=process.env.FLYTALLY_POSTGRES_INTEGRATION==="1",databaseUrl=process.env.DATABASE_URL??"",root=path.resolve(import.meta.dirname,"../.."),schema=`ft_security_${randomUUID().replaceAll("-","")}`,quotedSchema=`"${schema}"`,read=(file:string)=>fs.readFileSync(path.join(root,file),"utf8");
function rawPsql(statement:string){const result=spawnSync("psql",[databaseUrl,"-X","-v","ON_ERROR_STOP=1","-qAt","-c",statement],{encoding:"utf8",env:{...process.env,PGCONNECT_TIMEOUT:"5"}});if(result.error)throw result.error;return result}
function run(statement:string){const result=rawPsql(`SET search_path TO ${quotedSchema};\n${statement}`);if(result.status!==0)throw new Error(`PostgreSQL security/restore command failed:\n${result.stderr||result.stdout}`);return String(result.stdout??"").trim()}
function rows(statement:string){const clean=statement.trim().replace(/;\s*$/,"");return JSON.parse(run(`WITH q AS (${clean}) SELECT COALESCE(json_agg(row_to_json(q)),'[]'::json)::text FROM q`)||"[]") as Array<Record<string,unknown>>}
function sqlBlock(source:string,needle:string,which:"first"|"last"="first"){const blocks=[...source.matchAll(/sql`([\s\S]*?)`/g)].map(match=>match[1]).filter(value=>value.includes(needle)),block=which==="last"?blocks.at(-1):blocks[0];assert.ok(block,`Production SQL block not found: ${needle}`);return block}
function literal(value:unknown){if(value===null)return"NULL";if(typeof value==="number")return String(value);if(typeof value==="boolean")return value?"TRUE":"FALSE";const raw=typeof value==="string"?value:(JSON.stringify(value)??"");return`'${raw.replaceAll("'","''")}'`}
function render(block:string,values:Record<string,unknown>){const rendered=block.replace(/\$\{([^}]+)\}/g,(_all,expression)=>{const key=String(expression).trim();assert.ok(Object.prototype.hasOwnProperty.call(values,key),`No SQL test value for ${key}`);return literal(values[key])});assert.doesNotMatch(rendered,/\$\{/);return rendered}

const flightColumns=`id BIGINT PRIMARY KEY,user_id BIGINT NOT NULL,date DATE,evidence TEXT NOT NULL DEFAULT '',registration TEXT NOT NULL DEFAULT '',aircraft_make TEXT NOT NULL DEFAULT '',aircraft_model TEXT NOT NULL DEFAULT '',aircraft_variant TEXT NOT NULL DEFAULT '',aircraft_type TEXT NOT NULL DEFAULT '',aircraft_class TEXT NOT NULL DEFAULT '',departure TEXT NOT NULL DEFAULT '',arrival TEXT NOT NULL DEFAULT '',off_block TEXT NOT NULL DEFAULT '',takeoff TEXT NOT NULL DEFAULT '',landing TEXT NOT NULL DEFAULT '',on_block TEXT NOT NULL DEFAULT '',starts INTEGER NOT NULL DEFAULT 0,operation_type TEXT NOT NULL DEFAULT 'SP',engine_type TEXT NOT NULL DEFAULT 'SE',landings_day INTEGER NOT NULL DEFAULT 0,landings_night INTEGER NOT NULL DEFAULT 0,night_minutes INTEGER NOT NULL DEFAULT 0,ifr_minutes INTEGER NOT NULL DEFAULT 0,pic_minutes INTEGER NOT NULL DEFAULT 0,copilot_minutes INTEGER NOT NULL DEFAULT 0,dual_minutes INTEGER NOT NULL DEFAULT 0,instructor_minutes INTEGER NOT NULL DEFAULT 0,commander TEXT NOT NULL DEFAULT '',instructor TEXT NOT NULL DEFAULT '',role TEXT NOT NULL DEFAULT '',task TEXT NOT NULL DEFAULT '',note TEXT NOT NULL DEFAULT '',purpose_code TEXT NOT NULL DEFAULT '',verification_name TEXT NOT NULL DEFAULT '',verification_reference TEXT NOT NULL DEFAULT '',certified_at TIMESTAMPTZ,certified_by_user_id BIGINT,certification_hash TEXT NOT NULL DEFAULT '',certification_version INTEGER NOT NULL DEFAULT 3,locked_at TIMESTAMPTZ,locked_by_user_id BIGINT,record_revision INTEGER NOT NULL DEFAULT 1,correction_reason TEXT NOT NULL DEFAULT '',correction_opened_at TIMESTAMPTZ,correction_opened_by_user_id BIGINT`;

before(()=>{if(!enabled)return;assert.ok(databaseUrl,"DATABASE_URL is required for PostgreSQL security/restore acceptance tests");const result=rawPsql(`CREATE SCHEMA ${quotedSchema};SET search_path TO ${quotedSchema};CREATE TABLE users(id BIGINT PRIMARY KEY,email TEXT NOT NULL DEFAULT '',display_name TEXT NOT NULL DEFAULT '');CREATE TABLE flights(${flightColumns});CREATE TABLE flight_tracks(id BIGINT PRIMARY KEY,user_id BIGINT NOT NULL,flight_id BIGINT NOT NULL,file_name TEXT NOT NULL DEFAULT '',point_count INTEGER NOT NULL DEFAULT 0,coordinates_json TEXT NOT NULL DEFAULT '[]',overview_coordinates_json TEXT NOT NULL DEFAULT '[]');CREATE TABLE flight_certified_revisions(id BIGINT PRIMARY KEY,flight_id BIGINT NOT NULL,user_id BIGINT NOT NULL,revision_number INTEGER NOT NULL,snapshot_data JSONB NOT NULL,certification_hash TEXT NOT NULL,certification_version INTEGER NOT NULL DEFAULT 1,certified_at TIMESTAMPTZ NOT NULL,superseded_at TIMESTAMPTZ,correction_reason TEXT NOT NULL DEFAULT '');CREATE TABLE flight_verifications(id BIGINT PRIMARY KEY,flight_id BIGINT NOT NULL,flight_user_id BIGINT NOT NULL,signer_user_id BIGINT,verification_role TEXT NOT NULL,record_revision INTEGER NOT NULL,flight_hash TEXT NOT NULL,credential_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,payload_hash TEXT NOT NULL DEFAULT '',server_signature TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'pending',requested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),signed_at TIMESTAMPTZ,declined_at TIMESTAMPTZ,cancelled_at TIMESTAMPTZ,revoked_at TIMESTAMPTZ,decision_note TEXT NOT NULL DEFAULT '',revocation_reason TEXT NOT NULL DEFAULT '',UNIQUE(flight_id,record_revision,signer_user_id,verification_role));CREATE TABLE flight_participations(id BIGINT PRIMARY KEY,source_flight_id BIGINT NOT NULL,source_user_id BIGINT NOT NULL,participant_user_id BIGINT NOT NULL,participant_role TEXT NOT NULL,source_revision INTEGER NOT NULL,source_hash TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',participant_flight_id BIGINT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),responded_at TIMESTAMPTZ,cancelled_at TIMESTAMPTZ,superseded_at TIMESTAMPTZ,decision_note TEXT NOT NULL DEFAULT '',approval_id BIGINT,UNIQUE(source_flight_id,source_revision,participant_user_id));INSERT INTO users(id,email,display_name) VALUES(1,'owner@example.test','Owner'),(2,'participant@example.test','Participant'),(3,'attacker@example.test','Attacker'),(10,'pilot@example.test','Pilot'),(11,'fi@example.test','Test FI');`);if(result.status!==0)throw new Error(`PostgreSQL security/restore schema setup failed:\n${result.stderr||result.stdout}`)});
after(()=>{if(enabled)rawPsql(`DROP SCHEMA IF EXISTS ${quotedSchema} CASCADE`)});

test("AC-13 exact production action SQL rejects cross-user identifiers",{skip:!enabled},()=>{
  run(`INSERT INTO flights(id,user_id,date,certified_at,certification_hash,record_revision) VALUES(101,1,'2026-08-28',NOW(),'owner-r1',1),(102,1,'2026-08-28',NULL,'',1);INSERT INTO flight_verifications(id,flight_id,flight_user_id,signer_user_id,verification_role,record_revision,flight_hash,server_signature,status,signed_at) VALUES(501,101,1,2,'INSTRUCTOR',1,'owner-r1','${"a".repeat(64)}','signed',NOW());INSERT INTO flight_participations(id,source_flight_id,source_user_id,participant_user_id,participant_role,source_revision,source_hash,status) VALUES(601,101,1,2,'INSTRUCTOR',1,'owner-r1','pending');`);
  const certification=read("app/(protected)/flights/certification-actions.ts"),instructor=read("app/(protected)/flights/instructor-actions.ts"),shared=read("app/(protected)/flights/shared-actions.ts"),actions=read("app/(protected)/flights/actions.ts");
  const correctionLookup=sqlBlock(certification,"SELECT certified_at,certification_hash,record_revision FROM flights");assert.equal(rows(render(correctionLookup,{flightId:101,userId:3})).length,0);assert.equal(rows(render(correctionLookup,{flightId:101,userId:1})).length,1);
  const participantGate=sqlBlock(shared,"SELECT participant_role FROM flight_participations WHERE id=");assert.equal(rows(render(participantGate,{participationId:601,userId:3})).length,0);assert.equal(rows(render(participantGate,{participationId:601,userId:2})).length,1);
  const revoke=sqlBlock(instructor,"UPDATE flight_verifications SET status='revoked'");assert.equal(rows(render(revoke,{reason:"Unauthorised attempt",verificationId:501,"session.userId":3})).length,0);assert.equal(run(`SELECT status FROM flight_verifications WHERE id=501`),"signed");assert.equal(rows(render(revoke,{reason:"Signer revocation",verificationId:501,"session.userId":2})).length,1);assert.equal(run(`SELECT status FROM flight_verifications WHERE id=501`),"revoked");
  const cancel=sqlBlock(shared,"UPDATE flight_participations SET status='cancelled',cancelled_at=NOW()");assert.equal(rows(render(cancel,{participationId:601,sourceFlightId:101,userId:2})).length,0);assert.equal(rows(render(cancel,{participationId:601,sourceFlightId:101,userId:3})).length,0);assert.equal(rows(render(cancel,{participationId:601,sourceFlightId:101,userId:1})).length,1);
  const lock=sqlBlock(actions,"UPDATE flights SET locked_at=NOW(),locked_by_user_id=");run(render(lock,{userId:3,flightId:102}));assert.equal(run(`SELECT COALESCE(locked_by_user_id::text,'') FROM flights WHERE id=102`),"");run(render(lock,{userId:1,flightId:102}));assert.equal(run(`SELECT locked_by_user_id::text FROM flights WHERE id=102`),"1");
});

const sectionKeys=["flights","aircraft","rates","airports","expiries","settings","flight_tracks","track_points","audit_log","fstd_sessions","flight_certified_revisions","fstd_certified_revisions","deleted_flights","pilot_connections","flight_participations","instructor_flight_approvals","pilot_licences","pilot_qualifications","user_notifications","flight_verifications","connection_audit_log"] as const;
async function makeBackup(){
  process.env.SIGNING_SECRET=process.env.SIGNING_SECRET||"flytally-ci-signing-secret-with-enough-entropy";
  const common={id:1001,user_id:10,date:"2026-08-20",evidence:"EASA",registration:"OK-TST",aircraft_make:"Bristell",aircraft_model:"B23",aircraft_variant:"",aircraft_type:"B23",aircraft_class:"SEP",departure:"LKPR",arrival:"LKBE",off_block:"10:00",takeoff:"10:05",landing:"11:00",on_block:"11:05",starts:1,operation_type:"SP",engine_type:"SE",landings_day:1,landings_night:0,night_minutes:0,ifr_minutes:0,pic_minutes:0,copilot_minutes:0,dual_minutes:65,instructor_minutes:0,commander:"Test FI",instructor:"Test FI",role:"DUAL",task:"Refresher training",note:"",purpose_code:"LAPL_FCL140A_REFRESHER",verification_name:"",verification_reference:"",certification_version:3,locked_by_user_id:10};
  const r1Base={...common,record_revision:1,correction_reason:"",certified_at:"2026-08-20T11:10:00.000Z",certified_by_user_id:10,locked_at:"2026-08-20T11:10:00.000Z",correction_opened_at:null,correction_opened_by_user_id:null,certification_hash:""},r1Hash=flightCertificationHash(r1Base,10,3),r1={...r1Base,certification_hash:r1Hash};
  const r2Base={...r1,arrival:"LKMB",record_revision:2,correction_reason:"Corrected destination after review",certified_at:"2026-08-21T09:00:00.000Z",locked_at:"2026-08-21T09:00:00.000Z",correction_opened_at:"2026-08-21T08:45:00.000Z",correction_opened_by_user_id:10,certification_hash:""},r2Hash=flightCertificationHash(r2Base,10,3),r2={...r2Base,certification_hash:r2Hash};
  const manualCredential={identity:"Test FI",source:"In-person handwritten signature",licenceNumber:"CZ.FCL.123",qualification:"FI(A)",captureMethod:"same-device",signature:{version:1,width:600,height:180,strokes:[[[10,20],[20,24],[30,18],[45,22]]]}},accountCredential={identity:"Test FI",source:"FlyTally account",licences:[{licence_type:"CPL(A)",licence_number:"CZ.FCL.123",authority:"CAA CZ"}],qualifications:[{qualification_type:"FI(A)",certificate_reference:"FI-123"}]};
  const manualPayload={flightId:1001,flightUserId:10,signerUserId:null,recordRevision:1,flightHash:r1Hash,verificationRole:"INSTRUCTOR",credentialSnapshot:manualCredential},accountPayload={flightId:1001,flightUserId:10,signerUserId:11,recordRevision:2,flightHash:r2Hash,verificationRole:"INSTRUCTOR",credentialSnapshot:accountCredential},coordinates=JSON.stringify([{lat:50.1,lon:14.2,alt:300,time:"2026-08-20T10:05:00Z"},{lat:50.2,lon:14.4,alt:900,time:"2026-08-20T10:30:00Z"},{lat:50.3,lon:14.6,alt:320,time:"2026-08-20T11:00:00Z"}]),requestedAt="2026-08-21T08:50:00.000Z";
  const arrays:Record<string,unknown[]>={flights:[r2],aircraft:[],rates:[],airports:[],expiries:[],settings:[],flight_tracks:[{id:7001,user_id:10,flight_id:1001,file_name:"OK-TST.kml",point_count:3,coordinates_json:coordinates,overview_coordinates_json:coordinates}],track_points:[],audit_log:[],fstd_sessions:[],flight_certified_revisions:[{id:3001,flight_id:1001,user_id:10,revision_number:1,snapshot_data:r1,certification_hash:r1Hash,certification_version:3,certified_at:r1.certified_at,superseded_at:"2026-08-21T08:45:00.000Z",correction_reason:"Corrected destination after review"}],fstd_certified_revisions:[],deleted_flights:[],pilot_connections:[],flight_participations:[{id:8001,source_flight_id:1001,source_user_id:10,participant_user_id:11,participant_role:"INSTRUCTOR",source_revision:2,source_hash:r2Hash,status:"accepted",participant_flight_id:null,created_at:requestedAt,responded_at:"2026-08-21T09:02:00.000Z",cancelled_at:null,superseded_at:null,decision_note:"Signed",approval_id:null}],instructor_flight_approvals:[],pilot_licences:[],pilot_qualifications:[],user_notifications:[],flight_verifications:[{id:9001,flight_id:1001,flight_user_id:10,signer_user_id:null,verification_role:"INSTRUCTOR",record_revision:1,flight_hash:r1Hash,credential_snapshot:manualCredential,payload_hash:r1Hash,server_signature:signVerificationPayload(manualPayload),status:"signed",requested_at:"2026-08-20T11:11:00.000Z",signed_at:"2026-08-20T11:12:00.000Z",declined_at:null,cancelled_at:null,revoked_at:null,decision_note:"",revocation_reason:""},{id:9002,flight_id:1001,flight_user_id:10,signer_user_id:11,verification_role:"INSTRUCTOR",record_revision:2,flight_hash:r2Hash,credential_snapshot:accountCredential,payload_hash:r2Hash,server_signature:signVerificationPayload(accountPayload),status:"signed",requested_at:requestedAt,signed_at:"2026-08-21T09:02:00.000Z",declined_at:null,cancelled_at:null,revoked_at:null,decision_note:"",revocation_reason:""}],connection_audit_log:[]};
  const counts=Object.fromEntries(sectionKeys.map(key=>[key,arrays[key].length])),payload={format:"pilot-logbook-portable",version:7,schema_version:13,exported_at:"2026-08-28T07:30:00.000Z",profile:{id:10,email:"pilot@example.test",display_name:"Pilot"},counts,...arrays} as unknown as Omit<PortableBackup,"integrity">,digest=await portableBackupDigest(JSON.stringify(payload)),backup={...payload,integrity:{algorithm:"SHA-256",payload_sha256:digest}} as PortableBackup;
  return{backup,json:JSON.stringify(backup),r1Hash,r2Hash,coordinates};
}

test("AC-19 and AC-22 backup validates certification plus HMAC evidence and rejects tampering",{skip:!enabled},async()=>{const fixture=await makeBackup(),parsed=await parsePortableBackup(fixture.json),summary=validateBackupCertificationHistory(parsed.backup,10);assert.equal(summary.certifiedFlights,1);assert.equal(summary.flightRevisions,1);const damaged=JSON.parse(fixture.json);damaged.flight_tracks[0].point_count=99;await assert.rejects(()=>parsePortableBackup(JSON.stringify(damaged)),/Integrity check failed/i);const forged=JSON.parse(fixture.json);forged.flight_verifications[1].server_signature="0".repeat(64);delete forged.integrity;const digest=await portableBackupDigest(JSON.stringify(forged));forged.integrity={algorithm:"SHA-256",payload_sha256:digest};const reparsed=await parsePortableBackup(JSON.stringify(forged));assert.throws(()=>validateBackupCertificationHistory(reparsed.backup,10),/failed HMAC verification/i)});

test("AC-20 production restore SQL preserves R1/R2 hashes, signatures, participation and GPS",{skip:!enabled},async()=>{
  const fixture=await makeBackup(),{backup}=await parsePortableBackup(fixture.json);validateBackupCertificationHistory(backup,10);run(`DELETE FROM flight_verifications WHERE flight_id=1001;DELETE FROM flight_participations WHERE source_flight_id=1001;DELETE FROM flight_tracks WHERE flight_id=1001;DELETE FROM flight_certified_revisions WHERE flight_id=1001;DELETE FROM flights WHERE id=1001;`);const restore=read("lib/account-restore-v6.ts"),flight=backup.flights[0],staged={...flight,aircraft_make:"",aircraft_model:"",aircraft_variant:"",certified_at:null,certified_by_user_id:null,certification_hash:"",locked_at:null,locked_by_user_id:null};
  const apply=()=>{run(render(sqlBlock(restore,"INSERT INTO flights SELECT (json_populate_record(NULL::flights,item)).*"),{"JSON.stringify(batch)":[staged]}));run(render(sqlBlock(restore,"UPDATE flights f SET aircraft_make="),{"JSON.stringify(batch)":[flight],userId:10}));run(render(sqlBlock(restore,"INSERT INTO flight_tracks SELECT (json_populate_record(NULL::flight_tracks,item)).*"),{"JSON.stringify(batch)":backup.flight_tracks}));run(render(sqlBlock(restore,"INSERT INTO flight_certified_revisions SELECT (json_populate_record(NULL::flight_certified_revisions,item)).*"),{"JSON.stringify(batch)":backup.flight_certified_revisions}));run(render(sqlBlock(restore,"INSERT INTO flight_participations SELECT (json_populate_record(NULL::flight_participations,item)).*"),{"JSON.stringify(batch)":backup.flight_participations}));run(render(sqlBlock(restore,"INSERT INTO flight_verifications SELECT (json_populate_record(NULL::flight_verifications,item)).*"),{"JSON.stringify(batch)":backup.flight_verifications}))};
  apply();const restored=rows(`SELECT * FROM flights WHERE id=1001 AND user_id=10`)[0];assert.ok(restored);assert.equal(verifyFlightCertification(restored,10).status,"verified");assert.equal(String(restored.purpose_code),"LAPL_FCL140A_REFRESHER");assert.equal(String(restored.certification_hash),fixture.r2Hash);const revision=rows(`SELECT * FROM flight_certified_revisions WHERE flight_id=1001 AND revision_number=1`)[0],snapshot=revision.snapshot_data as Record<string,unknown>;assert.equal(verifyFlightCertification({...snapshot,certification_hash:revision.certification_hash,certification_version:revision.certification_version},10).status,"verified");assert.equal(String(revision.certification_hash),fixture.r1Hash);const verifications=rows(`SELECT * FROM flight_verifications WHERE flight_id=1001 ORDER BY id`);assert.equal(verifications.length,2);for(const verification of verifications)assert.equal(verificationCryptographicStatus(verification),"verified");assert.equal((verifications[0].credential_snapshot as Record<string,unknown>).source,"In-person handwritten signature");const track=rows(`SELECT * FROM flight_tracks WHERE flight_id=1001`)[0];assert.equal(Number(track.point_count),3);assert.equal(String(track.coordinates_json),fixture.coordinates);const participation=rows(`SELECT * FROM flight_participations WHERE source_flight_id=1001`)[0];assert.equal(String(participation.source_hash),fixture.r2Hash);assert.equal(String(participation.status),"accepted");apply();assert.equal(run(`SELECT COUNT(*) FROM flights WHERE id=1001`),"1");assert.equal(run(`SELECT COUNT(*) FROM flight_certified_revisions WHERE flight_id=1001`),"1");assert.equal(run(`SELECT COUNT(*) FROM flight_verifications WHERE flight_id=1001`),"2");assert.equal(run(`SELECT COUNT(*) FROM flight_tracks WHERE flight_id=1001`),"1");
});
