"use server";
import { revalidatePath } from "next/cache";
import { requireUser } from "@/lib/auth/require-user";
import { sql } from "@/lib/db";
import { hashLegacyPassword } from "@/lib/auth/password";

async function admin(){const session=await requireUser();if(session.role!=="admin")throw new Error("Přístup odepřen.");return session}
export async function toggleUser(form:FormData){const session=await admin(),id=Number(form.get("id"));if(!Number.isSafeInteger(id)||id<=0||id===session.userId)return;await sql`UPDATE users SET active=CASE WHEN active=1 THEN 0 ELSE 1 END,updated_at=NOW() WHERE id=${id}`;revalidatePath("/admin")}
export async function changeRole(form:FormData){const session=await admin(),id=Number(form.get("id")),role=String(form.get("role"))==="admin"?"admin":"user";if(!Number.isSafeInteger(id)||id<=0||id===session.userId)return;await sql`UPDATE users SET role=${role},updated_at=NOW() WHERE id=${id}`;revalidatePath("/admin")}
export async function createUser(form:FormData){await admin();const email=String(form.get("email")??"").trim().toLowerCase().slice(0,254),displayName=String(form.get("display_name")??"").trim().slice(0,120),password=String(form.get("password")??""),role=String(form.get("role"))==="admin"?"admin":"user";if(!email||!email.includes("@")||!displayName||password.length<10)return;const hash=await hashLegacyPassword(password),slug=`${email.split("@")[0].replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,40)||"pilot"}-${Date.now().toString(36)}`;const rows=await sql`WITH created AS (INSERT INTO users(email,display_name,slug,role,active,created_at,updated_at) VALUES(${email},${displayName},${slug},${role},1,NOW(),NOW()) RETURNING id) INSERT INTO user_credentials(user_id,password_hash,created_at,updated_at) SELECT id,${hash},NOW(),NOW() FROM created RETURNING user_id` as Array<{user_id:number|string}>;if(rows[0])await sql`INSERT INTO user_settings(user_id,timezone,currency,default_role,created_at,updated_at) VALUES(${Number(rows[0].user_id)},'Europe/Prague','CZK','PIC',NOW(),NOW()) ON CONFLICT(user_id) DO NOTHING`;revalidatePath("/admin")}
export async function resetUserPassword(form:FormData){const session=await admin(),id=Number(form.get("id")),password=String(form.get("password")??"");if(!Number.isSafeInteger(id)||id<=0||id===session.userId||password.length<10)return;const hash=await hashLegacyPassword(password);await sql`UPDATE user_credentials SET password_hash=${hash},updated_at=NOW() WHERE user_id=${id}`;revalidatePath("/admin")}
