import Link from "next/link";
import { requireUser } from "@/lib/auth/require-user";
import { formatDuration } from "@/lib/data/dashboard";
import type { FlightRow } from "@/lib/data/flights";
import { getFlightFilterOptionsFast as getFlightFilterOptions,getFlightsPageFast as getFlightsPage } from "@/lib/data/flights-fast";
export const metadata={title:"Flights | FlyTally"};

type Params={page?:string;size?:string;q?:string;evidence?:string;role?:string;registration?:string;aircraftClass?:string;airport?:string;route?:string;routePair?:string;gps?:string;year?:string;sort?:string;from?:string;to?:string};
function href(params:Params,changes:Params){const out=new URLSearchParams();for(const [key,value] of Object.entries({...params,...changes}))if(value)out.set(key,value);return `/flights?${out}`;}
function detailHref(id:number,params:Params){const out=new URLSearchParams();for(const [key,value] of Object.entries(params))if(value&&key!=="page"&&key!=="size")out.set(key,value);const query=out.toString();return `/flights/${id}${query?`?${query}`:""}`;}
function pageLinks(current:number,pages:number){const visible=new Set([1,pages,current-2,current-1,current,current+1,current+2].filter(value=>value>=1&&value<=pages)),sorted=[...visible].sort((a,b)=>a-b),out:Array<number|string>=[];for(const value of sorted){const previous=out.at(-1);if(typeof previous==="number"&&value-previous>1)out.push(`gap-${previous}-${value}`);out.push(value)}return out}
function Pagination({params,page,pages,total,all,showTotal=false}:{params:Params;page:number;pages:number;total:number;all:boolean;showTotal?:boolean}){return <nav className="pagination" aria-label="Flight pages">{showTotal?<span>{total} records</span>:null}{all?<strong>All records</strong>:<><Link aria-disabled={page<=1} href={href(params,{page:String(Math.max(1,page-1))})}>←</Link><div className="page-number-list">{pageLinks(page,pages).map(item=>typeof item==="number"?<Link key={item} aria-current={item===page?"page":undefined} href={href(params,{page:String(item)})}>{item}</Link>:<span key={item}>…</span>)}</div><Link aria-disabled={page>=pages} href={href(params,{page:String(Math.min(pages,page+1))})}>→</Link></>}</nav>}
const recordStatus=(flight:FlightRow)=>{const revision=Math.max(1,Number(flight.record_revision||1));if(flight.certified_at)return`Certified R${revision}`;if(revision>1&&flight.correction_reason)return`Correction R${revision}`;if(flight.locked_at)return"Locked";return"Draft"};

export default async function FlightsPage({searchParams}:{searchParams:Promise<Params>}){
  const session=await requireUser(),params=await searchParams;
  const all=params.size==="all",filters={...params,page:Number(params.page||1),size:all?5000:Number(params.size||50)};
  const [result,options]=await Promise.all([getFlightsPage(session.userId,filters),getFlightFilterOptions(session.userId)]),pages=Math.max(1,Math.ceil(result.total/result.size));
  const active=[params.q,params.year,params.evidence,params.role,params.aircraftClass,params.registration,params.airport,params.route,params.routePair,params.gps,params.from,params.to].filter(Boolean).length;
  return <>
    <header className="page-header"><div><p className="eyebrow">LOGBOOK</p><h1>Flights</h1></div><Link className="primary-link" href="/flights/new">＋ Add flight</Link></header>
    <details className="panel filter-panel filter-expander"><summary><span>Filters and sorting</span><small>{active?`${active} active`:"Filters"}</small></summary><form method="get"><div className="filter-grid">{params.routePair?<input type="hidden" name="routePair" value={params.routePair}/>:null}
      <label className="search-field">Search<input name="q" defaultValue={params.q} placeholder="Registration, airport, type, role…"/></label>
      <label>Year<select name="year" defaultValue={params.year||""}><option value="">All</option>{options.years.map(value=><option key={value}>{value}</option>)}</select></label>
      <label>Logbook<select name="evidence" defaultValue={params.evidence||""}><option value="">All</option>{options.evidence.map(value=><option key={value}>{value}</option>)}</select></label>
      <label>Role<select name="role" defaultValue={params.role||""}><option value="">All</option>{options.roles.map(value=><option key={value}>{value}</option>)}</select></label>
      <label>Class<select name="aircraftClass" defaultValue={params.aircraftClass||""}><option value="">All</option>{options.classes.map(value=><option key={value}>{value}</option>)}</select></label>
      <label>Aircraft<select name="registration" defaultValue={params.registration||""}><option value="">All</option>{options.registrations.map(value=><option key={value}>{value}</option>)}</select></label>
      <label>Airport<select name="airport" defaultValue={params.airport||""}><option value="">All</option>{options.airports.map(value=><option key={value}>{value}</option>)}</select></label>
      <label>Route<select name="route" defaultValue={params.route||""}><option value="">All</option>{options.routes.map(value=><option key={value}>{value}</option>)}</select></label>
      <label>GPS<select name="gps" defaultValue={params.gps||""}><option value="">All</option><option value="with">With GPS</option><option value="without">Without GPS</option></select></label>
      <label>Sort<select name="sort" defaultValue={params.sort||"newest"}><option value="newest">Newest</option><option value="oldest">Oldest</option><option value="longest">Longest BLOCK</option><option value="cost">Highest cost</option><option value="gps">Longest GPS track</option></select></label>
      <label>From<input type="date" name="from" defaultValue={params.from}/></label><label>To<input type="date" name="to" defaultValue={params.to}/></label>
      <div className="filter-actions"><button className="primary-button">Apply</button><Link className="secondary-link" href="/flights">Clear</Link></div>
    </div></form></details>
    {params.routePair?<div className="active-route-filter"><div><span>SELECTED ROUTE</span><strong>{params.routePair.replace("↔"," ↔ ")}</strong></div><Link href={href(params,{routePair:undefined,page:"1"})}>Clear</Link></div>:null}
    <section className="flight-summary"><div><span>Flights</span><strong>{result.summary.flights}</strong><small>{result.summary.tracks} GPS tracks</small></div><div><span>BLOCK</span><strong>{formatDuration(result.summary.blockMinutes)}</strong></div><div><span>PIC</span><strong>{formatDuration(result.summary.picMinutes)}</strong></div><div><span>Cost</span><strong>{Math.round(result.summary.cost).toLocaleString("en-GB")} CZK</strong></div><div><span>Landings</span><strong>{result.summary.landings}</strong><small>{result.summary.gpsKm.toFixed(0)} GPS km</small></div></section>
    <section className="table-panel flights-table"><div className="list-toolbar"><div className="page-size-control"><span>Show</span>{[{label:"25",value:"25"},{label:"50",value:"50"},{label:"All",value:"all"}].map(option=><Link key={option.value} className={(all?option.value==="all":String(result.size)===option.value)?"active":""} href={href(params,{size:option.value,page:"1"})}>{option.label}</Link>)}</div><Pagination params={params} page={result.page} pages={pages} total={result.total} all={all}/></div><div className="table-scroll"><table><thead><tr><th>Details</th><th>Date</th><th>Aircraft</th><th>Route</th><th>Times</th><th>BLOCK</th><th>Cost</th><th>Role</th><th>Landings</th><th>GPS</th></tr></thead><tbody>{result.rows.map(f=><tr key={f.id}><td data-label="Flight"><Link className="detail-button" href={detailHref(f.id,params)}>View flight</Link></td><td data-label="Date">{new Date(`${f.date}T00:00:00`).toLocaleDateString("en-GB")}</td><td data-label="Aircraft"><strong>{f.registration||"—"}</strong><small>{f.aircraft_type||f.evidence}</small></td><td data-label="Route"><strong>{f.departure||"—"} → {f.arrival||"—"}</strong><small>{f.task||""}</small></td><td data-label="Times"><span className="time-pair"><small>BLOCK</small>{f.off_block||"—"}–{f.on_block||"—"}</span><span className="time-pair"><small>AIR</small>{f.takeoff&&f.landing?`${f.takeoff}–${f.landing}`:"—"}</span></td><td data-label="Duration"><strong>{formatDuration(f.block_minutes)}</strong><small>AIR {formatDuration(f.air_minutes)}</small></td><td data-label="Cost"><strong>{f.price_per_hour?`${Math.round(f.calculated_price).toLocaleString("en-GB")} CZK`:"—"}</strong><small>{f.billing_basis||"BLOCK"}</small></td><td data-label="Role"><strong>{f.role||"—"}</strong><span className="record-status">{recordStatus(f)}</span><small>{f.evidence}</small></td><td data-label="Landings">{f.starts}</td><td data-label="GPS">{f.track_count?<Link className="gps-badge" href={detailHref(f.id,params)}>● {f.track_count}<small>{f.gps_km.toFixed(0)} km</small></Link>:<span className="muted">—</span>}</td></tr>)}{!result.rows.length?<tr><td colSpan={10} className="empty-state">No flights match these filters.</td></tr>:null}</tbody></table></div>
      <Pagination params={params} page={result.page} pages={pages} total={result.total} all={all} showTotal/>
    </section>
  </>;
}
