import Link from "next/link";
import { notFound } from "next/navigation";
import { requireUser } from "@/lib/auth/require-user";
import { sql } from "@/lib/db";
import { ensureRuntimeSchema } from "@/lib/runtime-schema";
import { InPersonSignaturePad } from "@/components/in-person-signature-pad";
import { SignaturePreview } from "@/components/signature-preview";
import { aircraftTrainingCredentialSnapshot,aircraftTrainingVerificationStatus } from "@/lib/aircraft-training-verification";
import { signAircraftQualificationInPerson } from "@/app/(protected)/credentials/aircraft-actions";

const t=(value:unknown)=>String(value??"").trim();
const label=(row:Record<string,unknown>)=>[t(row.aircraft_make),t(row.aircraft_model),t(row.aircraft_variant)].filter(Boolean).join(" ")||t(row.qualification_type)||"Aircraft training";
const kind=(value:unknown)=>value==="differences"?"Differences training":value==="familiarisation"?"Familiarisation":value==="class_type"?"Class / type training":value==="national"?"National / ULL authorisation":"Other aircraft training";
const dateTime=(value:unknown)=>{const date=new Date(String(value??""));return Number.isNaN(date.getTime())?t(value):new Intl.DateTimeFormat("en-GB",{dateStyle:"medium",timeStyle:"short",timeZone:"UTC"}).format(date)+" UTC"};

export default async function AircraftTrainingInPersonSignature({params}:{params:Promise<{id:string}>}){
  const{userId}=await requireUser();await ensureRuntimeSchema();const recordId=Number((await params).id);if(!Number.isSafeInteger(recordId)||recordId<=0)notFound();
  const rows=await sql`SELECT id,user_id,qualification_type,certificate_reference,linked_licence_id,training_kind,aircraft_make,aircraft_model,aircraft_variant,differences,completed_on::text completed_on,instructor_name,training_organisation,notes,requested_signer_user_id,signature_status,verification_role,verified_at,verified_by_user_id,verification_snapshot,verification_signature,verification_note,verification_version
    FROM pilot_qualifications WHERE id=${recordId} AND user_id=${userId} AND record_kind='aircraft_training' AND record_active IS TRUE LIMIT 1` as Array<Record<string,unknown>>;
  const row=rows[0];if(!row)notFound();const status=aircraftTrainingVerificationStatus(row),snapshot=aircraftTrainingCredentialSnapshot(row.verification_snapshot),inPerson=t(snapshot.source)==="In-person handwritten signature";
  const recordLabel=`this exact ${kind(row.training_kind).toLowerCase()} record for ${label(row)} dated ${t(row.completed_on)||"the recorded date"}`;
  return <>
    <header className="page-header"><div><p className="eyebrow">IN-PERSON TRAINING SIGNATURE</p><h1>{label(row)}</h1><p className="muted">{t(row.completed_on)||"Date not recorded"} · {kind(row.training_kind)}</p></div><Link className="secondary-link" href="/credentials">← Licences</Link></header>
    <section className="panel"><div className="section-heading"><div><p className="eyebrow">TRAINING EVIDENCE</p><h2>{kind(row.training_kind)}</h2></div><span className={status==="verified"?"status-on":status==="pending"?"status-warning":status==="revoked"||status==="invalid"?"status-off":"record-status"}>{status.toUpperCase()}</span></div><div className="detail-grid"><div><span>Class / type</span><strong>{t(row.qualification_type)||"—"}</strong></div><div><span>Aircraft</span><strong>{label(row)}</strong></div><div><span>Completed</span><strong>{t(row.completed_on)||"—"}</strong></div><div><span>Organisation</span><strong>{t(row.training_organisation)||"—"}</strong></div><div><span>Record reference</span><strong>{t(row.certificate_reference)||"—"}</strong></div><div><span>Instructor / examiner</span><strong>{t(row.instructor_name)||"—"}</strong></div></div>{t(row.differences)?<p><strong>Differences / equipment:</strong> {t(row.differences)}</p>:null}{t(row.notes)?<p><strong>Notes:</strong> {t(row.notes)}</p>:null}</section>
    {status==="verified"?<section className="panel"><div className="section-heading"><div><p className="eyebrow">SIGNATURE EVIDENCE</p><h2>{inPerson?"Signed in person":"Signed with a FlyTally account"}</h2><p className="muted">The stored server signature verifies against the exact training contents and credential snapshot.</p></div><span className="status-on">VERIFIED</span></div>{inPerson?<div className="credential-list"><div className="credential-card"><div className="credential-editor"><p><strong>{t(snapshot.identity)}</strong></p><p className="muted">Licence {t(snapshot.licenceNumber)||"—"} · {t(snapshot.qualification)||"—"}{t(snapshot.qualificationReference)?` · ${t(snapshot.qualificationReference)}`:""}</p><SignaturePreview signature={snapshot.signature}/><p className="muted">Signed {dateTime(row.verified_at)} · captured in person on this device. The identity was not independently authenticated by a FlyTally account.</p></div></div></div>:<p className="muted">Signer: {t(snapshot.identity)||"FlyTally pilot"} · signed {dateTime(row.verified_at)}.</p>}</section>:row.verified_at?<section className="panel"><p className="form-error">This record already contains signature evidence with status {status.toUpperCase()}. Create a corrected training record rather than overwriting signed evidence.</p></section>:<section className="panel"><div className="section-heading"><div><p className="eyebrow">SIGN ON THIS DEVICE</p><h2>Instructor / examiner signature</h2><p className="muted">Use this when the instructor or examiner is physically present. Any outstanding connected-pilot request is closed when the in-person signature succeeds.</p></div></div><InPersonSignaturePad action={signAircraftQualificationInPerson.bind(null,recordId)} defaultInstructor={t(row.instructor_name)} recordLabel={recordLabel} allowExaminer defaultQualification="FI(A) / FE(A)"/></section>}
  </>;
}
