import { PendingActionButton } from "@/components/pending-action-button";
import { requireUser } from "@/lib/auth/require-user";
import { sql } from "@/lib/db";
import { ensureV165Schema } from "@/lib/v165-schema";
import { classifyQualificationLabel,qualificationCategoryLabel,qualificationFamilyLabel,QUALIFICATION_CATEGORIES,QUALIFICATION_FAMILIES,QUALIFICATION_ROLES,type QualificationCategory,type QualificationFamily,type QualificationRole } from "@/lib/qualification-structure";
import { QUALIFICATION_CATALOG,qualificationCatalogEntry } from "@/lib/qualification-catalog";
import { clearQualificationStructure,saveQualificationStructure } from "@/app/(protected)/credentials/qualification-actions";

const t=(value:unknown)=>String(value??"").trim();
const upper=(value:unknown)=>t(value).toUpperCase();
const selected=<T extends string>(value:unknown,allowed:readonly T[],fallback:T)=>allowed.includes(upper(value) as T)?upper(value) as T:fallback;

export async function AdvancedQualificationsPanel(){
  await ensureV165Schema();const{userId}=await requireUser();
  const rows=await sql`SELECT q.id,q.qualification_type,q.certificate_reference,q.qualification_family,q.regulatory_category,q.qualification_scope,q.privilege_role,q.classification_source,q.issued_on::text issued_on,q.limitations,l.licence_type,l.licence_number
    FROM pilot_qualifications q JOIN pilot_licences l ON l.id=q.licence_id AND l.user_id=q.user_id
    WHERE q.user_id=${userId} AND q.active=TRUE AND l.active=TRUE AND COALESCE(q.record_kind,'')<>'aircraft_training'
    ORDER BY l.licence_type,q.qualification_type,q.id` as Array<Record<string,unknown>>;
  if(!rows.length)return null;
  const enriched=rows.map(row=>{const hint=classifyQualificationLabel(row.qualification_type,row.licence_type),confirmed=upper(row.classification_source)==="USER_CONFIRMED",family=confirmed?selected<QualificationFamily>(row.qualification_family,QUALIFICATION_FAMILIES,"OTHER"):hint.family,category=confirmed?selected<QualificationCategory>(row.regulatory_category,QUALIFICATION_CATEGORIES,"OTHER"):hint.category,role=confirmed?selected<QualificationRole>(row.privilege_role,QUALIFICATION_ROLES,"OTHER"):hint.role,scope=confirmed?t(row.qualification_scope):hint.scope,catalog=qualificationCatalogEntry(confirmed?t(row.qualification_scope):row.qualification_type);return{row,hint,confirmed,family,category,role,scope,catalog}});
  const confirmedCount=enriched.filter(item=>item.confirmed).length,unclassified=enriched.filter(item=>item.family==="OTHER").length;
  return <section className="panel expiry-panel advanced-qualifications-panel"><details className="credential-create"><summary><span><strong>Advanced qualification structure</strong><small>{confirmedCount}/{rows.length} confirmed{unclassified?` · ${unclassified} needs classification`:""}</small></span></summary>
    <div className="section-heading"><div><p className="eyebrow">ADVANCED QUALIFICATIONS · v1.65</p><h2>Qualification structure</h2><p className="muted">Family, aircraft category and privilege role are kept separate from validity and recency. Legacy labels are shown only as conservative hints until you confirm them.</p></div><span>{rows.length}</span></div>
    <datalist id="v165-qualification-scopes">{QUALIFICATION_CATALOG.map(item=><option key={`${item.category}-${item.code}`} value={item.code}>{item.label}</option>)}</datalist>
    <div className="credential-list">{enriched.map(({row,hint,confirmed,family,category,role,scope,catalog})=>{const id=Number(row.id);return <details className="credential-card" key={id}><summary className="credential-summary"><div className="credential-main"><span>{t(row.licence_type)} · {t(row.licence_number)}</span><strong>{t(row.qualification_type)}</strong><small>{qualificationFamilyLabel(family)} · {qualificationCategoryLabel(category)} · {role.toLowerCase()}</small></div><div className="credential-validity"><b className={confirmed?"status-on":"record-status"}>{confirmed?"CONFIRMED":"HINT"}</b><small>{catalog?.reference|| (confirmed?"Pilot-confirmed structure":hint.confidence==="unknown"?"Needs classification":"Derived from existing label")}</small></div><span className="credential-chevron" aria-hidden="true">⌄</span></summary>
      <div className="credential-editor"><form action={saveQualificationStructure} className="form-grid settings-grid"><input type="hidden" name="id" value={id}/><label>Family<select name="qualification_family" defaultValue={family}>{QUALIFICATION_FAMILIES.map(value=><option key={value} value={value}>{qualificationFamilyLabel(value)}</option>)}</select></label><label>Aircraft category<select name="regulatory_category" defaultValue={category}>{QUALIFICATION_CATEGORIES.map(value=><option key={value} value={value}>{qualificationCategoryLabel(value)}</option>)}</select></label><label>Privilege role<select name="privilege_role" defaultValue={role}>{QUALIFICATION_ROLES.map(value=><option key={value} value={value}>{value[0]+value.slice(1).toLowerCase()}</option>)}</select></label><label>Scope / rating<input name="qualification_scope" list="v165-qualification-scopes" defaultValue={scope} placeholder="SEP(land), R44, IR(A)…"/></label><label>Issued / last authority entry<input type="date" name="issued_on" max={new Date().toISOString().slice(0,10)} defaultValue={t(row.issued_on).slice(0,10)}/></label><label className="wide">Limitations / extensions<textarea name="limitations" rows={2} defaultValue={t(row.limitations)} placeholder="Only explicit limitations or extensions recorded on the licence/certificate"/></label><div className="form-actions wide"><PendingActionButton className="primary-button" pendingLabel="Saving…">Confirm qualification structure</PendingActionButton></div></form>
      {confirmed?<form action={clearQualificationStructure} className="credential-record-actions"><input type="hidden" name="id" value={id}/><PendingActionButton className="secondary-link" pendingLabel="Updating…">Return to label hint</PendingActionButton></form>:null}<p className="muted">This classification organises the logbook only. It does not issue, extend, revalidate or renew the qualification.</p></div></details>})}</div>
  </details></section>;
}
