"use client";

import { useState } from "react";

type Result={ok:boolean;title:string;detail:string;counts?:Record<string,number>};

async function digest(value:string){const hash=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return Array.from(new Uint8Array(hash),byte=>byte.toString(16).padStart(2,"0")).join("")}

export function BackupValidator(){
  const[result,setResult]=useState<Result|null>(null),[checking,setChecking]=useState(false);
  const inspect=async(file?:File)=>{if(!file){setResult(null);return}setChecking(true);try{if(file.size>150*1024*1024)throw new Error("Soubor je větší než bezpečný limit 150 MB.");const parsed=JSON.parse(await file.text()) as Record<string,unknown>,integrity=parsed.integrity as Record<string,unknown>|undefined;const{integrity:_removed,...payload}=parsed;if(payload.format!=="pilot-logbook-portable")throw new Error("Soubor není přenosná záloha Logbooku.");if(!Array.isArray(payload.flights)||!Array.isArray(payload.aircraft)||!Array.isArray(payload.rates))throw new Error("Záloha neobsahuje povinné datové části.");const expected=String(integrity?.payload_sha256??""),actual=await digest(JSON.stringify(payload));if(!expected)throw new Error("Starší záloha nemá kontrolní SHA-256 otisk. Data lze prohlédnout, ale nelze ověřit jejich úplnost.");if(expected!==actual)throw new Error("Kontrolní otisk nesouhlasí. Soubor je poškozený nebo byl po exportu změněn.");const counts=Object.fromEntries(Object.entries(payload.counts as Record<string,unknown>||{}).map(([key,value])=>[key,Number(value)||0]));setResult({ok:true,title:"Záloha je úplná a nepoškozená",detail:`Verze ${String(payload.version??"?")} · vytvořeno ${String(payload.exported_at??"neuvedeno")}`,counts})}catch(error){setResult({ok:false,title:"Zálohu nelze bezpečně ověřit",detail:error instanceof Error?error.message:"Neznámá chyba souboru."})}finally{setChecking(false)}};
  return <section className="panel backup-validator"><div><p className="eyebrow">KONTROLA ZÁLOHY</p><h2>Ověřit úplnou JSON zálohu</h2><p className="muted">Kontrola probíhá pouze ve vašem prohlížeči. Nic se neodesílá ani nezapisuje do databáze.</p></div><label className="backup-file">Soubor zálohy<input type="file" accept="application/json,.json" onChange={event=>inspect(event.target.files?.[0])}/></label>{checking?<p className="muted">Počítám kontrolní otisk…</p>:null}{result?<div className={`backup-result ${result.ok?"valid":"invalid"}`}><strong>{result.ok?"✓":"⚠"} {result.title}</strong><p>{result.detail}</p>{result.counts?<div>{Object.entries(result.counts).map(([key,value])=><span key={key}><small>{key.replaceAll("_"," ")}</small><b>{value.toLocaleString("cs-CZ")}</b></span>)}</div>:null}</div>:null}</section>;
}
