import { requireUser } from "@/lib/auth/require-user";
import { getBalloonRecencyStateForUser } from "@/lib/balloon-recency-service";
import { addBalloonProficiencyEvidence,deleteBalloonProficiencyEvidence } from "@/app/(protected)/credentials/balloon-actions";
import type { RecencyEvaluation,RecencyRequirement } from "@/lib/recency-engine";
import { PendingActionButton } from "@/components/pending-action-button";
import { PendingActionLabel } from "@/components/pending-action-label";

const statusClass=(status:RecencyEvaluation["status"])=>status==="current"?"status-on":status==="attention"?"status-warning":"status-off";
const requirementValue=(item:RecencyRequirement)=>item.unit==="hours"?`${item.current.toFixed(item.current%1?1:0)} / ${item.target} h`:`${Math.round(item.current)} / ${Math.round(item.target)}`;
function EvaluationCard({item}:{item:RecencyEvaluation}){return <article className="spl-recency-card"><header><div><span>{item.code}</span><strong>{item.title}</strong><small>{item.windowLabel}</small></div><b className={statusClass(item.status)}>{item.badge||item.status.toUpperCase()}</b></header><p>{item.summary}</p><div className="spl-requirements">{item.requirements.map(requirement=><div key={requirement.id} className={requirement.met?"met":"missing"}><span>{requirement.label}</span><strong>{requirementValue(requirement)}</strong></div>)}</div>{item.note?<small className="spl-recency-note">{item.note}</small>:null}{item.meta?.hotAirGroup?<small className="spl-recency-note">Current hot-air group evidence: {String(item.meta.hotAirGroup)}</small>:null}</article>}
export async function BalloonRecencyPanel(){
  const{userId}=await requireUser();const state=await getBalloonRecencyStateForUser(userId);if(!state)return null;const currentCards=state.anchor?[state.anchor,...state.additional]:[];
  return <section className="panel spl-recency-panel"><div className="section-heading"><div><p className="eyebrow">PART-BFCL · BALLOON</p><h2>BPL recency</h2><p className="muted">BFCL.160 flying-privilege recency by balloon class. One held class satisfies the base route; each additional held class requires its own experience.</p></div><span>{state.heldClasses.length}</span></div>
    {!state.hasBpl?<div className="flight-empty-state"><h3>Add your BPL first</h3><p>Balloon flights are present, but FlyTally will not infer a licence privilege from aircraft or flight history.</p></div>:null}
    {state.hasBpl&&!state.heldClasses.length?<div className="flight-empty-state"><h3>Record BPL class privileges</h3><p>Under <b>Licences & ratings</b>, add the balloon classes actually held: <b>Hot-air balloon</b>, <b>Gas balloon</b>, <b>Hot-air airship</b> or <b>Mixed balloon</b>.</p></div>:null}
    {state.anchor?<><h3 className="spl-recency-group-title">Current BFCL.160 route</h3><div className="spl-recency-grid">{currentCards.map(item=><EvaluationCard key={item.id} item={item}/>)}</div></>:state.heldClasses.length?<><h3 className="spl-recency-group-title">Base-class candidates</h3><p className="spl-recency-setup-note">No complete multi-class route is currently satisfied.</p><div className="spl-recency-grid">{state.candidates.map(item=><EvaluationCard key={item.evaluation.id} item={item.evaluation}/>)}</div>{state.additional.length?<><h3 className="spl-recency-group-title">Additional-class experience</h3><div className="spl-recency-grid">{state.additional.map(item=><EvaluationCard key={item.id} item={item}/>)}</div></>:null}</>:null}
    {state.tethered?<><h3 className="spl-recency-group-title">Tethered hot-air privilege</h3><div className="spl-recency-grid"><EvaluationCard item={state.tethered}/></div></>:state.hasBpl&&state.heldClasses.includes("HOT_AIR_BALLOON")?<p className="spl-recency-setup-note">BFCL.200 tethered recency is shown only when a tethered hot-air balloon rating is recorded as a BPL qualification. FlyTally does not infer the rating from flight history.</p>:null}
    {state.hasBpl&&state.heldClasses.length?<details className="spl-evidence"><summary>FE(B) proficiency-check evidence</summary><div className="spl-evidence-body"><p className="muted">Record only signed proficiency-check evidence.</p><form action={addBalloonProficiencyEvidence} className="form-grid settings-grid"><label><span>Balloon class <span className="field-hint" aria-hidden="true">Required</span></span><select name="balloon_class" required><option value="">Select</option>{state.heldClasses.map(value=><option value={value} key={value}>{state.classLabels[value]}</option>)}</select></label><label>Hot-air group<select name="balloon_group" defaultValue=""><option value="">Not applicable / select for hot-air</option><option>A</option><option>B</option><option>C</option><option>D</option></select></label><label><span>Date <span className="field-hint" aria-hidden="true">Required</span></span><input type="date" name="evidence_date" required/></label><label><span>Examiner <span className="field-hint" aria-hidden="true">Required</span></span><input name="signer" required/></label><label><span>Reference <span className="field-hint" aria-hidden="true">Required</span></span><input name="reference" required/></label><label className="wide">Notes<input name="note"/></label><div className="form-actions wide"><PendingActionButton className="primary-button" pendingLabel={<PendingActionLabel current="Adding…" reserve="Add evidence"/>}><PendingActionLabel current="Add evidence" reserve="Adding…"/></PendingActionButton></div></form>{state.evidence.length?<div className="spl-evidence-list">{state.evidence.map(item=><div key={item.id}><span><strong>{item.balloonClass.replaceAll("_"," ")}{item.balloonGroup?` · group ${item.balloonGroup}`:""} · {item.date}</strong><small>{item.signer} · {item.reference}{item.note?` · ${item.note}`:""}</small></span><form action={deleteBalloonProficiencyEvidence}><input type="hidden" name="id" value={item.id}/><PendingActionButton className="secondary-link" pendingLabel={<PendingActionLabel current="Removing…" reserve="Remove"/>}><PendingActionLabel current="Remove" reserve="Removing…"/></PendingActionButton></form></div>)}</div>:null}</div></details>:null}
  </section>;
}
