"use client";
import {useRef,useState} from "react";
import type {TrackPoint} from "@/lib/data/tracks";

type Props={departure:string;arrival:string;date:string;aircraftType:string;registration?:string;blockMinutes:number;landings:number;distanceKm:number;points:TrackPoint[]};
type PixelPoint={x:number;y:number;alt:number};
type Tile={z:number;x:number;y:number;px:number;py:number};
const MAP={x:55,y:420,w:970,h:690,pad:55};
const duration=(m:number)=>m?`${Math.floor(m/60)}:${String(m%60).padStart(2,"0")}`:"—";
const clampLat=(lat:number)=>Math.max(-85.0511,Math.min(85.0511,lat));
function world(lat:number,lon:number,z:number){const n=2**z,rad=clampLat(lat)*Math.PI/180;return{x:(lon+180)/360*n*256,y:(1-Math.asinh(Math.tan(rad))/Math.PI)/2*n*256}}
function mapLayout(points:TrackPoint[]){if(points.length<2)return{route:[] as PixelPoint[],tiles:[] as Tile[],zoom:5};const sample=points.filter((_,i)=>i===0||i===points.length-1||i%Math.max(1,Math.ceil(points.length/500))===0);let zoom=5;for(let z=12;z>=3;z--){const q=sample.map(p=>world(p.lat,p.lon,z)),xs=q.map(p=>p.x),ys=q.map(p=>p.y);if(Math.max(...xs)-Math.min(...xs)<=MAP.w-MAP.pad*2&&Math.max(...ys)-Math.min(...ys)<=MAP.h-MAP.pad*2){zoom=z;break}}
 const q=sample.map(p=>({...world(p.lat,p.lon,zoom),alt:Number(p.alt??0)})),minX=Math.min(...q.map(p=>p.x)),maxX=Math.max(...q.map(p=>p.x)),minY=Math.min(...q.map(p=>p.y)),maxY=Math.max(...q.map(p=>p.y)),cx=(minX+maxX)/2,cy=(minY+maxY)/2,left=cx-MAP.w/2,top=cy-MAP.h/2,route=q.map(p=>({x:MAP.x+p.x-left,y:MAP.y+p.y-top,alt:p.alt}));
 const x0=Math.floor(left/256),x1=Math.floor((left+MAP.w)/256),y0=Math.floor(top/256),y1=Math.floor((top+MAP.h)/256),tiles:Tile[]=[];for(let y=y0;y<=y1;y++)for(let x=x0;x<=x1;x++)tiles.push({z:zoom,x,y,px:MAP.x+x*256-left,py:MAP.y+y*256-top});return{route,tiles,zoom}}
function altitudePath(points:PixelPoint[]){if(points.length<2)return"";const vals=points.map(p=>p.alt).filter(Number.isFinite),min=Math.min(...vals),max=Math.max(...vals),range=Math.max(max-min,1),x0=95,y0=1205,w=890,h=145;return points.map((p,i)=>`${i?"L":"M"} ${x0+i/(points.length-1)*w} ${y0+h-(p.alt-min)/range*h}`).join(" ")}

export function FlightStoryCard(props:Props){const svgRef=useRef<SVGSVGElement>(null),[busy,setBusy]=useState(false),layout=mapLayout(props.points),route=layout.route.map(p=>`${p.x},${p.y}`).join(" "),profile=altitudePath(layout.route);async function save(){if(!svgRef.current)return;setBusy(true);try{let xml=new XMLSerializer().serializeToString(svgRef.current);xml=xml.replaceAll('href="/api/map-tile/',`href="${window.location.origin}/api/map-tile/`);const blob=new Blob([xml],{type:"image/svg+xml;charset=utf-8"}),url=URL.createObjectURL(blob),img=new Image();await new Promise<void>((ok,bad)=>{img.onload=()=>ok();img.onerror=bad;img.src=url});const c=document.createElement("canvas");c.width=1080;c.height=1920;const ctx=c.getContext("2d");if(!ctx)return;ctx.drawImage(img,0,0,1080,1920);URL.revokeObjectURL(url);const png=await new Promise<Blob|null>(r=>c.toBlob(r,"image/png",.96));if(!png)return;const file=new File([png],`FlyTally-${props.departure}-${props.arrival}.png`,{type:"image/png"});if(navigator.share&&navigator.canShare?.({files:[file]}))await navigator.share({files:[file],title:`${props.departure} → ${props.arrival}`});else{const a=document.createElement("a");a.href=URL.createObjectURL(png);a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}}finally{setBusy(false)}}
 return <div className="story-card-tool"><div className="story-preview"><svg ref={svgRef} viewBox="0 0 1080 1920" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient id="bg" x1="0" y1="0" x2="1" y2="1"><stop stopColor="#061724"/><stop offset="1" stopColor="#0d3852"/></linearGradient><linearGradient id="line" x1="0" y1="0" x2="1" y2="0"><stop stopColor="#6ee7ff"/><stop offset="1" stopColor="#fff"/></linearGradient><clipPath id="mapClip"><rect x={MAP.x} y={MAP.y} width={MAP.w} height={MAP.h} rx="12"/></clipPath></defs><rect width="1080" height="1920" fill="url(#bg)"/><text x="72" y="105" fill="#8eb6ca" fontSize="30" fontFamily="Arial" fontWeight="700" letterSpacing="5">FLYTALLY · FLIGHT</text><text x="72" y="245" fill="white" fontSize="88" fontFamily="Arial" fontWeight="800">{props.departure||"—"} → {props.arrival||"—"}</text><text x="72" y="310" fill="#b7d1de" fontSize="34" fontFamily="Arial">{[props.aircraftType,props.registration,props.date].filter(Boolean).join("  ·  ")}</text>
 <g clipPath="url(#mapClip)"><rect x={MAP.x} y={MAP.y} width={MAP.w} height={MAP.h} fill="#d8e2e6"/>{layout.tiles.map(t=><image key={`${t.z}-${t.x}-${t.y}`} href={`/api/map-tile/${t.z}/${t.x}/${t.y}`} x={t.px} y={t.py} width="256" height="256" preserveAspectRatio="none"/>)}<rect x={MAP.x} y={MAP.y} width={MAP.w} height={MAP.h} fill="#061724" opacity=".16"/>{layout.route.length>1&&<><polyline points={route} fill="none" stroke="#061724" strokeWidth="18" opacity=".58" strokeLinecap="round" strokeLinejoin="round"/><polyline points={route} fill="none" stroke="url(#line)" strokeWidth="10" strokeLinecap="round" strokeLinejoin="round"/><circle cx={layout.route[0].x} cy={layout.route[0].y} r="18" fill="#6ee7ff" stroke="#061724" strokeWidth="5"/><circle cx={layout.route.at(-1)!.x} cy={layout.route.at(-1)!.y} r="18" fill="#fff" stroke="#061724" strokeWidth="5"/></>}</g><rect x={MAP.x} y={MAP.y} width={MAP.w} height={MAP.h} rx="12" fill="none" stroke="#25536a" strokeWidth="3"/><text x="75" y="1090" fill="#fff" fontSize="19" fontFamily="Arial" opacity=".82">© OpenStreetMap contributors · GPS track</text>
 {profile&&<><path d={`${profile} L 985 1350 L 95 1350 Z`} fill="#3dd9df" opacity=".12"/><path d={profile} fill="none" stroke="#77e6f1" strokeWidth="5" strokeLinejoin="round"/><text x="95" y="1390" fill="#739caf" fontSize="22" fontFamily="Arial">RECORDED ALTITUDE PROFILE</text></>}
 <text x="72" y="1490" fill="#8eb6ca" fontSize="28" fontFamily="Arial" fontWeight="700">FLIGHT TIME</text><text x="72" y="1570" fill="white" fontSize="70" fontFamily="Arial" fontWeight="800">{duration(props.blockMinutes)}</text><text x="405" y="1490" fill="#8eb6ca" fontSize="28" fontFamily="Arial" fontWeight="700">DISTANCE</text><text x="405" y="1570" fill="white" fontSize="70" fontFamily="Arial" fontWeight="800">{props.distanceKm?`${Math.round(props.distanceKm/1.852)} NM`:"—"}</text><text x="785" y="1490" fill="#8eb6ca" fontSize="28" fontFamily="Arial" fontWeight="700">LANDINGS</text><text x="785" y="1570" fill="white" fontSize="70" fontFamily="Arial" fontWeight="800">{props.landings}</text><line x1="72" y1="1690" x2="1008" y2="1690" stroke="#31586c"/><text x="72" y="1770" fill="white" fontSize="38" fontFamily="Arial" fontWeight="700">Logged with FlyTally</text><text x="72" y="1830" fill="#8eb6ca" fontSize="27" fontFamily="Arial">A private pilot logbook · shared by the pilot</text></svg></div><button type="button" className="primary-button" onClick={save} disabled={busy}>{busy?"Preparing…":"Share Story · 1080×1920"}</button></div>}
