"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import L from "leaflet";
import type { MapTrack, TrackPoint } from "@/lib/data/tracks";
import { addFlyTallyBasemap,installResponsiveMap } from "@/components/leaflet-mobile";
import { mapThemePalette,useResolvedTheme } from "@/components/theme-runtime";

type IndexedPoint = TrackPoint & { track: number };
type Sample = TrackPoint & { distance: number; speed: number; bearing: number; track: number };
type ScenePoint={x:number;y:number;groundY:number};
const rad=Math.PI/180,MAX_SANITY_SPEED_KMH=2500;
const AIRCRAFT_MARKER_SVG='<svg class="aircraft-marker-svg" viewBox="0 0 40 40" width="34" height="34" aria-hidden="true" xmlns="http://www.w3.org/2000/svg"><circle cx="20" cy="20" r="18" fill="#082b45" stroke="rgba(255,255,255,.9)" stroke-width="1.5"/><path d="M20 5.5c1.15 0 1.8 1.2 2.05 3.15l1.05 8.15 10.15 5.4v3.15l-10.05-2.7-.45 7.2 3.45 2.55v2.1L20 32.85l-6.2 1.65v-2.1l3.45-2.55-.45-7.2-10.05 2.7V22.2l10.15-5.4 1.05-8.15C18.2 6.7 18.85 5.5 20 5.5Z" fill="white"/></svg>';
function leg(a:TrackPoint,b:TrackPoint){const dLat=(b.lat-a.lat)*rad,dLon=(b.lon-a.lon)*rad,q=Math.sin(dLat/2)**2+Math.cos(a.lat*rad)*Math.cos(b.lat*rad)*Math.sin(dLon/2)**2;return 12742.0176*Math.asin(Math.sqrt(q))}
function bearing(a:TrackPoint,b:TrackPoint){const y=Math.sin((b.lon-a.lon)*rad)*Math.cos(b.lat*rad),x=Math.cos(a.lat*rad)*Math.sin(b.lat*rad)-Math.sin(a.lat*rad)*Math.cos(b.lat*rad)*Math.cos((b.lon-a.lon)*rad);return(Math.atan2(y,x)/rad+360)%360}
function elapsed(a?:string,b?:string){if(!a||!b)return 0;const ms=Date.parse(b)-Date.parse(a);return Number.isFinite(ms)&&ms>0?ms/3600000:0}
function path(values:number[],width:number,height:number){const finite=values.filter(Number.isFinite),lo=Math.min(...finite,0),hi=Math.max(...finite,1),range=hi-lo||1;return values.map((v,i)=>`${i/Math.max(1,values.length-1)*width},${height-(v-lo)/range*height}`).join(" ")}
function median(values:number[]){const sorted=values.filter(Number.isFinite).sort((a,b)=>a-b);if(!sorted.length)return 0;const middle=Math.floor(sorted.length/2);return sorted.length%2?sorted[middle]:(sorted[middle-1]+sorted[middle])/2}
function windowedSpeed(points:IndexedPoint[],index:number,radius=2){const track=points[index]?.track;let start=index,end=index;for(let step=1;step<=radius;step++)if(points[index-step]?.track===track)start=index-step;else break;for(let step=1;step<=radius;step++)if(points[index+step]?.track===track)end=index+step;else break;if(end===start)return 0;const hours=elapsed(points[start]?.time,points[end]?.time);if(!hours)return 0;let distance=0;for(let i=start+1;i<=end;i++)if(points[i-1]?.track===track&&points[i]?.track===track)distance+=leg(points[i-1],points[i]);const speed=distance/hours;return Number.isFinite(speed)&&speed>=0?speed:0}
function smoothTrackSpeeds(points:IndexedPoint[],raw:number[]){const baselines=new Map<number,number>();for(const point of points){if(baselines.has(point.track))continue;baselines.set(point.track,median(raw.filter((v,i)=>points[i]?.track===point.track&&v>=5&&v<=MAX_SANITY_SPEED_KMH)))}const cleaned=raw.map((value,index)=>{const track=points[index]?.track,baseline=baselines.get(track)??0;if(!Number.isFinite(value)||value<0)return 0;if(value>MAX_SANITY_SPEED_KMH)return baseline;const neighbors:number[]=[];for(let i=Math.max(0,index-3);i<=Math.min(raw.length-1,index+3);i++)if(i!==index&&points[i]?.track===track&&Number.isFinite(raw[i])&&raw[i]>=0&&raw[i]<=MAX_SANITY_SPEED_KMH)neighbors.push(raw[i]);const reference=median(neighbors)||baseline;return reference>0&&value>Math.max(reference*1.9,reference+140)?reference:value});const pass=cleaned.map((value,index)=>{const window:number[]=[];for(let i=Math.max(0,index-2);i<=Math.min(cleaned.length-1,index+2);i++)if(points[i]?.track===points[index]?.track)window.push(cleaned[i]);return window.length>=3?median(window):value});return pass.map((value,index)=>{let sum=0,weight=0;for(let offset=-3;offset<=3;offset++){const i=index+offset;if(points[i]?.track!==points[index]?.track)continue;const w=4-Math.abs(offset);sum+=pass[i]*w;weight+=w}return weight?Math.max(0,sum/weight):Math.max(0,value)})}
function scene(samples:Sample[]):ScenePoint[]{if(!samples.length)return[];const lats=samples.map(p=>p.lat),lons=samples.map(p=>p.lon),alts=samples.map(p=>Number(p.alt??0));const minLat=Math.min(...lats),maxLat=Math.max(...lats),minLon=Math.min(...lons),maxLon=Math.max(...lons),minAlt=Math.min(...alts,0),maxAlt=Math.max(...alts,1),latR=maxLat-minLat||1,lonR=maxLon-minLon||1,altR=maxAlt-minAlt||1;return samples.map((p,i)=>{const nx=(p.lon-minLon)/lonR-.5,nz=(p.lat-minLat)/latR-.5,alt=(Number(p.alt??0)-minAlt)/altR;const depth=nz*.42,x=500+nx*660-depth*260,y=315+depth*250-alt*205;return{x,y,groundY:315+depth*250}})}

export function FlightTrackPlayer({tracks}:{tracks:MapTrack[]}){
 const theme=useResolvedTheme(),palette=mapThemePalette(theme),points=useMemo<IndexedPoint[]>(()=>tracks.flatMap((t,track)=>t.points.map(p=>({...p,track}))),[tracks]);
 const samples=useMemo<Sample[]>(()=>{const speeds=smoothTrackSpeeds(points,points.map((_,i)=>windowedSpeed(points,i,2)));let distance=0;return points.map((p,i)=>{const candidate=points[i-1],prev=candidate?.track===p.track?candidate:undefined,next=points[i+1]?.track===p.track?points[i+1]:undefined;if(prev)distance+=leg(prev,p);return{...p,distance,speed:speeds[i]??0,bearing:prev?bearing(prev,p):next?bearing(p,next):0}})},[points]);
 const scenePoints=useMemo(()=>scene(samples),[samples]),target=useRef<HTMLDivElement>(null),markerRef=useRef<L.Marker|null>(null);
 const [cursor,setCursor]=useState(0),[playing,setPlaying]=useState(false),[rate,setRate]=useState(1),[view,setView]=useState<"map"|"3d">("map");
 const max=Math.max(0,samples.length-1),index=Math.min(max,Math.floor(cursor)),fraction=cursor-index,a=samples[index],candidate=samples[Math.min(max,index+1)]??a,b=candidate?.track===a?.track?candidate:a;
 const current=a&&b?{...a,lat:a.lat+(b.lat-a.lat)*fraction,lon:a.lon+(b.lon-a.lon)*fraction,alt:Number(a.alt??0)+(Number(b.alt??a.alt??0)-Number(a.alt??0))*fraction,speed:a.speed+(b.speed-a.speed)*fraction,bearing:b.bearing||a.bearing,distance:a.distance+(b.distance-a.distance)*fraction}:null;
 const sa=scenePoints[index],sb=scenePoints[Math.min(max,index+1)]??sa,sceneCurrent=sa&&sb?{x:sa.x+(sb.x-sa.x)*fraction,y:sa.y+(sb.y-sa.y)*fraction,groundY:sa.groundY+(sb.groundY-sa.groundY)*fraction}:null;
 useEffect(()=>{if(!target.current||!samples.length)return;const map=L.map(target.current,{preferCanvas:true,zoomControl:true});addFlyTallyBasemap(map);const renderer=L.canvas({padding:.3}),bounds=L.latLngBounds([]);tracks.forEach((track,i)=>{const ll=track.points.map(p=>L.latLng(p.lat,p.lon)),color=i%2?palette.route:palette.routeAlt;ll.forEach(p=>bounds.extend(p));L.polyline(ll,{color,weight:3,opacity:.92,renderer}).addTo(map)});const icon=L.divIcon({className:"aircraft-marker",html:AIRCRAFT_MARKER_SVG,iconSize:[34,34],iconAnchor:[17,17]});markerRef.current=L.marker([samples[0].lat,samples[0].lon],{icon,zIndexOffset:1000}).addTo(map);map.fitBounds(bounds,{padding:[25,25],maxZoom:13});const cleanup=installResponsiveMap(map,target.current);return()=>{cleanup();map.remove();markerRef.current=null}},[samples,tracks,theme,palette.route,palette.routeAlt]);
 useEffect(()=>{if(!current||!markerRef.current)return;markerRef.current.setLatLng([current.lat,current.lon]);const node=markerRef.current.getElement()?.querySelector(".aircraft-marker-svg") as SVGElement|null;if(node){node.style.transformOrigin="50% 50%";node.style.transform=`rotate(${current.bearing}deg)`}},[current]);
 useEffect(()=>{if(!playing||max<1)return;let frame=0,last=performance.now();const tick=(now:number)=>{const dt=Math.min(100,now-last);last=now;setCursor(v=>{const next=v+dt/1000*rate*Math.max(1,max/90);if(next>=max){setPlaying(false);return max}return next});frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)},[playing,max,rate]);
 if(samples.length<2)return null;const w=1000,h=150,alts=samples.map(p=>Number(p.alt??0)),speeds=samples.map(p=>p.speed),x=cursor/max*w,route=scenePoints.map(p=>`${p.x},${p.y}`).join(" "),ground=scenePoints.map(p=>`${p.x},${p.groundY}`).join(" ");
 return <section className="track-player-suite">
  <div style={{display:"flex",justifyContent:"flex-end",marginBottom:8}}><div className="segment-control" style={{margin:0}}><button className={view==="map"?"active":""} onClick={()=>setView("map")}>2D map</button><button className={view==="3d"?"active":""} onClick={()=>setView("3d")}>3D flight path</button></div></div>
  <div style={{display:view==="map"?"block":"none"}}><div ref={target} className="track-map responsive-map player-responsive-map" style={{"--map-height":"500px"} as React.CSSProperties} aria-label="Synchronized GPS track map"/></div>
  {view==="3d"&&<div className="panel" style={{padding:0,overflow:"hidden",minHeight:500,background:"radial-gradient(circle at 50% 15%, rgba(56,189,248,.16), transparent 38%), linear-gradient(180deg,#071525,#0b1727)"}}><svg viewBox="0 0 1000 500" width="100%" height="500" role="img" aria-label="Perspective three dimensional flight path using GPS altitude"><defs><linearGradient id="floor" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="rgba(52,211,153,.10)"/><stop offset="1" stopColor="rgba(52,211,153,.01)"/></linearGradient></defs><path d="M80 380 L500 245 L920 380 L500 495 Z" fill="url(#floor)" stroke="rgba(142,163,187,.18)"/><polyline points={ground} fill="none" stroke="rgba(142,163,187,.22)" strokeWidth="2" strokeDasharray="6 8"/><polyline points={route} fill="none" stroke="var(--accent2)" strokeWidth="6" strokeLinecap="round" strokeLinejoin="round"/><polyline points={route} fill="none" stroke="rgba(255,255,255,.35)" strokeWidth="1.5"/>{sceneCurrent&&<><line x1={sceneCurrent.x} y1={sceneCurrent.y} x2={sceneCurrent.x} y2={sceneCurrent.groundY} stroke="var(--accent)" strokeDasharray="5 6" opacity=".7"/><g transform={`translate(${sceneCurrent.x} ${sceneCurrent.y}) rotate(${(current?.bearing??0)+45})`}><circle r="17" fill="#082b45" stroke="white" strokeWidth="1.5"/><path d="M0 -12 L3 -2 L13 3 L13 6 L3 4 L2 11 L5 14 L2 15 L0 13 L-2 15 L-5 14 L-2 11 L-3 4 L-13 6 L-13 3 L-3 -2 Z" fill="white"/></g></>}<text x="28" y="38" fill="var(--muted)" fontSize="18">GPS altitude perspective · visualisation, not terrain clearance</text></svg></div>}
  <div className="panel track-profile"><div className="section-heading"><div><p className="eyebrow">GPS PLAYER</p><h2>Altitude, speed and position</h2></div><div className="track-stats"><span>{samples.at(-1)?.distance.toFixed(1)} km</span><span>{samples.length} points</span><span>max {Math.round(Math.max(...alts)*3.28084)} ft</span><span>max {Math.round(Math.max(...speeds))} km/h</span></div></div><div className="combined-profile-chart"><div className="profile-legend"><span><i className="alt-line"/>Altitude</span><span><i className="speed-line"/>Speed</span></div><svg viewBox={`0 0 ${w} ${h}`} preserveAspectRatio="none"><polyline points={path(alts,w,h)} fill="none" stroke="var(--chart-primary)" strokeWidth="3" vectorEffect="non-scaling-stroke"/><polyline points={path(speeds,w,h)} fill="none" stroke="var(--chart-secondary)" strokeWidth="3" vectorEffect="non-scaling-stroke"/><line x1={x} x2={x} y1="0" y2={h} stroke="var(--chart-cursor)" strokeWidth="2" vectorEffect="non-scaling-stroke"/></svg></div><div className="player-controls"><button type="button" className="play-button" onClick={()=>{if(cursor>=max)setCursor(0);setPlaying(v=>!v)}}>{playing?'❚❚':'▶'}</button><input aria-label="Track position" type="range" min="0" max={max} step="0.01" value={cursor} onChange={e=>{setPlaying(false);setCursor(Number(e.target.value))}}/><select aria-label="Playback speed" value={rate} onChange={e=>setRate(Number(e.target.value))}><option value="1">1×</option><option value="2">2×</option><option value="5">5×</option><option value="10">10×</option></select><div><strong>{current?.distance.toFixed(1)} km</strong><small>{current?.time?new Date(current.time).toLocaleTimeString("en-GB",{hour:"2-digit",minute:"2-digit",second:"2-digit"}):`point ${index+1}`}</small><small>{Math.round(Number(current?.alt||0)*3.28084)} ft · {Math.round(current?.speed||0)} km/h</small></div></div></div>
 </section>;
}
