"use client";
import {useRef,useState} from "react";
import type {TrackPoint} from "@/lib/data/tracks";

type Props={departure:string;arrival:string;date:string;aircraftType:string;registration?:string;blockMinutes:number;landings:number;distanceKm:number;points:TrackPoint[]};
type PixelPoint={x:number;y:number;alt:number;time?:string;speed?:number};
type Tile={z:number;x:number;y:number;px:number;py:number};
const MAP={x:55,y:350,w:970,h:690,pad:55};
const duration=(m:number)=>m?`${Math.floor(m/60)}:${String(m%60).padStart(2,"0")}`:"—";
const clampLat=(lat:number)=>Math.max(-85.0511,Math.min(85.0511,lat));
function world(lat:number,lon:number,z:number){const n=2**z,rad=clampLat(lat)*Math.PI/180;return{x:(lon+180)/360*n*256,y:(1-Math.asinh(Math.tan(rad))/Math.PI)/2*n*256}}
function distanceNm(a:TrackPoint,b:TrackPoint){const r=3440.065,p=Math.PI/180,dLat=(b.lat-a.lat)*p,dLon=(b.lon-a.lon)*p,q=Math.sin(dLat/2)**2+Math.cos(a.lat*p)*Math.cos(b.lat*p)*Math.sin(dLon/2)**2;return 2*r*Math.asin(Math.sqrt(q))}
function pointSpeeds(points:TrackPoint[]){return points.map((p,i)=>{if(!i||!p.time)return undefined;const prev=points[i-1];if(!prev?.time)return undefined;const dt=(Date.parse(p.time)-Date.parse(prev.time))/3600000;if(!Number.isFinite(dt)||dt<=0||dt>.25)return undefined;const kt=distanceNm(prev,p)/dt;return kt>=0&&kt<500?kt:undefined})}
function mapLayout(points:TrackPoint[]){if(points.length<2)return{route:[] as PixelPoint[],tiles:[] as Tile[],zoom:5};const stride=Math.max(1,Math.ceil(points.length/500)),sample=points.filter((_,i)=>i===0||i===points.length-1||i%stride===0),speeds=pointSpeeds(sample);let zoom=5;for(let z=12;z>=3;z--){const q=sample.map(p=>world(p.lat,p.lon,z)),xs=q.map(p=>p.x),ys=q.map(p=>p.y);if(Math.max(...xs)-Math.min(...xs)<=MAP.w-MAP.pad*2&&Math.max(...ys)-Math.min(...ys)<=MAP.h-MAP.pad*2){zoom=z;break}}
 const q=sample.map((p,i)=>({...world(p.lat,p.lon,zoom),alt:Number(p.alt??0),time:p.time,speed:speeds[i]})),minX=Math.min(...q.map(p=>p.x)),maxX=Math.max(...q.map(p=>p.x)),minY=Math.min(...q.map(p=>p.y)),maxY=Math.max(...q.map(p=>p.y)),cx=(minX+maxX)/2,cy=(minY+maxY)/2,left=cx-MAP.w/2,top=cy-MAP.h/2,route=q.map(p=>({x:MAP.x+p.x-left,y:MAP.y+p.y-top,alt:p.alt,time:p.time,speed:p.speed}));
 const x0=Math.floor(left/256),x1=Math.floor((left+MAP.w)/256),y0=Math.floor(top/256),y1=Math.floor((top+MAP.h)/256),tiles:Tile[]=[];for(let y=y0;y<=y1;y++)for(let x=x0;x<=x1;x++)tiles.push({z:zoom,x,y,px:MAP.x+x*256-left,py:MAP.y+y*256-top});return{route,tiles,zoom}}
function chartPath(points:PixelPoint[],key:"alt"|"speed",x0=95,y0=1120,w=890,h=245){const values=points.map(p=>key==="alt"?p.alt:p.speed).filter((v):v is number=>Number.isFinite(v));if(values.length<2)return"";const max=key==="alt"?Math.max(...values,1000):Math.max(...values,50),valid=points.map((p,i)=>({v:key==="alt"?p.alt:p.speed,x:x0+i/Math.max(points.length-1,1)*w})).filter((p):p is {v:number;x:number}=>Number.isFinite(p.v));return valid.map((p,i)=>`${i?"L":"M"} ${p.x} ${y0+h-p.v/max*h}`).join(" ")}

export function FlightStoryCard(props:Props){const svgRef=useRef<SVGSVGElement>(null),[busy,setBusy]=useState(false),layout=mapLayout(props.points),route=layout.route.map(p=>`${p.x},${p.y}`).join(" "),altPath=chartPath(layout.route,"alt"),speedPath=chartPath(layout.route,"speed"),avgKt=props.blockMinutes&&props.distanceKm?Math.round((props.distanceKm/1.852)/(props.blockMinutes/60)):0;async function save(){if(!svgRef.current)return;setBusy(true);try{let xml=new XMLSerializer().serializeToString(svgRef.current);xml=xml.replaceAll('href="/api/map-tile/',`href="${window.location.origin}/api/map-tile/`);const blob=new Blob([xml],{type:"image/svg+xml;charset=utf-8"}),url=URL.createObjectURL(blob),img=new Image();await new Promise<void>((ok,bad)=>{img.onload=()=>ok();img.onerror=bad;img.src=url});const c=document.createElement("canvas");c.width=1080;c.height=1920;const ctx=c.getContext("2d");if(!ctx)return;ctx.drawImage(img,0,0,1080,1920);URL.revokeObjectURL(url);const png=await new Promise<Blob|null>(r=>c.toBlob(r,"image/png",.96));if(!png)return;const file=new File([png],`FlyTally-${props.departure}-${props.arrival}.png`,{type:"image/png"});if(navigator.share&&navigator.canShare?.({files:[file]}))await navigator.share({files:[file],title:`${props.departure} → ${props.arrival}`});else{const a=document.createElement("a");a.href=URL.createObjectURL(png);a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}}finally{setBusy(false)}}
 return <div className="story-card-tool"><div className="story-preview"><svg ref={svgRef} viewBox="0 0 1080 1920" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient id="bg" x1="0" y1="0" x2="1" y2="1"><stop stopColor="#04131f"/><stop offset=".58" stopColor="#071d2c"/><stop offset="1" stopColor="#0b3147"/></linearGradient><linearGradient id="routeLine" x1="0" y1="0" x2="1" y2="1"><stop stopColor="#63e6ff"/><stop offset="1" stopColor="#b9f6ff"/></linearGradient><clipPath id="mapClip"><rect x={MAP.x} y={MAP.y} width={MAP.w} height={MAP.h} rx="22"/></clipPath></defs><rect width="1080" height="1920" rx="38" fill="url(#bg)"/><rect x="28" y="28" width="1024" height="1864" rx="38" fill="none" stroke="#17445a" strokeWidth="2"/>
 <text x="72" y="100" fill="#8eb6ca" fontSize="27" fontFamily="Arial" fontWeight="700" letterSpacing="6">FLIGHT</text><text x="72" y="220" fill="white" fontSize="82" fontFamily="Arial" fontWeight="800">{props.departure||"—"} → {props.arrival||"—"}</text><text x="72" y="282" fill="#abc9d7" fontSize="32" fontFamily="Arial">{[props.aircraftType,props.registration,props.date].filter(Boolean).join("  ·  ")}</text>
 <g clipPath="url(#mapClip)"><rect x={MAP.x} y={MAP.y} width={MAP.w} height={MAP.h} fill="#071923"/>{layout.tiles.map(t=><image key={`${t.z}-${t.x}-${t.y}`} href={`/api/map-tile/${t.z}/${t.x}/${t.y}`} x={t.px} y={t.py} width="256" height="256" preserveAspectRatio="none"/>)}<rect x={MAP.x} y={MAP.y} width={MAP.w} height={MAP.h} fill="#03131e" opacity=".58"/>{layout.route.length>1&&<><polyline points={route} fill="none" stroke="#00101a" strokeWidth="18" opacity=".8" strokeLinecap="round" strokeLinejoin="round"/><polyline points={route} fill="none" stroke="url(#routeLine)" strokeWidth="9" strokeLinecap="round" strokeLinejoin="round"/><circle cx={layout.route[0].x} cy={layout.route[0].y} r="17" fill="#fff" stroke="#061724" strokeWidth="5"/><circle cx={layout.route.at(-1)!.x} cy={layout.route.at(-1)!.y} r="17" fill="#58dcf4" stroke="#061724" strokeWidth="5"/></>}</g><rect x={MAP.x} y={MAP.y} width={MAP.w} height={MAP.h} rx="22" fill="none" stroke="#24546b" strokeWidth="3"/><text x="72" y="1025" fill="#b8ced8" fontSize="17" fontFamily="Arial" opacity=".75">© OpenStreetMap contributors</text>
 <line x1="95" y1="1120" x2="95" y2="1365" stroke="#24485a"/><line x1="95" y1="1365" x2="985" y2="1365" stroke="#24485a"/>{[0,1,2,3].map(i=><line key={i} x1="95" y1={1120+i*61.25} x2="985" y2={1120+i*61.25} stroke="#17384a"/>)}{altPath&&<path d={altPath} fill="none" stroke="#59dcff" strokeWidth="5" strokeLinejoin="round"/>}{speedPath&&<path d={speedPath} fill="none" stroke="#ffb04a" strokeWidth="4" strokeLinejoin="round"/>}<text x="95" y="1090" fill="#59dcff" fontSize="24" fontFamily="Arial" fontWeight="700">ALTITUDE</text><text x="985" y="1090" textAnchor="end" fill="#ffb04a" fontSize="24" fontFamily="Arial" fontWeight="700">SPEED</text><line x1="95" y1="1408" x2="145" y2="1408" stroke="#59dcff" strokeWidth="5"/><text x="158" y="1416" fill="#9ebdca" fontSize="21" fontFamily="Arial">Altitude</text><line x1="310" y1="1408" x2="360" y2="1408" stroke="#ffb04a" strokeWidth="5"/><text x="373" y="1416" fill="#9ebdca" fontSize="21" fontFamily="Arial">GPS speed</text>
 <text x="72" y="1510" fill="#8eb6ca" fontSize="25" fontFamily="Arial" fontWeight="700">FLIGHT TIME</text><text x="72" y="1585" fill="white" fontSize="65" fontFamily="Arial" fontWeight="800">{duration(props.blockMinutes)}</text><text x="405" y="1510" fill="#8eb6ca" fontSize="25" fontFamily="Arial" fontWeight="700">DISTANCE</text><text x="405" y="1585" fill="white" fontSize="65" fontFamily="Arial" fontWeight="800">{props.distanceKm?`${Math.round(props.distanceKm/1.852)} NM`:"—"}</text><text x="760" y="1510" fill="#8eb6ca" fontSize="25" fontFamily="Arial" fontWeight="700">AVERAGE SPEED</text><text x="760" y="1585" fill="white" fontSize="65" fontFamily="Arial" fontWeight="800">{avgKt?`${avgKt} kt`:"—"}</text><line x1="72" y1="1710" x2="1008" y2="1710" stroke="#24485a"/><text x="1008" y="1818" textAnchor="end" fill="#779bab" fontSize="22" fontFamily="Arial">FlyTally</text></svg></div><button type="button" className="primary-button" onClick={save} disabled={busy}>{busy?"Preparing…":"Share Story · 1080×1920"}</button></div>