"use client";

import { useActionState,useEffect,useMemo,useRef,useState } from "react";
import { useFormStatus } from "react-dom";
import Link from "next/link";
import type { AircraftOption } from "@/lib/data/aircraft";
import type { FlightRow } from "@/lib/data/flights";
import type { FlightActionState } from "@/app/(protected)/flights/actions";
import { BILLING,CLASSES,EVIDENCE,ROLES } from "@/lib/flight-input";
import { defaultEngineType,ENGINE_TYPES,formatEasaDuration,OPERATION_TYPES } from "@/lib/easa-logbook";
import { BILLING_SHARES,calculatedFlightPrice,parseBilling,serializeBilling } from "@/lib/billing";
import { normalizeChoice,normalizeRegistration,shouldApplyAircraftProfileDefaults } from "@/lib/flight-form-rules";
import { FLIGHT_PURPOSES,normalizeFlightPurposeCode } from "@/lib/flight-purpose";
import { useUnsavedFormGuard } from "@/components/use-unsaved-form-guard";

type Action=(state:FlightActionState,data:FormData)=>Promise<FlightActionState>;
type Initial=Partial<FlightRow>&Record<string,unknown>;
function addTime(value:string,minutes:number){if(!/^\d\d:\d\d$/.test(value))return"";const total=(Number(value.slice(0,2))*60+Number(value.slice(3))+minutes+1440)%1440;return`${String(Math.floor(total/60)).padStart(2,"0")}:${String(total%60).padStart(2,"0")}`}
function minutesBetween(start:string,end:string){if(!/^\d\d:\d\d$/.test(start)||!/^\d\d:\d\d$/.test(end))return 0;const a=Number(start.slice(0,2))*60+Number(start.slice(3)),b=Number(end.slice(0,2))*60+Number(end.slice(3));return(b-a+1440)%1440}
function durationLabel(minutes:number){return minutes?`${Math.floor(minutes/60)}:${String(minutes%60).padStart(2,"0")}`:"—"}
const roleLabel=(value:string)=>value==="INSTRUKTOR"?"INSTRUCTOR":value;
const validBilling=(value:string)=>/^(BLOCK|AIR)(?:\/\d+)?$/.test(value);
function Submit({another=false}:{another?:boolean}){const{pending}=useFormStatus();return <button className={another?"secondary-link":"primary-button"} name="intent" value={another?"another":"save"} disabled={pending}>{pending?"Saving…":another?"Save and add another":"Save flight"}</button>}

export function FlightForm({action,aircraft,initial={},routes=[],instructors=[]}:{action:Action;aircraft:AircraftOption[];initial?:Initial;routes?:Array<{departure:string;arrival:string}>;instructors?:Array<{name:string}>}){
  const[state,formAction]=useActionState(action,{}),field=(name:string,fallback="")=>String(initial[name]??fallback),editing=Boolean(initial.id);
  const{dirty,markDirty,beginSubmit}=useUnsavedFormGuard(),errorRef=useRef<HTMLParagraphElement>(null);
  const normalizedAircraft=useMemo(()=>aircraft.map(item=>({...item,registration:normalizeRegistration(item.registration)})),[aircraft]);
  const initialRegistration=normalizeRegistration(field("registration",editing?"":normalizedAircraft[0]?.registration||""));
  const[registration,setRegistration]=useState(initialRegistration),[date,setDate]=useState(field("date",new Date().toISOString().slice(0,10)));
  const selected=useMemo(()=>normalizedAircraft.find(x=>x.registration===registration),[normalizedAircraft,registration]);
  const registrationOptions=useMemo(()=>initialRegistration&&!normalizedAircraft.some(item=>item.registration===initialRegistration)?[{registration:initialRegistration} as AircraftOption,...normalizedAircraft]:normalizedAircraft,[initialRegistration,normalizedAircraft]);
  const storedEvidence=normalizeChoice(field("evidence"),EVIDENCE,""),storedClass=normalizeChoice(field("aircraft_class"),CLASSES,""),storedRole=normalizeChoice(field("role"),ROLES,""),storedPurpose=normalizeFlightPurposeCode(field("purpose_code"));
  const profileEvidence=normalizeChoice(selected?.evidence,EVIDENCE,"ULL"),profileClass=normalizeChoice(selected?.aircraft_class,CLASSES,"ULL"),profileRole=normalizeChoice(selected?.default_role==="INSTRUKTOR"?"INSTRUCTOR":selected?.default_role,ROLES,"PIC");
  const initialEvidence=editing?storedEvidence:(storedEvidence||profileEvidence),initialClass=editing?storedClass:(storedClass||profileClass),initialRole=editing?storedRole:(storedRole||profileRole);
  const storedBillingRaw=String(field("billing_basis")).trim().toUpperCase(),billingSource=editing?storedBillingRaw:(storedBillingRaw||String(selected?.billing_basis||"BLOCK")),initialBilling=parseBilling(billingSource),initialBillingBasis:""|"BLOCK"|"AIR"=editing&&!validBilling(storedBillingRaw)?"":initialBilling.basis;
  const[type,setType]=useState(editing?field("aircraft_type").trim():field("aircraft_type",selected?.aircraft_type||"").trim()),[aircraftClass,setClass]=useState<string>(initialClass),[evidence,setEvidence]=useState<string>(initialEvidence),[role,setRole]=useState<string>(initialRole),[billing,setBilling]=useState<""|"BLOCK"|"AIR">(initialBillingBasis),[billingShare,setBillingShare]=useState(initialBilling.share),[hourlyRate,setHourlyRate]=useState(Number(field("price_per_hour",String(selected?.price_per_hour||0)))||0);
  const[departure,setDeparture]=useState(field("departure")),[arrival,setArrival]=useState(field("arrival")),[off,setOff]=useState(field("off_block")),[takeoff,setTakeoff]=useState(field("takeoff")),[landing,setLanding]=useState(field("landing")),[on,setOn]=useState(field("on_block")),[duration,setDuration]=useState(60);
  const[operationType,setOperationType]=useState(normalizeChoice(field("operation_type"),OPERATION_TYPES,"SP")),[engineType,setEngineType]=useState(normalizeChoice(field("engine_type"),ENGINE_TYPES,defaultEngineType(initialClass||profileClass))),[landingsDay,setLandingsDay]=useState(Number(field("landings_day",field("starts","1")))||0),[landingsNight,setLandingsNight]=useState(Number(field("landings_night","0"))||0);
  const pickAircraft=(reg:string)=>{markDirty();const normalized=normalizeRegistration(reg);setRegistration(normalized);const a=normalizedAircraft.find(x=>x.registration===normalized);if(a&&shouldApplyAircraftProfileDefaults(editing,initialRegistration,normalized)){const nextBilling=parseBilling(a.billing_basis),nextClass=normalizeChoice(a.aircraft_class,CLASSES,"ULL"),nextEvidence=normalizeChoice(a.evidence,EVIDENCE,"ULL"),nextRole=normalizeChoice(a.default_role==="INSTRUKTOR"?"INSTRUCTOR":a.default_role,ROLES,"PIC");setType(a.aircraft_type||"");setClass(nextClass);setEngineType(defaultEngineType(nextClass));setEvidence(nextEvidence);setRole(nextRole);setBilling(nextBilling.basis);setBillingShare(nextBilling.share);setHourlyRate(Number(a.price_per_hour)||0)}};
  const fillTimes=()=>{markDirty();const start=off||new Date().toLocaleTimeString("en-GB",{hour:"2-digit",minute:"2-digit",timeZone:"UTC"});setOff(start);setTakeoff(addTime(start,5));setLanding(addTime(start,5+duration));setOn(addTime(start,10+duration))};
  const blockMinutes=minutesBetween(off,on),airMinutes=minutesBetween(takeoff,landing),billableMinutes=billing==="AIR"?airMinutes:billing==="BLOCK"?blockMinutes:0,billingValue=billing?serializeBilling(billing,billingShare):"",flightPrice=calculatedFlightPrice(hourlyRate,blockMinutes,airMinutes,billingValue),trainingRole=["DUAL","SPIC","PICUS","INSTRUCTOR","EXAMINER"].includes(role),pilotSectionOpen=trainingRole||role==="SAFETY PILOT",countersignatureRequired=["SPIC","PICUS"].includes(role);
  const roleGuidance=role==="DUAL"?"Choose a connected instructor when possible. They are recorded as PIC and will automatically receive a review/sign request after certification.":role==="SAFETY PILOT"?"Enter the actual PIC below. Safety Pilot time is kept for reference and is not added to creditable logbook totals.":["SPIC","PICUS"].includes(role)?"Choose the supervising PIC/FI when possible. A matching connected instructor will automatically receive the certified entry for review.":"";
  const missing=[!date&&"date",!registration&&"aircraft",!role&&"role",!evidence&&"logbook",!aircraftClass&&"class",!billing&&"billing"].filter(Boolean);useEffect(()=>{if(state.error){markDirty();errorRef.current?.focus()}},[state.error,markDirty]);
  return <form action={formAction} className="flight-form" onChangeCapture={markDirty} onSubmitCapture={beginSubmit}>
    {instructors.length?<datalist id="connected-instructors">{instructors.map((item,index)=><option value={item.name} key={`${item.name}-${index}`}/>)}</datalist>:null}
    <nav className="entry-progress" aria-label="Manual flight entry progress"><span className="complete">1 <b>Source</b></span><span className="active">2 <b>Details</b></span><span>3 <b>Review &amp; save</b></span></nav>
    <section className="entry-section entry-section-primary"><p className="section-kicker">Flight essentials</p><div className="form-grid essential-grid">
      <label>Date<input name="date" type="date" value={date} onChange={event=>setDate(event.target.value)} required/></label><label>Registration<select name="registration" value={registration} onChange={e=>pickAircraft(e.target.value)} required><option value="">Select</option>{registrationOptions.map(a=><option key={a.registration} value={a.registration}>{a.registration}</option>)}</select><small><Link href="/database">Manage aircraft</Link></small></label><label>Role<select name="role" value={role} onChange={e=>setRole(e.target.value)} required><option value="">Select role</option>{ROLES.map(x=><option key={x} value={x}>{roleLabel(x)}</option>)}</select>{roleGuidance?<small className="role-guidance">{roleGuidance}</small>:null}</label>
      <label>Departure<input name="departure" value={departure} onChange={e=>setDeparture(e.target.value.toUpperCase())} placeholder="LKLT" autoCapitalize="characters"/></label><label>Arrival<input name="arrival" value={arrival} onChange={e=>setArrival(e.target.value.toUpperCase())} placeholder="LKLT" autoCapitalize="characters"/></label><label>Off-block <span className="field-hint">UTC</span><input name="offBlock" type="time" value={off} onChange={e=>setOff(e.target.value)}/></label><label>Takeoff <span className="field-hint">UTC</span><input name="takeoff" type="time" value={takeoff} onChange={e=>setTakeoff(e.target.value)}/></label><label>Landing <span className="field-hint">UTC</span><input name="landing" type="time" value={landing} onChange={e=>setLanding(e.target.value)}/></label><label>On-block <span className="field-hint">UTC</span><input name="onBlock" type="time" value={on} onChange={e=>setOn(e.target.value)}/></label><label>Day landings<input name="landingsDay" type="number" min="0" max="99" value={landingsDay} onChange={event=>setLandingsDay(Number(event.target.value)||0)}/></label>
    </div></section>
    {!editing?<details className="quick-tools"><summary>Speed up entry</summary><div className="quick-tools-grid"><label>Flight duration (min)<input type="number" min="1" max="1440" value={duration} onChange={e=>setDuration(Number(e.target.value)||1)}/></label><button type="button" className="secondary-link" onClick={fillTimes}>Fill UTC times ±5 min</button><button type="button" className="secondary-link" onClick={()=>{markDirty();setDeparture(arrival);setArrival(departure)}}>Reverse route</button></div>{routes.length?<div className="route-chips"><small>Recent routes</small>{routes.slice(0,8).map((r,i)=><button type="button" key={`${r.departure}-${r.arrival}-${i}`} onClick={()=>{markDirty();setDeparture(r.departure);setArrival(r.arrival)}}>{r.departure}–{r.arrival}</button>)}</div>:null}</details>:null}
    <details className="entry-section" open={pilotSectionOpen}><summary><span>Pilot & training</span><small>{role}{field("instructor")?` · ${field("instructor")}`:""}</small></summary><div className="entry-section-body"><div className="form-grid secondary-entry-grid">
      {role==="DUAL"?<><input type="hidden" name="commander" value={field("commander")}/><label>Instructor / PIC<input name="instructor" list={instructors.length?"connected-instructors":undefined} defaultValue={field("instructor")} required={evidence==="EASA"}/><small>{instructors.length?"Select a connected instructor or enter a name manually.":"Required for a DUAL training record."}</small></label><label>Training purpose<select name="purposeCode" defaultValue={storedPurpose}>{FLIGHT_PURPOSES.map(item=><option key={item.code||"general"} value={item.code}>{item.label}</option>)}</select><small>Choose FCL.140.A here so LAPL recency does not depend on free-text wording.</small></label></>:<><label>{role==="SAFETY PILOT"?"Actual PIC":"Commander / PIC"}<input name="commander" defaultValue={field("commander")} required={evidence==="EASA"&&role==="SAFETY PILOT"}/></label><label>Instructor<input name="instructor" list={instructors.length?"connected-instructors":undefined} defaultValue={field("instructor")}/></label></>}
      <label className="wide">Task / exercise<input name="task" defaultValue={field("task")}/><small>Free-text exercise details remain available and are kept alongside the structured purpose.</small></label>
    </div></div></details>
    <details className="entry-section" open={evidence==="EASA"}><summary><span>Aircraft & EASA record</span><small>{evidence||"Select logbook"} · {operationType} · {engineType}</small></summary><div className="entry-section-body"><div className="form-grid secondary-entry-grid">
      <label>Logbook<select name="evidence" value={evidence} onChange={e=>setEvidence(e.target.value)} required><option value="">Select logbook</option>{EVIDENCE.map(x=><option key={x}>{x}</option>)}</select></label><label>Aircraft type<input name="aircraftType" value={type} onChange={e=>setType(e.target.value)}/></label><label>Class<select name="aircraftClass" value={aircraftClass} onChange={e=>{setClass(e.target.value);if(e.target.value)setEngineType(defaultEngineType(e.target.value))}} required><option value="">Select class</option>{CLASSES.map(x=><option key={x}>{x}</option>)}</select></label><label>Operation<select name="operationType" value={operationType} onChange={event=>setOperationType(event.target.value)}>{OPERATION_TYPES.map(value=><option key={value}>{value}</option>)}</select><small>Single-pilot / multi-pilot</small></label><label>Engine<select name="engineType" value={engineType} onChange={event=>setEngineType(event.target.value)}>{ENGINE_TYPES.map(value=><option key={value}>{value}</option>)}</select><small>Single-engine / multi-engine</small></label><label>Night landings<input name="landingsNight" type="number" min="0" max="99" value={landingsNight} onChange={event=>setLandingsNight(Number(event.target.value)||0)}/></label><label>Night time<input name="nightTime" inputMode="numeric" placeholder="0:00" defaultValue={formatEasaDuration(field("night_minutes","0"))}/></label><label>IFR time<input name="ifrTime" inputMode="numeric" placeholder="0:00" defaultValue={formatEasaDuration(field("ifr_minutes","0"))}/></label>
      {countersignatureRequired?<><label>Supervising PIC / FI<input name="verificationName" list={instructors.length?"connected-instructors":undefined} defaultValue={field("verification_name")} required/><small>{instructors.length?`Select a connected instructor when applicable. Required for ${role} credit.`:`Required for ${role} credit.`}</small></label><label>Countersignature reference<input name="verificationReference" defaultValue={field("verification_reference")} required/><small>Reference to the supervising PIC/FI countersignature or signed evidence.</small></label></>:<><input type="hidden" name="verificationName" value={field("verification_name")}/><input type="hidden" name="verificationReference" value={field("verification_reference")}/></>}
    </div></div></details>
    <details className="entry-section"><summary><span>Cost & notes</span><small>{billing||"Select billing"}{billing?` · 1/${billingShare}`:""}</small></summary><div className="entry-section-body"><div className="form-grid secondary-entry-grid"><label>Billing time<select name="billingBasis" value={billing} onChange={e=>setBilling(e.target.value as ""|"BLOCK"|"AIR")} required><option value="">Select billing</option>{BILLING.map(x=><option key={x}>{x}</option>)}</select></label><label>My share<select name="billingShare" value={billingShare} onChange={e=>setBillingShare(Number(e.target.value))}>{BILLING_SHARES.map(value=><option key={value} value={value}>{value===1?"1/1 · full price":`1/${value}`}</option>)}</select></label><label className="wide">Notes<textarea name="note" rows={3} defaultValue={field("note")}/></label></div><section className="price-preview compact-price" aria-live="polite"><div><span>Calculated flight cost</span><strong>{hourlyRate>0&&billableMinutes>0?`${Math.round(flightPrice).toLocaleString("en-GB")} CZK`:"—"}</strong></div><small>{hourlyRate>0&&billing?`${hourlyRate.toLocaleString("en-GB")} CZK/h · ${billing} ${billing==="AIR"?`${Math.floor(airMinutes/60)}:${String(airMinutes%60).padStart(2,"0")}`:`${Math.floor(blockMinutes/60)}:${String(blockMinutes%60).padStart(2,"0")}`} · 1/${billingShare}`:hourlyRate>0?"Select billing basis":"Hourly rate missing"}</small></section></div></details>
    <section className="entry-review-summary" aria-labelledby="flight-review-heading"><header><div><p className="section-kicker">Review before save</p><h3 id="flight-review-heading">{departure||"?"} → {arrival||"?"}</h3></div><span className={missing.length?"needs-attention":"ready"}>{missing.length?`${missing.length} ${missing.length===1?"item":"items"} need attention`:"Ready to save"}</span></header><dl><div><dt>Date / aircraft</dt><dd>{date||"—"} · {registration||"—"}</dd></div><div><dt>Role / logbook</dt><dd>{roleLabel(role)||"—"} · {evidence||"—"}</dd></div><div><dt>BLOCK / AIR</dt><dd>{durationLabel(blockMinutes)} / {durationLabel(airMinutes)}</dd></div><div><dt>Landings</dt><dd>{landingsDay} day{landingsNight?` · ${landingsNight} night`:""}</dd></div><div><dt>Estimated cost</dt><dd>{hourlyRate>0&&billableMinutes>0?`${Math.round(flightPrice).toLocaleString("en-GB")} CZK`:"—"}</dd></div></dl>{selected&&!editing?<p className="value-origin-note"><span>Automatic</span> Aircraft, logbook and billing defaults came from {registration}. You can change them above.</p>:null}{dirty?<small className="unsaved-indicator">Unsaved changes</small>:null}</section>
    {state.error?<p ref={errorRef} className="form-error" role="alert" tabIndex={-1}>{state.error}</p>:null}{state.success?<p className="form-success" role="status">{state.success}</p>:null}<div className="form-actions field-actions"><Submit/>{!editing?<Submit another/>:null}</div>
  </form>;
}
