"use client";
import { useActionState,useMemo,useState } from "react";
import { useFormStatus } from "react-dom";
import Link from "next/link";
import type { AircraftOption } from "@/lib/data/aircraft";
import type { FlightRow } from "@/lib/data/flights";
import type { FlightActionState } from "@/app/(protected)/flights/actions";
import { BILLING,CLASSES,EVIDENCE,ROLES } from "@/lib/flight-input";
import { BILLING_SHARES,calculatedFlightPrice,parseBilling,serializeBilling } from "@/lib/billing";
type Action=(state:FlightActionState,data:FormData)=>Promise<FlightActionState>;type Initial=Partial<FlightRow>&Record<string,unknown>;
function addTime(value:string,minutes:number){if(!/^\d\d:\d\d$/.test(value))return"";const total=(Number(value.slice(0,2))*60+Number(value.slice(3))+minutes+1440)%1440;return`${String(Math.floor(total/60)).padStart(2,"0")}:${String(total%60).padStart(2,"0")}`}
function minutesBetween(start:string,end:string){if(!/^\d\d:\d\d$/.test(start)||!/^\d\d:\d\d$/.test(end))return 0;const a=Number(start.slice(0,2))*60+Number(start.slice(3)),b=Number(end.slice(0,2))*60+Number(end.slice(3));return(b-a+1440)%1440}
const roleLabel=(value:string)=>value==="INSTRUKTOR"?"INSTRUCTOR":value;
function Submit({another=false}:{another?:boolean}){const{pending}=useFormStatus();return <button className={another?"secondary-link":"primary-button"} name="intent" value={another?"another":"save"} disabled={pending}>{pending?"Saving…":another?"Save and add another":"Save flight"}</button>}
export function FlightForm({action,aircraft,initial={},routes=[]}:{action:Action;aircraft:AircraftOption[];initial?:Initial;routes?:Array<{departure:string;arrival:string}>}){
 const[state,formAction]=useActionState(action,{}),field=(name:string,fallback="")=>String(initial[name]??fallback),editing=Boolean(initial.id);
 const initialRegistration=field("registration",aircraft[0]?.registration||"").trim().toUpperCase();
 const normalizedAircraft=useMemo(()=>aircraft.map(item=>({...item,registration:item.registration.trim().toUpperCase()})),[aircraft]);
 const[registration,setRegistration]=useState(initialRegistration);const selected=useMemo(()=>normalizedAircraft.find(x=>x.registration===registration),[normalizedAircraft,registration]);
 const registrationOptions=useMemo(()=>initialRegistration&&!normalizedAircraft.some(item=>item.registration===initialRegistration)?[{registration:initialRegistration} as AircraftOption,...normalizedAircraft]:normalizedAircraft,[initialRegistration,normalizedAircraft]);
 const initialBilling=parseBilling(field("billing_basis",selected?.billing_basis||"BLOCK"));
 const[type,setType]=useState(field("aircraft_type",selected?.aircraft_type||"")),[aircraftClass,setClass]=useState(field("aircraft_class",selected?.aircraft_class||"ULL")),[evidence,setEvidence]=useState(field("evidence",selected?.evidence||"ULL")),[role,setRole]=useState(field("role",selected?.default_role||"PIC")),[billing,setBilling]=useState(initialBilling.basis),[billingShare,setBillingShare]=useState(initialBilling.share),[hourlyRate,setHourlyRate]=useState(Number(field("price_per_hour",String(selected?.price_per_hour||0)))||0);
 const[departure,setDeparture]=useState(field("departure")),[arrival,setArrival]=useState(field("arrival")),[off,setOff]=useState(field("off_block")),[takeoff,setTakeoff]=useState(field("takeoff")),[landing,setLanding]=useState(field("landing")),[on,setOn]=useState(field("on_block")),[duration,setDuration]=useState(60);
 const pickAircraft=(reg:string)=>{const normalized=reg.trim().toUpperCase();setRegistration(normalized);const a=normalizedAircraft.find(x=>x.registration===normalized);if(a){const nextBilling=parseBilling(a.billing_basis);setType(a.aircraft_type||"");setClass(a.aircraft_class||"ULL");setEvidence(a.evidence||"ULL");setRole(a.default_role||"PIC");setBilling(nextBilling.basis);setBillingShare(nextBilling.share);setHourlyRate(Number(a.price_per_hour)||0)}};
 const fillTimes=()=>{const start=off||new Date().toLocaleTimeString("en-GB",{hour:"2-digit",minute:"2-digit"});setOff(start);setTakeoff(addTime(start,5));setLanding(addTime(start,5+duration));setOn(addTime(start,10+duration))};
 const blockMinutes=minutesBetween(off,on),airMinutes=minutesBetween(takeoff,landing),billableMinutes=billing==="AIR"?airMinutes:blockMinutes,billingValue=serializeBilling(billing,billingShare),flightPrice=calculatedFlightPrice(hourlyRate,blockMinutes,airMinutes,billingValue);
 return <form action={formAction} className="flight-form">{!editing?<details className="quick-tools"><summary>Quick entry</summary><div className="quick-tools-grid"><label>Flight duration (min)<input type="number" min="1" max="1440" value={duration} onChange={e=>setDuration(Number(e.target.value)||1)}/></label><button type="button" className="secondary-link" onClick={fillTimes}>Fill times ±5 min</button><button type="button" className="secondary-link" onClick={()=>{setDeparture(arrival);setArrival(departure)}}>Reverse route</button></div>{routes.length?<div className="route-chips">{routes.slice(0,12).map((r,i)=><button type="button" key={`${r.departure}-${r.arrival}-${i}`} onClick={()=>{setDeparture(r.departure);setArrival(r.arrival)}}>{r.departure}–{r.arrival}</button>)}</div>:null}</details>:null}<div className="form-grid">
  <label>Date<input name="date" type="date" defaultValue={field("date",new Date().toISOString().slice(0,10))} required/></label><label>Registration<select name="registration" value={registration} onChange={e=>pickAircraft(e.target.value)} required><option value="">Select</option>{registrationOptions.map(a=><option key={a.registration} value={a.registration}>{a.registration}</option>)}</select><small><Link href="/database">Manage aircraft</Link></small></label><label>Aircraft type<input name="aircraftType" value={type} onChange={e=>setType(e.target.value)}/></label><label>Class<select name="aircraftClass" value={aircraftClass} onChange={e=>setClass(e.target.value)}>{CLASSES.map(x=><option key={x}>{x}</option>)}</select></label><label>Logbook<select name="evidence" value={evidence} onChange={e=>setEvidence(e.target.value)}>{EVIDENCE.map(x=><option key={x}>{x}</option>)}</select></label><label>Role<select name="role" value={role} onChange={e=>setRole(e.target.value)}>{ROLES.map(x=><option key={x} value={x}>{roleLabel(x)}</option>)}</select></label>
  <label>Departure<input name="departure" value={departure} onChange={e=>setDeparture(e.target.value.toUpperCase())} placeholder="LKLT"/></label><label>Arrival<input name="arrival" value={arrival} onChange={e=>setArrival(e.target.value.toUpperCase())} placeholder="LKLT"/></label><label>Off-block<input name="offBlock" type="time" value={off} onChange={e=>setOff(e.target.value)}/></label><label>Takeoff<input name="takeoff" type="time" value={takeoff} onChange={e=>setTakeoff(e.target.value)}/></label><label>Landing<input name="landing" type="time" value={landing} onChange={e=>setLanding(e.target.value)}/></label><label>On-block<input name="onBlock" type="time" value={on} onChange={e=>setOn(e.target.value)}/></label>
  <label>Landings<input name="starts" type="number" min="0" max="99" defaultValue={field("starts","1")}/></label><label>Billing time<select name="billingBasis" value={billing} onChange={e=>setBilling(e.target.value as "BLOCK"|"AIR")}>{BILLING.map(x=><option key={x}>{x}</option>)}</select></label><label>My share<select name="billingShare" value={billingShare} onChange={e=>setBillingShare(Number(e.target.value))}>{BILLING_SHARES.map(value=><option key={value} value={value}>{value===1?"1/1 · full price":`1/${value}`}</option>)}</select></label><label>Commander<input name="commander" defaultValue={field("commander")}/></label><label>Instructor<input name="instructor" defaultValue={field("instructor")}/></label><label className="wide">Task<input name="task" defaultValue={field("task")}/></label><label className="wide">Notes<textarea name="note" rows={4} defaultValue={field("note")}/></label>
 </div><section className="price-preview" aria-live="polite"><div><span>Calculated flight cost</span><strong>{hourlyRate>0&&billableMinutes>0?`${Math.round(flightPrice).toLocaleString("en-GB")} CZK`:"—"}</strong></div><small>{hourlyRate>0?`${hourlyRate.toLocaleString("en-GB")} CZK/h · ${billing} ${billing==="AIR"?`${Math.floor(airMinutes/60)}:${String(airMinutes%60).padStart(2,"0")}`:`${Math.floor(blockMinutes/60)}:${String(blockMinutes%60).padStart(2,"0")}`} · 1/${billingShare}`:"Hourly rate missing"}</small></section>{state.error?<p className="form-error" role="alert">{state.error}</p>:null}{state.success?<p className="form-success" role="status">{state.success}</p>:null}<div className="form-actions"><Submit/>{!editing?<Submit another/>:null}</div></form>
}
