import { requireUser } from "@/lib/auth/require-user";
import { getHelicopterRecencyStateForUser } from "@/lib/helicopter-recency-service";
import { addHelicopterProficiencyEvidence,deleteHelicopterProficiencyEvidence } from "@/app/(protected)/credentials/helicopter-actions";
import type { RecencyEvaluation,RecencyRequirement } from "@/lib/recency-engine";
import { PendingActionButton } from "@/components/pending-action-button";
import { PendingActionLabel } from "@/components/pending-action-label";

const statusClass=(status:RecencyEvaluation["status"])=>status==="current"?"status-on":status==="attention"?"status-warning":"status-off";
const requirementValue=(item:RecencyRequirement)=>item.unit==="hours"?`${item.current.toFixed(item.current%1?1:0)} / ${item.target} h`:`${Math.round(item.current)} / ${Math.round(item.target)}`;

function EvaluationCard({item}:{item:RecencyEvaluation}){
  return <article className="spl-recency-card"><header><div><span>{item.code}</span><strong>{item.title}</strong><small>{item.windowLabel}</small></div><b className={statusClass(item.status)}>{item.badge||item.status.toUpperCase()}</b></header><p>{item.summary}</p><div className="spl-requirements">{item.requirements.map(requirement=><div key={requirement.id} className={requirement.met?"met":"missing"}><span>{requirement.label}</span><strong>{requirementValue(requirement)}</strong></div>)}</div>{item.note?<small className="spl-recency-note">{item.note}</small>:null}</article>;
}

export async function HelicopterRecencyPanel(){
  const{userId}=await requireUser();const state=await getHelicopterRecencyStateForUser(userId);if(!state)return null;
  return <section className="panel spl-recency-panel"><div className="section-heading"><div><p className="eyebrow">PART-FCL · HELICOPTER</p><h2>Helicopter recency</h2><p className="muted">Type-specific LAPL(H) recency and passenger recent-experience evidence. Different helicopter types are never pooled automatically.</p></div><span>{state.evaluations.length+state.passengerEvaluations.length}</span></div>
    {!state.helicopterTypes.length?<div className="flight-empty-state"><h3>Add a helicopter profile</h3><p>Create an EASA aircraft profile with <b>Class / category = Helicopter</b>. FlyTally uses its stored type/model to keep FCL.140.H recency type-specific.</p></div>:null}
    {state.evaluations.length?<><h3 className="spl-recency-group-title">LAPL(H) flying privileges</h3><div className="spl-recency-grid">{state.evaluations.map(item=><EvaluationCard key={item.id} item={item}/>)}</div></>:state.hasHelicopterLicence&&!state.hasLaplH?<p className="spl-recency-setup-note">FCL.140.H applies to LAPL(H). Your other helicopter licences remain type-rating/validity controlled; FlyTally does not apply the LAPL(H) rolling rule to them.</p>:null}
    {state.passengerEvaluations.length?<><h3 className="spl-recency-group-title">Passenger recent experience</h3><div className="spl-recency-grid">{state.passengerEvaluations.map(item=><EvaluationCard key={item.id} item={item}/>)}</div></>:null}
    {state.hasLaplH?<details className="spl-evidence"><summary>Examiner proficiency-check evidence</summary><div className="spl-evidence-body"><p className="muted">Under FCL.140.H a proficiency check on the specific helicopter type is an alternative to the 12-month experience + refresher route. Record only signed examiner evidence.</p>{state.helicopterTypes.length?<datalist id="helicopter-recency-types">{state.helicopterTypes.map(type=><option value={type} key={type}/>)}</datalist>:null}<form action={addHelicopterProficiencyEvidence} className="form-grid settings-grid"><label>Helicopter type<input name="helicopter_type" list="helicopter-recency-types" placeholder="R44" required/></label><label>Date<input type="date" name="evidence_date" required/></label><label>Examiner<input name="signer" required/></label><label>Reference<input name="reference" required/></label><label className="wide">Notes<input name="note"/></label><div className="form-actions wide"><PendingActionButton className="primary-button" pendingLabel={<PendingActionLabel current="Adding…" reserve="Add evidence"/>}><PendingActionLabel current="Add evidence" reserve="Adding…"/></PendingActionButton></div></form>{state.evidence.length?<div className="spl-evidence-list">{state.evidence.map(item=><div key={item.id}><span><strong>{item.helicopterType} · {item.date}</strong><small>{item.signer} · {item.reference}{item.note?` · ${item.note}`:""}</small></span><form action={deleteHelicopterProficiencyEvidence}><input type="hidden" name="id" value={item.id}/><PendingActionButton className="secondary-link" pendingLabel={<PendingActionLabel current="Removing…" reserve="Remove"/>}><PendingActionLabel current="Remove" reserve="Removing…"/></PendingActionButton></form></div>)}</div>:null}</div></details>:null}
  </section>;
}
