"use client";
import { useActionState,useMemo,useState } from "react";
import { useFormStatus } from "react-dom";
import type { AircraftOption } from "@/lib/data/aircraft";
import type { FlightActionState } from "@/app/(protected)/flights/actions";
import type { MapTrack,TrackPoint } from "@/lib/data/tracks";
import { TracksMap } from "@/components/tracks-map";
import { localParts,overview,parseTrackFile,suggestedSplits,trackStats } from "@/lib/track-processing";
type Action=(state:FlightActionState,data:FormData)=>Promise<FlightActionState>;
type Analysis={name:string;points:TrackPoint[];times:string[];gaps:number;date:string;start:string;end:string;registration:string;minAlt:number;maxAlt:number};
function inspect(source:string,name:string):Analysis{const parsed=parseTrackFile(source,name),points=parsed.map(point=>({...point,alt:point.alt??undefined,time:point.time??undefined})) as TrackPoint[],times=parsed.map(point=>point.time||"").filter(Boolean),splits=suggestedSplits(parsed),stats=trackStats(parsed),start=localParts(stats.startUtc),end=localParts(stats.endUtc),alts=parsed.map(point=>point.alt).filter((value):value is number=>value!==null&&Number.isFinite(value)),registration=name.toUpperCase().replaceAll("_","-").match(/\bOK-?[A-Z]{3}\d{0,2}\b/)?.[0]?.replace(/^OK(?!-)/,"OK-")||"";return{name,points,times,gaps:splits.length,date:start?.date||"",start:start?.time||"",end:end?.time||"",registration,minAlt:alts.length?Math.min(...alts):0,maxAlt:alts.length?Math.max(...alts):0}}
function Submit(){const {pending}=useFormStatus();return <button className="primary-button" disabled={pending}>{pending?"Importuji track…":"Zkontrolováno – uložit let"}</button>}
export function KmlImportForm({action,aircraft}:{action:Action;aircraft:AircraftOption[]}){
 const [state,formAction]=useActionState(action,{}),[analysis,setAnalysis]=useState<Analysis|null>(null),[registration,setRegistration]=useState("");
 const preview=useMemo<MapTrack[]>(()=>analysis?.points.length?[{id:0,flightId:0,date:analysis.date,registration,departure:"",arrival:"",evidence:"ULL",distanceKm:0,points:overview(analysis.points.map(point=>({...point,alt:point.alt??null,time:point.time??null})),1200).map(point=>({...point,alt:point.alt??undefined,time:point.time??undefined}))}]:[],[analysis,registration]);
 return <form action={formAction} className="flight-form kml-wizard">
  <div className="import-step"><span>1</span><div><strong>Nahrání tracku</strong><small>Soubor se nejprve pouze analyzuje. Nic se neuloží bez finálního potvrzení.</small></div></div>
  <div className="upload-zone"><label>KML, GPX nebo CSV<input name="kml" type="file" accept=".kml,.gpx,.csv,application/vnd.google-earth.kml+xml,application/xml,text/xml,text/csv" required onChange={async e=>{const f=e.target.files?.[0];if(!f){setAnalysis(null);return}const a=inspect(await f.text(),f.name);setAnalysis(a);if(a.registration&&aircraft.some(x=>x.registration===a.registration))setRegistration(a.registration)}}/></label>{analysis?<p>{analysis.points.length>=2?"✓":"⚠"} {analysis.name} · {analysis.points.length} GPS bodů · {analysis.times.length} časů{analysis.gaps?` · návrh ${analysis.gaps+1} samostatných letů`:""}</p>:<p className="muted">KML/gx:Track, GPX a CSV se sloupci latitude/longitude/time.</p>}</div>
  {analysis?<><div className="import-step"><span>2</span><div><strong>Kontrola tracku</strong><small>{analysis.date||"Datum bez časových značek"} · {analysis.start||"—"}–{analysis.end||"—"} · výška {Math.round(analysis.minAlt*3.28084)}–{Math.round(analysis.maxAlt*3.28084)} ft</small></div></div><section className="kml-preview"><TracksMap tracks={preview} height={360} detail/></section><div className="import-choice"><label>Zpracování tracku<select name="splitMode" defaultValue={analysis.gaps?"auto":"single"}><option value="auto">Smart KML – rozdělit potvrzené samostatné lety</option><option value="single">Uložit celý track jako jeden let</option></select><small>Automatické dělení vyhodnocuje časové mezery i delší zastavení na zemi. Krátký touch-and-go zůstává jedním letem a zvýší počet přistání.</small></label></div><div className="import-step"><span>3</span><div><strong>Údaje letu a finální kontrola</strong><small>Před uložením lze automatický návrh upravit.</small></div></div></>:null}
  <div className="form-grid"><label>Datum<input key={`date-${analysis?.name}`} name="date" type="date" defaultValue={analysis?.date||""}/><small>Prázdné = z KML</small></label><label>Imatrikulace<select name="registration" required value={registration} onChange={e=>setRegistration(e.target.value)}><option value="">Vyberte</option>{aircraft.map(a=><option key={a.registration}>{a.registration}</option>)}</select>{analysis?.registration?<small>Soubor navrhuje {analysis.registration}</small>:null}</label><label>Typ letadla<input key={`type-${registration}`} name="aircraftType" placeholder="Typ" defaultValue={aircraft.find(a=>a.registration===registration)?.aircraft_type||""}/></label><label>Třída<select key={`class-${registration}`} name="aircraftClass" defaultValue={aircraft.find(a=>a.registration===registration)?.aircraft_class||"ULL"}><option>ULL</option><option>SEP</option><option>TMG</option><option>MEP</option><option>SET</option><option>OTHER</option><option>GLIDER</option></select></label><label>Evidence<select key={`evidence-${registration}`} name="evidence" defaultValue={aircraft.find(a=>a.registration===registration)?.evidence||"ULL"}><option>ULL</option><option>EASA</option></select></label><label>Funkce<select key={`role-${registration}`} name="role" defaultValue={aircraft.find(a=>a.registration===registration)?.default_role||"PIC"}><option>PIC</option><option>DUAL</option><option>INSTRUKTOR</option><option>SAFETY PILOT</option><option>CO-PILOT</option><option>PAX</option><option>OBSERVER</option></select></label><label>Odlet<input name="departure" placeholder="Automaticky podle GPS"/></label><label>Přílet<input name="arrival" placeholder="Automaticky podle GPS"/></label><label>Off-block<input key={`off-${analysis?.name}`} name="offBlock" type="time" defaultValue={analysis?.start||""}/><small>Prázdné = z KML</small></label><label>On-block<input key={`on-${analysis?.name}`} name="onBlock" type="time" defaultValue={analysis?.end||""}/><small>Prázdné = z KML</small></label><label>Přistání<input name="starts" type="number" min="0" defaultValue="1"/></label><label>Úloha<input name="task" defaultValue="KML import"/></label><label className="wide">Poznámka<textarea name="note" rows={3}/></label></div>
  {analysis?<label className="review-confirm"><input type="checkbox" name="reviewed" value="yes" required/> Zkontroloval jsem trasu, rozdělení a předvyplněné údaje.</label>:null}
  {state.error?<p className="form-error">{state.error}</p>:null}<div className="form-actions"><Submit/></div>
 </form>
}
