"use client";
import { useActionState,useMemo,useState } from "react";
import { useFormStatus } from "react-dom";
import type { AircraftOption } from "@/lib/data/aircraft";
import type { FlightActionState } from "@/app/(protected)/flights/actions";
import type { MapTrack,TrackPoint } from "@/lib/data/tracks";
import { TracksMap } from "@/components/tracks-map";
type Action=(state:FlightActionState,data:FormData)=>Promise<FlightActionState>;
type Analysis={name:string;points:TrackPoint[];times:string[];gaps:number;date:string;start:string;end:string;registration:string;minAlt:number;maxAlt:number};
const clean=(v:string)=>v.replace(/<!\[CDATA\[|\]\]>/g,"").trim();
function point(value:string,time?:string):TrackPoint|null{const n=clean(value).replaceAll(","," ").split(/\s+/).map(Number);if(n.length<2||!Number.isFinite(n[0])||!Number.isFinite(n[1])||n[0]<-180||n[0]>180||n[1]<-90||n[1]>90)return null;return{lon:n[0],lat:n[1],alt:Number.isFinite(n[2])?n[2]:undefined,time:time||undefined}}
function local(iso?:string){if(!iso)return{date:"",time:""};const d=new Date(iso);if(Number.isNaN(d.getTime()))return{date:"",time:""};const p=Object.fromEntries(new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Prague",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(d).map(x=>[x.type,x.value]));return{date:`${p.year}-${p.month}-${p.day}`,time:`${p.hour}:${p.minute}`}}
function inspect(source:string,name:string):Analysis{let points:TrackPoint[]=[];if(name.toLowerCase().endsWith(".gpx")||/<(?:\w+:)?gpx\b/i.test(source)){points=[...source.matchAll(/<(?:\w+:)?(?:trkpt|rtept)\b([^>]*)>([\s\S]*?)<\/(?:\w+:)?(?:trkpt|rtept)>/gi)].map(m=>{const lat=Number(m[1].match(/\blat=["']([^"']+)/i)?.[1]),lon=Number(m[1].match(/\blon=["']([^"']+)/i)?.[1]),alt=Number(m[2].match(/<(?:\w+:)?ele\b[^>]*>([^<]+)/i)?.[1]),time=clean(m[2].match(/<(?:\w+:)?time\b[^>]*>([^<]+)/i)?.[1]||"");return Number.isFinite(lat)&&Number.isFinite(lon)?{lat,lon,alt:Number.isFinite(alt)?alt:undefined,time:time||undefined}:null}).filter(Boolean) as TrackPoint[]}
 else if(name.toLowerCase().endsWith(".csv")&&!source.includes("<")){const lines=source.replace(/^\uFEFF/,"").split(/\r?\n/).filter(Boolean),delimiter=(lines[0]?.match(/;/g)?.length||0)>(lines[0]?.match(/,/g)?.length||0)?";":lines[0]?.includes("\t")?"\t":",",cells=(line:string)=>line.split(delimiter).map(v=>v.trim().replace(/^"|"$/g,"")),headers=cells(lines[0]||"").map(x=>x.toLowerCase().replace(/[^a-z0-9]/g,"")),at=(names:string[])=>headers.findIndex(h=>names.includes(h)),latI=at(["lat","latitude","latitudedeg"]),lonI=at(["lon","lng","longitude","longitudedeg"]),altI=at(["alt","altitude","elevation","ele","altm"]),timeI=at(["time","timestamp","datetime","utc","dateandtime"]);if(latI>=0&&lonI>=0)points=lines.slice(1).map(line=>{const c=cells(line),lat=Number(c[latI]),lon=Number(c[lonI]),alt=Number(c[altI]),time=c[timeI];return Number.isFinite(lat)&&Number.isFinite(lon)?{lat,lon,alt:Number.isFinite(alt)?alt:undefined,time:time||undefined}:null}).filter(Boolean) as TrackPoint[]}
 else {const track=source.match(/<(?:\w+:)?Track\b[^>]*>([\s\S]*?)<\/(?:\w+:)?Track>/i)?.[1];if(track){const times=[...track.matchAll(/<when\b[^>]*>([\s\S]*?)<\/when>/gi)].map(m=>clean(m[1]));points=[...track.matchAll(/<(?:\w+:)?coord\b[^>]*>([\s\S]*?)<\/(?:\w+:)?coord>/gi)].map((m,i)=>point(m[1],times[i])).filter(Boolean) as TrackPoint[]}
 if(points.length<2){for(const block of source.matchAll(/<coordinates\b[^>]*>([\s\S]*?)<\/coordinates>/gi))for(const token of clean(block[1]).split(/\s+/)){const p=point(token);if(p)points.push(p)}}
 }
 points=points.filter((p,i,a)=>!i||p.lat!==a[i-1].lat||p.lon!==a[i-1].lon);const times=points.map(p=>p.time||"").filter(Boolean),stamp=times.map(x=>Date.parse(x)).filter(Number.isFinite),gaps=stamp.slice(1).filter((v,i)=>v-stamp[i]>=600000).length,start=local(times[0]),end=local(times.at(-1)),alts=points.map(p=>Number(p.alt)).filter(Number.isFinite),registration=name.toUpperCase().match(/\bOK-[A-Z0-9]{3,5}\b/)?.[0]||"";return{name,points,times,gaps,date:start.date,start:start.time,end:end.time,registration,minAlt:alts.length?Math.min(...alts):0,maxAlt:alts.length?Math.max(...alts):0}}
function Submit(){const {pending}=useFormStatus();return <button className="primary-button" disabled={pending}>{pending?"Importuji track…":"Zkontrolováno – uložit let"}</button>}
export function KmlImportForm({action,aircraft}:{action:Action;aircraft:AircraftOption[]}){
 const [state,formAction]=useActionState(action,{}),[analysis,setAnalysis]=useState<Analysis|null>(null),[registration,setRegistration]=useState("");
 const preview=useMemo<MapTrack[]>(()=>analysis?.points.length?[{id:0,flightId:0,date:analysis.date,registration,departure:"",arrival:"",evidence:"ULL",distanceKm:0,points:analysis.points.length>1200?analysis.points.filter((_,i)=>i%Math.ceil(analysis.points.length/1200)===0):analysis.points}]:[],[analysis,registration]);
 return <form action={formAction} className="flight-form kml-wizard">
  <div className="import-step"><span>1</span><div><strong>Nahrání tracku</strong><small>Soubor se nejprve pouze analyzuje. Nic se neuloží bez finálního potvrzení.</small></div></div>
  <div className="upload-zone"><label>KML, GPX nebo CSV<input name="kml" type="file" accept=".kml,.gpx,.csv,application/vnd.google-earth.kml+xml,application/xml,text/xml,text/csv" required onChange={async e=>{const f=e.target.files?.[0];if(!f){setAnalysis(null);return}const a=inspect(await f.text(),f.name);setAnalysis(a);if(a.registration&&aircraft.some(x=>x.registration===a.registration))setRegistration(a.registration)}}/></label>{analysis?<p>✓ {analysis.name} · {analysis.points.length} GPS bodů · {analysis.times.length} časů{analysis.gaps?` · ${analysis.gaps} možných dělení`:""}</p>:<p className="muted">KML/gx:Track, GPX a CSV se sloupci latitude/longitude/time.</p>}</div>
  {analysis?<><div className="import-step"><span>2</span><div><strong>Kontrola tracku</strong><small>{analysis.date||"Datum bez časových značek"} · {analysis.start||"—"}–{analysis.end||"—"} · výška {Math.round(analysis.minAlt*3.28084)}–{Math.round(analysis.maxAlt*3.28084)} ft</small></div></div><section className="kml-preview"><TracksMap tracks={preview} height={360} detail/></section><div className="import-choice"><label>Zpracování tracku<select name="splitMode" defaultValue={analysis.gaps?"auto":"single"}><option value="auto">Smart KML – rozdělit potvrzené samostatné lety</option><option value="single">Uložit celý track jako jeden let</option></select><small>Automatické dělení vyhodnocuje časové mezery i delší zastavení na zemi. Krátký touch-and-go zůstává jedním letem a zvýší počet přistání.</small></label></div><div className="import-step"><span>3</span><div><strong>Údaje letu a finální kontrola</strong><small>Před uložením lze automatický návrh upravit.</small></div></div></>:null}
  <div className="form-grid"><label>Datum<input key={`date-${analysis?.name}`} name="date" type="date" defaultValue={analysis?.date||""}/><small>Prázdné = z KML</small></label><label>Imatrikulace<select name="registration" required value={registration} onChange={e=>setRegistration(e.target.value)}><option value="">Vyberte</option>{aircraft.map(a=><option key={a.registration}>{a.registration}</option>)}</select>{analysis?.registration?<small>Soubor navrhuje {analysis.registration}</small>:null}</label><label>Typ letadla<input key={`type-${registration}`} name="aircraftType" placeholder="Typ" defaultValue={aircraft.find(a=>a.registration===registration)?.aircraft_type||""}/></label><label>Třída<select key={`class-${registration}`} name="aircraftClass" defaultValue={aircraft.find(a=>a.registration===registration)?.aircraft_class||"ULL"}><option>ULL</option><option>SEP</option><option>TMG</option><option>MEP</option><option>SET</option><option>OTHER</option><option>GLIDER</option></select></label><label>Evidence<select key={`evidence-${registration}`} name="evidence" defaultValue={aircraft.find(a=>a.registration===registration)?.evidence||"ULL"}><option>ULL</option><option>EASA</option></select></label><label>Funkce<select key={`role-${registration}`} name="role" defaultValue={aircraft.find(a=>a.registration===registration)?.default_role||"PIC"}><option>PIC</option><option>DUAL</option><option>INSTRUKTOR</option><option>SAFETY PILOT</option><option>CO-PILOT</option><option>PAX</option><option>OBSERVER</option></select></label><label>Odlet<input name="departure" placeholder="Automaticky podle GPS"/></label><label>Přílet<input name="arrival" placeholder="Automaticky podle GPS"/></label><label>Off-block<input key={`off-${analysis?.name}`} name="offBlock" type="time" defaultValue={analysis?.start||""}/><small>Prázdné = z KML</small></label><label>On-block<input key={`on-${analysis?.name}`} name="onBlock" type="time" defaultValue={analysis?.end||""}/><small>Prázdné = z KML</small></label><label>Přistání<input name="starts" type="number" min="0" defaultValue="1"/></label><label>Úloha<input name="task" defaultValue="KML import"/></label><label className="wide">Poznámka<textarea name="note" rows={3}/></label></div>
  {analysis?<label className="review-confirm"><input type="checkbox" name="reviewed" value="yes" required/> Zkontroloval jsem trasu, rozdělení a předvyplněné údaje.</label>:null}
  {state.error?<p className="form-error">{state.error}</p>:null}<div className="form-actions"><Submit/></div>
 </form>
}
