"use client";
import { useActionState,useState } from "react";import { useFormStatus } from "react-dom";import type { AircraftOption } from "@/lib/data/aircraft";import type { FlightActionState } from "@/app/(protected)/flights/actions";
type Action=(state:FlightActionState,data:FormData)=>Promise<FlightActionState>;
function Submit(){const {pending}=useFormStatus();return <button className="primary-button" disabled={pending}>{pending?'Importuji track…':'Importovat a uložit'}</button>}
export function KmlImportForm({action,aircraft}:{action:Action;aircraft:AircraftOption[]}){
  const [state,formAction]=useActionState(action,{}),[info,setInfo]=useState("");
  return <form action={formAction} className="flight-form">
    <div className="upload-zone"><label>KML soubor<input name="kml" type="file" accept=".kml,application/vnd.google-earth.kml+xml,application/xml,text/xml" required onChange={async e=>{const f=e.target.files?.[0];if(!f){setInfo('');return}const source=await f.text(),gx=(source.match(/<(?:\w+:)?coord\b/gi)||[]).length,plain=(source.match(/<coordinates\b/gi)||[]).length,times=(source.match(/<when\b/gi)||[]).length,gaps=[...source.matchAll(/<when\b[^>]*>([^<]+)<\/when>/gi)].map(m=>Date.parse(m[1])).filter(Number.isFinite).slice(1).filter((v,i,a)=>v-(i? a[i-1]:v)>1200000).length;setInfo(`${f.name} · ${gx||plain} GPS záznamů · ${times} časových značek${gaps?` · možné mezery: ${gaps}`:''}`)}}/></label>{info?<p>✓ {info}</p>:<p className="muted">Podporuje KML, gx:Track, Flightradar24 a ADS-B exporty.</p>}</div>
    <div className="import-choice"><label>Zpracování tracku<select name="splitMode" defaultValue="auto"><option value="auto">Smart KML – navržené samostatné lety</option><option value="single">Vždy uložit jako jeden let</option></select><small>Automatické dělení používá jen dlouhé časové mezery mezi věrohodnými částmi. Jednotlivé tracky zůstanou u svých letů.</small></label></div>
    <div className="form-grid"><label>Datum<input name="date" type="date"/><small>Prázdné = z KML</small></label><label>Imatrikulace<select name="registration" required><option value="">Vyberte</option>{aircraft.map(a=><option key={a.registration}>{a.registration}</option>)}</select></label><label>Typ letadla<input name="aircraftType" placeholder="Typ"/></label><label>Třída<select name="aircraftClass"><option>ULL</option><option>SEP</option><option>TMG</option><option>MEP</option><option>OTHER</option></select></label><label>Evidence<select name="evidence"><option>ULL</option><option>EASA</option></select></label><label>Funkce<select name="role"><option>PIC</option><option>DUAL</option><option>INSTRUKTOR</option><option>SAFETY PILOT</option></select></label><label>Odlet<input name="departure" placeholder="LKLT"/></label><label>Přílet<input name="arrival" placeholder="LKLT"/></label><label>Off-block<input name="offBlock" type="time"/><small>Prázdné = z KML</small></label><label>On-block<input name="onBlock" type="time"/><small>Prázdné = z KML</small></label><label>Přistání<input name="starts" type="number" min="0" defaultValue="1"/></label><label>Úloha<input name="task" defaultValue="KML import"/></label><label className="wide">Poznámka<textarea name="note" rows={3}/></label></div>
    {state.error?<p className="form-error">{state.error}</p>:null}<div className="form-actions"><Submit/></div>
  </form>;
}
