import Link from "next/link";
import { requireUser } from "@/lib/auth/require-user";
import { getRecencyComplianceWorkspaceForUser } from "@/lib/recency-workspace-service";
import type { ComplianceWorkspaceItem,ComplianceWorkspaceStatus } from "@/lib/recency-workspace";
import type { RecencyRequirement } from "@/lib/recency-engine";
import { RecencyPanel } from "@/components/recency-panel";
import { SplRecencyPanel } from "@/components/spl-recency-panel";
import { HelicopterRecencyPanel } from "@/components/helicopter-recency-panel";
import { BalloonRecencyPanel } from "@/components/balloon-recency-panel";

const tabs=[["overview","Overview"],["licences","Licences & ratings"],["recency","Recency"],["training","Aircraft training"],["documents","Medical & documents"]] as const;
const categoryLabels:Record<string,string>={aeroplane:"Aeroplane",helicopter:"Helicopter",sailplane:"Sailplane",balloon:"Balloon",ull:"ULL",other:"Other"};
const categoryLabel=(value:string)=>categoryLabels[value]??value;
const statusClass=(status:ComplianceWorkspaceStatus)=>status==="current"?"status-on":status==="not-current"?"status-off":status==="incomplete-evidence"?"record-status":"status-warning";
const requirementValue=(item:RecencyRequirement)=>item.unit==="hours"?`${Math.floor(item.current)}:${String(Math.round((item.current-Math.floor(item.current))*60)).padStart(2,"0")} / ${Math.floor(item.target)}:${String(Math.round((item.target-Math.floor(item.target))*60)).padStart(2,"0")}`:`${Math.round(item.current)} / ${Math.round(item.target)}`;

function CredentialsHeader(){return <><header className="page-header"><div><p className="eyebrow">PILOT PROFILE</p><h1>Licences</h1><p className="muted">Recency, validity and the evidence behind your flying status.</p></div></header><nav className="credentials-tabs" aria-label="Licence sections">{tabs.map(([key,label])=><Link key={key} className={key==="recency"?"active":""} href={`/credentials?view=${key}`}>{label}</Link>)}</nav></>}

function WorkspaceRow({item}:{item:ComplianceWorkspaceItem}){
  return <article className={`compliance-row compliance-${item.status}`}><div className="compliance-row-main"><div className="compliance-row-kicker"><span>{item.family}{item.code?` · ${item.code}`:""}</span><span>{categoryLabel(item.category)}</span></div><div className="compliance-row-title"><strong>{item.title}</strong><b className={statusClass(item.status)}>{item.statusLabel}</b></div><p>{item.summary}</p>{item.requirements.length?<div className="compliance-requirements">{item.requirements.map(requirement=><span className={requirement.met?"met":"missing"} key={requirement.id}><small>{requirement.label}</small><strong>{requirementValue(requirement)}</strong></span>)}</div>:null}<div className="compliance-row-meta">{item.windowLabel?<span>{item.windowLabel}</span>:null}{item.nextDate?<span>Next date · {item.nextDate}</span>:null}{item.evidenceSummary?<span>Evidence · {item.evidenceSummary}</span>:null}</div>{item.evidenceLinks.length?<details className="compliance-evidence"><summary>Contributing flights</summary><div>{item.evidenceLinks.map(link=><span key={link.id}><span><strong>{link.label}</strong>{link.detail?<small>{link.detail}</small>:null}</span>{link.href?<Link href={link.href}>Open</Link>:null}</span>)}</div></details>:null}</div><Link className="compliance-open" href={item.href}>{item.kind==="recency"?"Details":"Open"}</Link></article>;
}

export async function RecencyComplianceWorkspace({detailed=false}:{detailed?:boolean}){
  if(detailed)return <><CredentialsHeader/><div className="compliance-detail-nav"><div><p className="eyebrow">EVIDENCE & SETTINGS</p><h2>Detailed recency records</h2><p className="muted">Edit monitoring and structured evidence here. The summary workspace remains read-only.</p></div><Link className="secondary-button" href="/credentials?view=recency">Back to workspace</Link></div><RecencyPanel/><SplRecencyPanel/><HelicopterRecencyPanel/><BalloonRecencyPanel/></>;
  const{userId}=await requireUser(),state=await getRecencyComplianceWorkspaceForUser(userId),attention=state.items.filter(item=>item.status!=="current"),flying=state.items.filter(item=>item.kind==="recency"||item.kind==="setup"),credentialAttention=attention.filter(item=>["licence","qualification","document"].includes(item.kind));
  return <><CredentialsHeader/><main className="compliance-workspace">
    <section className="compliance-hero"><div><p className="eyebrow">RECENCY & COMPLIANCE</p><h2>What needs action</h2><p className="muted">Planning view built from the existing regulation-specific rule engines. FlyTally shows recorded evidence and does not infer a legal privilege that is not supported by saved data.</p></div><Link className="secondary-button" href="/credentials?view=recency&detail=1">Evidence & monitor settings</Link></section>
    <section className="compliance-scorecard" aria-label="Compliance status summary"><article><span>Not current</span><strong>{state.counts["not-current"]}</strong></article><article><span>Incomplete evidence</span><strong>{state.counts["incomplete-evidence"]}</strong></article><article><span>Action soon</span><strong>{state.counts["action-soon"]}</strong></article><article><span>Current</span><strong>{state.counts.current}</strong></article></section>
    {attention.length?<section className="compliance-section"><div className="compliance-section-heading"><div><p className="eyebrow">ACTION QUEUE</p><h2>{attention.length===1?"1 item needs attention":`${attention.length} items need attention`}</h2></div><span>Most important first</span></div><div className="compliance-list">{attention.map(item=><WorkspaceRow item={item} key={item.id}/>)}</div></section>:<section className="compliance-all-current"><span className="status-on">ALL CURRENT</span><div><strong>No recorded recency or validity item needs action.</strong><p className="muted">This is an evidence-based planning indication, not a substitute for licence-holder responsibility or authority records.</p></div></section>}
    <section className="compliance-section"><div className="compliance-section-heading"><div><p className="eyebrow">FLYING RECENCY</p><h2>Monitored privileges</h2></div><span>{state.activeCategories.length?state.activeCategories.map(categoryLabel).join(" · "):"No active flying category"}</span></div>{flying.length?<div className="compliance-list compliance-list-secondary">{flying.map(item=><WorkspaceRow item={item} key={item.id}/>)}</div>:<div className="panel compliance-empty"><strong>No active recency evaluation</strong><p className="muted">Add the relevant licence, qualification or aircraft profile, or configure a Part-FCL monitor in Evidence & monitor settings.</p></div>}</section>
    <section className="compliance-credential-summary"><div><p className="eyebrow">CREDENTIAL VALIDITY</p><h2>{state.currentCredentialCount} of {state.credentialCount} current</h2><p className="muted">Expired, expiring or incomplete credentials are included in the action queue above. Current records stay compact here so this page does not become another long licence list.</p></div><div className="compliance-credential-actions"><span className={credentialAttention.length?"status-warning":"status-on"}>{credentialAttention.length?`${credentialAttention.length} NEED ATTENTION`:"ALL CURRENT"}</span><Link className="secondary-button" href="/credentials?view=licences">Licences & ratings</Link><Link className="secondary-button" href="/credentials?view=documents">Medical & documents</Link></div></section>
  </main></>;
}
