import { requireUser } from "@/lib/auth/require-user";
import { daysBetween,type RecencyRequirement } from "@/lib/recency-engine";
import { getRecencyStateForUser } from "@/lib/recency-service";
import { addRecencyEvidence,addRecencyRule,deleteRecencyEvidence,deleteRecencyRule,saveRecencyMonitors } from "@/app/(protected)/credentials/recency-actions";

const requirementValue=(item:RecencyRequirement)=>item.unit==="hours"?`${Math.floor(item.current)}:${String(Math.round((item.current-Math.floor(item.current))*60)).padStart(2,"0")} / ${Math.floor(item.target)}:${String(Math.round((item.target-Math.floor(item.target))*60)).padStart(2,"0")}`:`${Math.round(item.current)} / ${Math.round(item.target)}`;
const remainingValue=(item:RecencyRequirement)=>{if(item.met)return"Requirement met";if(item.unit==="count")return`${Math.max(0,Math.ceil(item.target-item.current))} remaining`;const minutes=Math.max(0,Math.ceil((item.target-item.current)*60));return`${Math.floor(minutes/60)}:${String(minutes%60).padStart(2,"0")} remaining`};
const statusClass=(status:string)=>`recency-status-${status}`;
const evidenceLabel=(kind:string)=>kind==="LAPL_PROFICIENCY_CHECK"?"LAPL(A) proficiency check":kind==="CLASS_PROFICIENCY_CHECK"?"Class proficiency check":"FCL.740.A refresher training";

export async function RecencyPanel(){
  const{userId}=await requireUser(),state=await getRecencyStateForUser(userId);
  const headline=state.reviewCount?`${state.reviewCount} REVIEW`:state.dueSoonCount?`${state.dueSoonCount} DUE SOON`:"ALL CURRENT";
  const headlineClass=state.reviewCount||state.dueSoonCount?"status-warning":"status-on";
  return <section className="panel recency-overview-panel"><div className="section-heading"><div><p className="eyebrow">RECENCY ENGINE · v1.35.2</p><h2>Recency & currency</h2><p className="muted">Monitor only the privileges and deadlines that matter to you. Forecasts assume no new qualifying activity is recorded.</p></div><span className={headlineClass}>{headline}</span></div>
    <details className="credential-create recency-monitor-settings"><summary>Choose what to monitor</summary><form action={saveRecencyMonitors}><div className="recency-monitor-list">{state.availableMonitors.map(item=><label key={item.id}><input type="checkbox" name="monitor" value={item.id} defaultChecked={state.enabled.has(item.id)}/><span><strong>{item.label}</strong><small>{item.detail}</small></span></label>)}</div><label className="recency-notification-setting"><span><strong>Proactive notification</strong><small>Notify you before a rolling requirement is expected to drop out.</small></span><select name="notification_days" defaultValue={state.notificationDays}><option value="0">Off</option><option value="7">7 days before</option><option value="14">14 days before</option><option value="30">30 days before</option></select></label><p className="muted recency-monitor-note">Night passenger currency is offered only when a Night rating or current IR is saved. Revalidation monitoring is offered only for a dated SEP/TMG qualification.</p><div className="form-actions"><button className="primary-button">Save monitoring</button></div></form></details>
    {state.evaluations.length?<div className="recency-grid-v135">{state.evaluations.map(item=><article className={`recency-card-v135 ${statusClass(item.status)}`} key={item.id}><header><div><span>{item.code} · {item.windowLabel}</span><h3>{item.title}</h3></div><b>{item.badge??(item.status==="current"?"CURRENT":item.status==="attention"?"REVIEW":"NOT CURRENT")}</b></header><p>{item.summary}</p>{item.requirements.length?<ul>{item.requirements.map(req=><li className={req.met?"met":"missing"} key={req.id}><span><span>{req.label}</span><small>{remainingValue(req)}</small></span><strong>{requirementValue(req)}</strong></li>)}</ul>:null}{item.forecastDate&&item.status==="current"?<div className="recency-forecast"><strong>Next drop-off</strong><span>{item.forecastDate} · {Math.max(0,daysBetween(state.today,item.forecastDate))} days</span><small>If no new qualifying activity is recorded.</small></div>:null}{item.deadline?<div className="recency-forecast"><strong>Rating deadline</strong><span>{item.deadline}</span></div>:null}{item.note?<small className="recency-card-note">{item.note}</small>:null}{state.customIds.has(item.id)?<form action={deleteRecencyRule} className="recency-rule-delete"><input type="hidden" name="id" value={item.id}/><button className="secondary-link">Remove custom rule</button></form>:null}</article>)}</div>:<p className="empty-state">No active recency monitors. Use “Choose what to monitor” or add a custom rule.</p>}
    {state.monitorDeadlines&&state.deadlineItems.length?<div className="recency-deadlines"><div><p className="eyebrow">DEADLINES</p><h3>Expiring or expired</h3></div><div>{state.deadlineItems.slice(0,6).map((item,index)=><span key={`${item.label}-${index}`}><strong>{item.label}</strong><small>{item.state.label}</small><b className={item.state.status==="expired"?"status-off":"status-warning"}>{item.state.status==="expired"?"EXPIRED":"DUE SOON"}</b></span>)}</div></div>:null}
    <details className="credential-create recency-evidence"><summary>Proficiency & revalidation evidence</summary><div className="recency-evidence-body"><p className="muted">Add completed checks or refresher training that are not reliably derivable from a normal logbook entry. These records are user-entered evidence, not a FlyTally certification or authority endorsement.</p>{state.evidence.length?<div className="recency-evidence-list">{state.evidence.slice(0,10).map(item=><article key={item.id}><div><span>{item.date} · {item.aircraftClass}</span><strong>{evidenceLabel(item.kind)}</strong><small>{item.signer} · {item.reference}{item.kind==="CLASS_REFRESHER"?` · ${item.minutes} min`:""}</small>{item.note?<small>{item.note}</small>:null}</div><form action={deleteRecencyEvidence}><input type="hidden" name="id" value={item.id}/><button className="secondary-link">Remove</button></form></article>)}</div>:null}<form action={addRecencyEvidence} className="form-grid settings-grid recency-evidence-form"><label>Evidence<select name="kind" defaultValue="LAPL_PROFICIENCY_CHECK"><option value="LAPL_PROFICIENCY_CHECK">LAPL(A) proficiency check</option><option value="CLASS_PROFICIENCY_CHECK">SEP/TMG proficiency check</option><option value="CLASS_REFRESHER">FCL.740.A refresher training</option></select></label><label>Class<select name="aircraft_class" defaultValue="SEP"><option>SEP</option><option>TMG</option></select></label><label>Date<input type="date" name="date" defaultValue={state.today} required/></label><label>Duration (minutes)<input type="number" name="minutes" min="0" max="1440" defaultValue="0"/><small>Used for refresher training; enter at least 60 minutes when applicable.</small></label><label>Examiner / instructor<input name="signer" maxLength={120} required/></label><label>Certificate / reference<input name="reference" maxLength={120} required/></label><label className="wide">Note<input name="note" maxLength={300}/></label><div className="form-actions wide"><button className="primary-button">Add evidence</button></div></form></div></details>
    <details className="credential-create recency-custom-create"><summary>Add custom currency rule</summary><form action={addRecencyRule} className="form-grid settings-grid"><label>Rule name<input name="label" maxLength={80} placeholder="e.g. Club checkout currency" required/></label><label>Rolling window<input type="number" name="window_days" min="1" max="3650" defaultValue="90" required/><small>Days</small></label><label>Metric<select name="metric" defaultValue="flight_hours"><option value="flight_hours">Flight time</option><option value="pic_hours">PIC time</option><option value="flights">Flights</option><option value="landings">Landings</option><option value="night_landings">Night landings</option></select></label><label>Target<input type="number" name="target" min="0.01" max="10000" step="0.01" defaultValue="1" required/><small>Hours for time metrics; count otherwise.</small></label><label>Evidence<select name="evidence" defaultValue="ANY"><option value="ANY">Any</option><option value="EASA">EASA</option><option value="ULL">ULL</option></select></label><label>Aircraft class<select name="aircraft_class" defaultValue="ANY"><option value="ANY">Any</option><option value="SEP">SEP</option><option value="TMG">TMG</option><option value="ULL">ULL</option></select></label><label>Role<select name="role" defaultValue="ANY"><option value="ANY">Any flying role</option><option value="PIC">PIC</option><option value="DUAL">DUAL</option><option value="SOLO">SOLO</option><option value="CO-PILOT">CO-PILOT</option></select></label><div className="form-actions"><button className="primary-button">Add rule</button></div></form></details>
  </section>;
}
