import { requireUser } from "@/lib/auth/require-user";
import { sql } from "@/lib/db";
import { credentialValidity } from "@/lib/credential-validity";
import { parsePilotPreferences } from "@/lib/logbook-print";
import { evaluateCustomRule,evaluateLaplA,evaluatePassengerCurrency,flightMinutes,parseCustomRecencyRules,type RecencyEvaluation,type RecencyFlight,type RecencyRequirement } from "@/lib/recency-engine";
import { addRecencyRule,deleteRecencyRule } from "@/app/(protected)/credentials/recency-actions";

const t=(value:unknown)=>String(value??"").trim();
const today=new Date().toISOString().slice(0,10);
const requirementValue=(item:RecencyRequirement)=>item.unit==="hours"?`${Math.floor(item.current)}:${String(Math.round((item.current-Math.floor(item.current))*60)).padStart(2,"0")} / ${Math.floor(item.target)}:${String(Math.round((item.target-Math.floor(item.target))*60)).padStart(2,"0")}`:`${Math.round(item.current)} / ${Math.round(item.target)}`;
const statusLabel=(status:string)=>status==="current"?"CURRENT":status==="attention"?"LIMITED":"NOT CURRENT";
const statusClass=(status:string)=>`recency-status-${status}`;

export async function RecencyPanel(){
  const{userId}=await requireUser();
  const[settings,licences,qualifications,expiries]=await Promise.all([
    sql`SELECT preferences_json FROM user_settings WHERE user_id=${userId} LIMIT 1` as Promise<Array<Record<string,unknown>>>,
    sql`SELECT licence_type,validity_mode,valid_until::text valid_until,recency_until::text recency_until FROM pilot_licences WHERE user_id=${userId} AND active=TRUE` as Promise<Array<Record<string,unknown>>>,
    sql`SELECT qualification_type,validity_mode,valid_until::text valid_until,recency_until::text recency_until FROM pilot_qualifications WHERE user_id=${userId} AND active=TRUE` as Promise<Array<Record<string,unknown>>>,
    sql`SELECT label,expiry_date::text expiry_date,warning_days FROM user_expiries WHERE user_id=${userId} AND UPPER(TRIM(category))<>'LICENCE' AND active=1 AND expiry_date<'9999-01-01' ORDER BY expiry_date` as Promise<Array<Record<string,unknown>>>,
  ]);
  const preferences=parsePilotPreferences(settings[0]?.preferences_json),customRules=parseCustomRecencyRules(preferences.recency_rules),maxDays=Math.max(730,...customRules.map(rule=>rule.windowDays));
  const rows=await sql`SELECT f.date,f.evidence,f.aircraft_class,f.role,f.off_block,f.on_block,f.landings_day,f.landings_night,f.purpose_code,f.task,f.note,EXISTS(SELECT 1 FROM flight_verifications v WHERE v.flight_id=f.id AND v.flight_user_id=f.user_id AND v.record_revision=COALESCE(f.record_revision,1) AND v.flight_hash=f.certification_hash AND v.verification_role='INSTRUCTOR' AND v.status='signed') instructor_signed FROM flights f WHERE f.user_id=${userId} AND f.certified_at IS NOT NULL AND CASE WHEN f.date~'^\\d{4}-\\d{2}-\\d{2}$' THEN f.date::date ELSE NULL END>=CURRENT_DATE-(${maxDays}::int*INTERVAL '1 day') ORDER BY f.date DESC,f.id DESC` as Array<Record<string,unknown>>;
  const flights:RecencyFlight[]=rows.map(row=>({date:t(row.date).slice(0,10),evidence:t(row.evidence),aircraftClass:t(row.aircraft_class),role:t(row.role),minutes:flightMinutes(row.off_block,row.on_block),landingsDay:Number(row.landings_day)||0,landingsNight:Number(row.landings_night)||0,purposeCode:t(row.purpose_code),task:t(row.task),note:t(row.note),instructorSigned:Boolean(row.instructor_signed)}));
  const hasLapl=licences.some(row=>t(row.licence_type).toUpperCase()==="LAPL(A)"),hasSep=hasLapl||qualifications.some(row=>t(row.qualification_type).toUpperCase().startsWith("SEP")),hasTmg=qualifications.some(row=>t(row.qualification_type).toUpperCase().startsWith("TMG"));
  const hasIr=qualifications.some(row=>{if(!t(row.qualification_type).toUpperCase().startsWith("IR"))return false;const state=credentialValidity({mode:row.validity_mode,validUntil:row.valid_until,recencyUntil:row.recency_until},today);return state.status!=="expired"&&state.status!=="incomplete"});
  const evaluations:RecencyEvaluation[]=[];if(hasLapl)evaluations.push(evaluateLaplA(flights,today));if(hasSep)evaluations.push(evaluatePassengerCurrency(flights,"SEP",hasIr,today));if(hasTmg)evaluations.push(evaluatePassengerCurrency(flights,"TMG",hasIr,today));evaluations.push(...customRules.map(rule=>evaluateCustomRule(rule,flights,today)));
  const deadlineItems=[...licences.map(row=>({label:t(row.licence_type),state:credentialValidity({mode:row.validity_mode,validUntil:row.valid_until,recencyUntil:row.recency_until},today)})),...qualifications.map(row=>({label:t(row.qualification_type),state:credentialValidity({mode:row.validity_mode,validUntil:row.valid_until,recencyUntil:row.recency_until},today)})),...expiries.map(row=>({label:t(row.label),state:credentialValidity({mode:"date",validUntil:row.expiry_date,warningDays:row.warning_days},today)}))].filter(item=>item.state.status==="warning"||item.state.status==="expired").sort((a,b)=>(a.state.daysRemaining??99999)-(b.state.daysRemaining??99999));
  const reviewCount=evaluations.filter(item=>item.status!=="current").length+deadlineItems.length,customIds=new Set(customRules.map(rule=>rule.id));
  return <section className="panel recency-overview-panel"><div className="section-heading"><div><p className="eyebrow">RECENCY ENGINE · v1.35</p><h2>Recency & currency</h2><p className="muted">Regulatory profiles activate from your saved licences and qualifications. Calculations use certified FlyTally records; authority records and applicable regulations remain controlling.</p></div><span className={reviewCount?"status-warning":"status-on"}>{reviewCount?`${reviewCount} REVIEW`:"ALL CURRENT"}</span></div>
    {evaluations.length?<div className="recency-grid-v135">{evaluations.map(item=><article className={`recency-card-v135 ${statusClass(item.status)}`} key={item.id}><header><div><span>{item.code} · {item.windowLabel}</span><h3>{item.title}</h3></div><b>{statusLabel(item.status)}</b></header><p>{item.summary}</p><ul>{item.requirements.map(req=><li className={req.met?"met":"missing"} key={req.id}><span>{req.label}</span><strong>{requirementValue(req)}</strong></li>)}</ul>{item.note?<small>{item.note}</small>:null}{customIds.has(item.id)?<form action={deleteRecencyRule} className="recency-rule-delete"><input type="hidden" name="id" value={item.id}/><button className="secondary-link">Remove custom rule</button></form>:null}</article>)}</div>:<p className="empty-state">Add a licence or a custom rule to start monitoring recency.</p>}
    {deadlineItems.length?<div className="recency-deadlines"><div><p className="eyebrow">DEADLINES</p><h3>Expiring or expired</h3></div><div>{deadlineItems.slice(0,6).map((item,index)=><span key={`${item.label}-${index}`}><strong>{item.label}</strong><small>{item.state.label}</small><b className={item.state.status==="expired"?"status-off":"status-warning"}>{item.state.status==="expired"?"EXPIRED":"DUE SOON"}</b></span>)}</div></div>:null}
    <details className="credential-create recency-custom-create"><summary>Add custom currency rule</summary><form action={addRecencyRule} className="form-grid settings-grid"><label>Rule name<input name="label" maxLength={80} placeholder="e.g. Club checkout currency" required/></label><label>Rolling window<input type="number" name="window_days" min="1" max="3650" defaultValue="90" required/><small>Days</small></label><label>Metric<select name="metric" defaultValue="flight_hours"><option value="flight_hours">Flight time</option><option value="pic_hours">PIC time</option><option value="flights">Flights</option><option value="landings">Landings</option><option value="night_landings">Night landings</option></select></label><label>Target<input type="number" name="target" min="0.01" max="10000" step="0.01" defaultValue="1" required/><small>Hours for time metrics; count otherwise.</small></label><label>Evidence<select name="evidence" defaultValue="ANY"><option value="ANY">Any</option><option value="EASA">EASA</option><option value="ULL">ULL</option></select></label><label>Aircraft class<select name="aircraft_class" defaultValue="ANY"><option value="ANY">Any</option><option value="SEP">SEP</option><option value="TMG">TMG</option><option value="ULL">ULL</option></select></label><label>Role<select name="role" defaultValue="ANY"><option value="ANY">Any flying role</option><option value="PIC">PIC</option><option value="DUAL">DUAL</option><option value="SOLO">SOLO</option><option value="CO-PILOT">CO-PILOT</option></select></label><div className="form-actions"><button className="primary-button">Add rule</button></div></form></details>
  </section>;
}
