import Link from "next/link";
import { requireUser } from "@/lib/auth/require-user";
import { sql } from "@/lib/db";
import { AircraftEndorsementPicker } from "@/components/aircraft-endorsement-picker";
import { addAircraftQualification } from "@/app/(protected)/credentials/aircraft-actions";

const t=(value:unknown)=>String(value??"").trim();
export async function TrainingFlightCandidates(){
  const{userId}=await requireUser();
  const[candidates,licences]=await Promise.all([
    sql`SELECT f.id,f.date::text date,f.registration,f.aircraft_make,f.aircraft_model,f.aircraft_variant,f.aircraft_type,f.aircraft_class,f.departure,f.arrival,f.instructor,f.purpose_code,f.task,COALESCE(f.record_revision,1)::int record_revision,
      (UPPER(COALESCE(f.purpose_code,''))='AIRCRAFT_DIFFERENCES' OR LOWER(COALESCE(f.task,'')) LIKE '%differences training%') differences,
      EXISTS(SELECT 1 FROM flight_verifications v WHERE v.flight_id=f.id AND v.flight_user_id=f.user_id AND v.record_revision=COALESCE(f.record_revision,1) AND v.flight_hash=f.certification_hash AND v.verification_role='INSTRUCTOR' AND v.status='signed') instructor_signed
      FROM flights f WHERE f.user_id=${userId} AND f.certified_at IS NOT NULL AND UPPER(COALESCE(f.evidence,''))='EASA'
      AND ((UPPER(COALESCE(f.purpose_code,'')) IN ('AIRCRAFT_DIFFERENCES','AIRCRAFT_FAMILIARISATION')) OR LOWER(COALESCE(f.task,'')) LIKE '%differences training%' OR LOWER(COALESCE(f.task,'')) LIKE '%familiarisation%')
      AND ((UPPER(COALESCE(f.purpose_code,''))='AIRCRAFT_FAMILIARISATION' OR LOWER(COALESCE(f.task,'')) LIKE '%familiarisation%') OR EXISTS(SELECT 1 FROM flight_verifications v WHERE v.flight_id=f.id AND v.flight_user_id=f.user_id AND v.record_revision=COALESCE(f.record_revision,1) AND v.flight_hash=f.certification_hash AND v.verification_role='INSTRUCTOR' AND v.status='signed'))
      AND NOT EXISTS(SELECT 1 FROM pilot_qualifications q WHERE q.user_id=f.user_id AND q.record_kind='aircraft_training' AND q.record_active IS TRUE AND q.certificate_reference=('FLYTALLY-FLIGHT:'||f.id::text||':R'||COALESCE(f.record_revision,1)::text))
      ORDER BY f.date DESC,f.id DESC LIMIT 20` as Promise<Array<Record<string,unknown>>>,
    sql`SELECT id,licence_type,licence_number FROM pilot_licences WHERE user_id=${userId} AND active=TRUE ORDER BY licence_type,licence_number,id` as Promise<Array<Record<string,unknown>>>,
  ]);
  if(!candidates.length)return null;
  return <details className="credential-create training-flight-candidates"><summary>Training flights ready to record · {candidates.length}</summary><div><p className="muted">These are certified flights already marked as differences training or familiarisation. Signed differences flights can prefill an aircraft-training record, but FlyTally still requires you to select the exact endorsement(s); the flight never grants a privilege automatically.</p>{candidates.map(row=>{const id=Number(row.id),revision=Math.max(1,Number(row.record_revision)||1),reference=`FLYTALLY-FLIGHT:${id}:R${revision}`,differences=Boolean(row.differences),aircraft=[t(row.aircraft_make),t(row.aircraft_model),t(row.aircraft_variant)].filter(Boolean).join(" ")||t(row.aircraft_type)||t(row.registration);return <details className="training-flight-candidate" key={reference}><summary><span><strong>{t(row.date)} · {aircraft}</strong><small>{t(row.departure)||"?"} → {t(row.arrival)||"?"} · {differences?"Differences training":"Familiarisation"}</small></span><small>{differences?"Instructor signed":"Certified source"}</small></summary><form action={addAircraftQualification} className="form-grid settings-grid training-flight-candidate-form"><input type="hidden" name="training_kind" value={differences?"differences":"familiarisation"}/><input type="hidden" name="completed_on" value={t(row.date).slice(0,10)}/><input type="hidden" name="certificate_reference" value={reference}/><label>Class or type<input name="class_or_type" defaultValue={t(row.aircraft_class)||t(row.aircraft_type)}/></label><label>Aircraft make<input name="aircraft_make" defaultValue={t(row.aircraft_make)}/></label><label>Model<input name="aircraft_model" defaultValue={t(row.aircraft_model)||t(row.aircraft_type)}/></label><label>Variant<input name="aircraft_variant" defaultValue={t(row.aircraft_variant)}/></label><label>Linked licence<select name="linked_licence_id" defaultValue=""><option value="">No specific licence</option>{licences.map(item=><option key={t(item.id)} value={t(item.id)}>{t(item.licence_type)} · {t(item.licence_number)}</option>)}</select></label><label>Instructor<input name="instructor_name" defaultValue={t(row.instructor)}/></label><label>Organisation<input name="training_organisation" placeholder="ATO / DTO / club / organisation"/></label><div><strong>Source flight</strong><small><Link href={`/flights/${id}`}>{t(row.registration)} · R{revision}</Link></small></div><AircraftEndorsementPicker/><label className="wide">Notes<textarea name="notes" rows={2} defaultValue={`Created from certified FlyTally flight ${t(row.registration)} ${t(row.date)} · R${revision}.`}/></label><div className="form-actions wide"><button className="primary-button">Create aircraft training record</button></div></form></details>})}</div></details>;
}
