import "server-only";
import { Resend } from "resend";

const esc=(value:string)=>value.replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[char]||char));
const shell=(preview:string,title:string,message:string,button:string,url:string,footer:string)=>`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${esc(preview)}</title></head><body style="margin:0;background:#071018;color:#eaf2f8;font-family:Arial,sans-serif"><div style="display:none;max-height:0;overflow:hidden">${esc(preview)}</div><div style="max-width:560px;margin:0 auto;padding:40px 20px"><div style="padding:30px;border:1px solid #20333f;border-radius:18px;background:#0b151e"><div style="color:#65c8b5;font-size:12px;font-weight:700;letter-spacing:.12em">FLYTALLY · PILOT LOGBOOK</div><h1 style="margin:16px 0 12px;font-size:28px;color:#f4f8fb">${esc(title)}</h1><p style="margin:0 0 24px;color:#a9bac7;font-size:16px;line-height:1.6">${esc(message)}</p><a href="${esc(url)}" style="display:inline-block;padding:13px 20px;border-radius:9px;background:#58d5c1;color:#061014;text-decoration:none;font-weight:800">${esc(button)}</a><p style="margin:24px 0 0;color:#718696;font-size:12px;line-height:1.5">${esc(footer)}</p></div><p style="color:#607585;font-size:11px;text-align:center">FlyTally · Digital pilot logbook</p></div></body></html>`;

function client(){const key=process.env.RESEND_API_KEY?.trim();if(!key)throw new Error("RESEND_API_KEY is not configured.");return new Resend(key);}
function from(){return process.env.AUTH_EMAIL_FROM?.trim()||"FlyTally <no-reply@mail.fly-tally.com>";}
export function emailConfigured(){return Boolean(process.env.RESEND_API_KEY?.trim());}

export async function sendInvitationEmail(to:string,url:string,inviteId:number){const{error}=await client().emails.send({from:from(),to,subject:"Your FlyTally private beta invitation",html:shell("Your FlyTally invitation","You are invited to FlyTally","A pilot has invited you to test FlyTally. Use the private link below to create your account. The invitation is bound to this email address and can only be used once.","Accept invitation",url,"This invitation expires automatically. If you were not expecting it, you can ignore this email.")},{headers:{"Idempotency-Key":`flytally-invite-${inviteId}`}});if(error)throw new Error(error.message);}
export async function sendPasswordResetEmail(to:string,url:string,resetId:number){const{error}=await client().emails.send({from:from(),to,subject:"Reset your FlyTally password",html:shell("Reset your FlyTally password","Reset your password","We received a request to reset the password for your FlyTally account. Use the secure link below to choose a new password.","Reset password",url,"This link expires in 30 minutes and can only be used once. If you did not request it, your password remains unchanged.")},{headers:{"Idempotency-Key":`flytally-password-reset-${resetId}`}});if(error)throw new Error(error.message);}
