import { serializeBilling } from "./billing.ts";
import { flightDateKey } from "./dashboard-math.ts";
import { allocatedFunctionTimes,defaultEngineType,durationMinutes,EASA_ROLES,ENGINE_TYPES,OPERATION_TYPES } from "./easa-logbook.ts";
import { flightPurposeTask,normalizeFlightPurposeCodes,primaryFlightPurposeCode,stripFlightPurposeTasks } from "./flight-purpose.ts";
import { regulatoryAircraftCategory,type RegulatoryAircraftCategory } from "./flight-entry-profile.ts";

export const EVIDENCE = ["ULL", "EASA"] as const;
export const CLASSES = ["ULL", "SEP", "TMG", "MEP", "SET", "OTHER", "GLIDER"] as const;
export const ROLES = [...EASA_ROLES,"PAX","OBSERVER"] as const;
export const BILLING = ["BLOCK", "AIR"] as const;
export const REGULATORY_CATEGORIES=["AEROPLANE","SAILPLANE","ULL","OTHER"] as const;
export const LAUNCH_METHODS=["WINCH","AEROTOW","SELF_LAUNCH","CAR","BUNGEE","OTHER"] as const;
export type FlightInput={date:string;registration:string;aircraftType:string;aircraftClass:string;regulatoryCategory:RegulatoryAircraftCategory;launchMethod:string;launches:number;evidence:string;departure:string;arrival:string;offBlock:string;takeoff:string;landing:string;onBlock:string;starts:number;operationType:string;engineType:string;landingsDay:number;landingsNight:number;movementEvidenceRecorded:boolean;takeoffsDay:number;takeoffsNight:number;approachesDay:number;approachesNight:number;nightMinutes:number;ifrMinutes:number;picMinutes:number;copilotMinutes:number;dualMinutes:number;instructorMinutes:number;verificationName:string;verificationReference:string;commander:string;instructor:string;role:string;task:string;purposeCode:string;billingBasis:string;note:string};
function text(form:FormData,name:string,max:number){return String(form.get(name)??"").trim().slice(0,max)}
function requiredOption<T extends readonly string[]>(value:string,values:T,label:string){if(!values.includes(value as T[number]))return{error:`Select a valid ${label}.`} as const;return{value:value as T[number]} as const}
function option<T extends readonly string[]>(value:string,values:T,fallback:T[number]){return values.includes(value as T[number])?value:fallback}
const counter=(form:FormData,name:string)=>Math.max(0,Math.min(99,Number.parseInt(text(form,name,2)||"0",10)||0));
const LEGACY_REFRESHER=/\bFCL[.]140[.]A\s+refresher\s+training\b\s*(?:[·|\-]\s*)?/i;

export function parseFlightInput(form:FormData):{data?:FlightInput;error?:string}{
  const date=text(form,"date",10);if(flightDateKey(date)!==date)return{error:"Enter a valid date."};const time=(name:string)=>text(form,name,5),times=[time("offBlock"),time("takeoff"),time("landing"),time("onBlock")];if(times.some(value=>value&&!/^([01]\d|2[0-3]):[0-5]\d$/.test(value)))return{error:"Times must use HH:MM format."};
  const minute=(value:string)=>value?Number(value.slice(0,2))*60+Number(value.slice(3)):null,delta=(a:string,b:string)=>{const start=minute(a),end=minute(b);return start===null||end===null?null:(end-start+1440)%1440},block=delta(times[0],times[3]),air=delta(times[1],times[2]),taxiOut=delta(times[0],times[1]),taxiIn=delta(times[2],times[3]);if(block!==null&&block>18*60)return{error:"BLOCK time exceeds 18 hours. Check Off-block and On-block."};if(air!==null&&block!==null&&air>block+5)return{error:"AIR time cannot exceed BLOCK time. Check the time order."};if((taxiOut!==null&&taxiOut>180)||(taxiIn!==null&&taxiIn>180))return{error:"Taxi time exceeds 3 hours. Check Off-block, takeoff, landing and On-block."};
  const registration=text(form,"registration",32).toUpperCase();if(!registration)return{error:"Select or enter an aircraft registration."};
  const evidenceResult=requiredOption(text(form,"evidence",8).toUpperCase(),EVIDENCE,"logbook");if("error" in evidenceResult)return evidenceResult;const classResult=requiredOption(text(form,"aircraftClass",16).toUpperCase(),CLASSES,"aircraft class");if("error" in classResult)return classResult;const roleResult=requiredOption(text(form,"role",24).toUpperCase(),ROLES,"pilot role");if("error" in roleResult)return roleResult;const billingResult=requiredOption(text(form,"billingBasis",8).toUpperCase(),BILLING,"billing time basis");if("error" in billingResult)return billingResult;
  const evidence=evidenceResult.value,aircraftClass=classResult.value,role=roleResult.value,billingBasis=billingResult.value,requestedRegulatory=text(form,"regulatoryCategory",16).toUpperCase(),regulatoryCategory=regulatoryAircraftCategory({regulatoryCategory:requestedRegulatory,aircraftClass,evidence});
  if(evidence==="ULL"&&regulatoryCategory!=="ULL")return{error:"ULL flights must use the ULL regulatory category."};
  if(aircraftClass==="GLIDER"&&regulatoryCategory!=="SAILPLANE")return{error:"A non-TMG glider must use the Sailplane / Part-SFCL regulatory category."};
  if(["SEP","MEP","SET"].includes(aircraftClass)&&regulatoryCategory!=="AEROPLANE")return{error:"This aircraft class must use the Aeroplane / Part-FCL regulatory category."};
  if(aircraftClass==="TMG"&&!["AEROPLANE","SAILPLANE"].includes(regulatoryCategory))return{error:"Select whether this TMG flight belongs to the Part-FCL aeroplane or SPL sailplane context."};
  const legacyStarts=Math.max(0,Math.min(99,Number.parseInt(text(form,"starts",2)||"0",10)||0)),hasLandings=form.has("landingsDay")||form.has("landingsNight"),landingsDay=counter(form,"landingsDay"),landingsNight=counter(form,"landingsNight"),hasLaunches=form.has("launches"),launches=regulatoryCategory==="SAILPLANE"&&aircraftClass!=="TMG"?(hasLaunches?counter(form,"launches"):0):0,launchRaw=text(form,"launchMethod",20).toUpperCase(),launchMethod=LAUNCH_METHODS.includes(launchRaw as typeof LAUNCH_METHODS[number])?launchRaw:"";
  if(regulatoryCategory==="SAILPLANE"&&aircraftClass!=="TMG"&&hasLaunches&&launches<1)return{error:"Enter at least one sailplane launch for this flight."};
  if(launches>0&&!launchMethod)return{error:"Select the launch method used for this sailplane flight."};
  const starts=regulatoryCategory==="SAILPLANE"&&aircraftClass!=="TMG"?launches:hasLandings?landingsDay+landingsNight:legacyStarts;
  const instructor=text(form,"instructor",100),operationType=option(text(form,"operationType",2).toUpperCase(),OPERATION_TYPES,"SP"),engineType=option(text(form,"engineType",2).toUpperCase(),ENGINE_TYPES,defaultEngineType(aircraftClass)),nightMinutes=durationMinutes(form.get("nightTime")),ifrMinutes=durationMinutes(form.get("ifrTime")),blockMinutes=block??0,airMinutes=air??0,creditedMinutes=regulatoryCategory==="SAILPLANE"?(airMinutes||blockMinutes):blockMinutes;if(block!==null&&(nightMinutes>blockMinutes||ifrMinutes>blockMinutes))return{error:"Night and IFR time cannot exceed BLOCK time."};
  const splTmg=regulatoryCategory==="SAILPLANE"&&aircraftClass==="TMG",movementEvidenceRecorded=evidence==="EASA"&&regulatoryCategory==="AEROPLANE"&&String(form.get("movementEvidenceRecorded")??"")==="yes",takeoffsDay=splTmg?counter(form,"takeoffsDay"):movementEvidenceRecorded?counter(form,"takeoffsDay"):0,takeoffsNight=splTmg?counter(form,"takeoffsNight"):movementEvidenceRecorded?counter(form,"takeoffsNight"):0,approachesDay=movementEvidenceRecorded?counter(form,"approachesDay"):0,approachesNight=movementEvidenceRecorded?counter(form,"approachesNight"):0;
  const verificationName=text(form,"verificationName",160),verificationReference=text(form,"verificationReference",160);if(evidence==="EASA"&&["SPIC","PICUS"].includes(role)&&(!verificationName||!verificationReference))return{error:"SPIC and PICUS entries require the supervising pilot's name and countersignature reference."};
  const allocation=allocatedFunctionTimes(role,creditedMinutes),rawTask=text(form,"task",160),hasPurposeField=form.has("purposeSelectionPresent")||form.has("purposeCode"),selectedPurposes=normalizeFlightPurposeCodes(form.getAll("purposeCode")),legacyPurposes=!hasPurposeField&&role==="DUAL"&&LEGACY_REFRESHER.test(rawTask)?["LAPL_FCL140A_REFRESHER"] as const:[],allowedPurposes=role==="DUAL"?selectedPurposes:instructor?selectedPurposes.filter(code=>code==="AIRCRAFT_DIFFERENCES"||code==="AIRCRAFT_FAMILIARISATION"):[],purposes=allowedPurposes.length?allowedPurposes:legacyPurposes,purposeCode=primaryFlightPurposeCode(purposes),cleanTask=hasPurposeField?stripFlightPurposeTasks(rawTask):rawTask,purposeTask=flightPurposeTask(purposes),task=purposeTask?`${purposeTask}${cleanTask?` · ${cleanTask}`:""}`.slice(0,160):cleanTask;
  return{data:{date,registration,aircraftType:text(form,"aircraftType",80),aircraftClass,regulatoryCategory,launchMethod,launches,evidence,departure:text(form,"departure",16).toUpperCase(),arrival:text(form,"arrival",16).toUpperCase(),offBlock:times[0],takeoff:times[1],landing:times[2],onBlock:times[3],starts,operationType,engineType,landingsDay:hasLandings?landingsDay:starts,landingsNight:hasLandings?landingsNight:0,movementEvidenceRecorded,takeoffsDay,takeoffsNight,approachesDay,approachesNight,nightMinutes,ifrMinutes,...allocation,verificationName,verificationReference,commander:text(form,"commander",100),instructor,role,task,purposeCode,billingBasis:serializeBilling(billingBasis,text(form,"billingShare",2)),note:text(form,"note",2000)}};
}
