import "server-only";
import {createHash,randomBytes} from "node:crypto";
import {sql} from "@/lib/db";
import {getFlightTracks,type TrackPoint} from "@/lib/data/tracks";

export type PublicFlight={departure:string;arrival:string;date:string;aircraftType:string;registration:string;blockMinutes:number;landings:number;distanceKm:number;points:TrackPoint[]};
export type FlightShareOptions={showRegistration?:boolean;showDate?:boolean;showTrack?:boolean};
const hash=(token:string)=>createHash("sha256").update(token).digest("hex");
let ready:Promise<void>|undefined;
async function ensureShares(){if(!ready)ready=(async()=>{await sql`CREATE TABLE IF NOT EXISTS flight_public_shares(id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL,flight_id BIGINT NOT NULL,token_hash TEXT NOT NULL UNIQUE,show_registration BOOLEAN NOT NULL DEFAULT FALSE,show_date BOOLEAN NOT NULL DEFAULT TRUE,show_track BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),revoked_at TIMESTAMPTZ,CONSTRAINT flight_public_shares_owner_fk FOREIGN KEY(flight_id,user_id) REFERENCES flights(id,user_id) ON DELETE CASCADE)`;await sql`CREATE INDEX IF NOT EXISTS idx_flight_public_shares_owner ON flight_public_shares(user_id,flight_id,created_at DESC)`})().catch(e=>{ready=undefined;throw e});return ready}
export async function createFlightShare(userId:number,flightId:number,options:FlightShareOptions={}){await ensureShares();const owned=await sql`SELECT id FROM flights WHERE id=${flightId} AND user_id=${userId} LIMIT 1` as Array<{id:number}>;if(!owned[0])throw new Error("Flight not found");await sql`UPDATE flight_public_shares SET revoked_at=NOW() WHERE user_id=${userId} AND flight_id=${flightId} AND revoked_at IS NULL`;const token=randomBytes(24).toString("base64url");await sql`INSERT INTO flight_public_shares(user_id,flight_id,token_hash,show_registration,show_date,show_track) VALUES(${userId},${flightId},${hash(token)},${Boolean(options.showRegistration)},${options.showDate!==false},${options.showTrack!==false})`;return token}
export async function revokeFlightShares(userId:number,flightId:number){await ensureShares();await sql`UPDATE flight_public_shares SET revoked_at=NOW() WHERE user_id=${userId} AND flight_id=${flightId} AND revoked_at IS NULL`}
export async function hasActiveFlightShare(userId:number,flightId:number){await ensureShares();const rows=await sql`SELECT id FROM flight_public_shares WHERE user_id=${userId} AND flight_id=${flightId} AND revoked_at IS NULL LIMIT 1`;return Boolean(rows[0])}
function minutes(a:unknown,b:unknown){const p=(v:unknown)=>{const m=/^(\d{2}):(\d{2})$/.exec(String(v??""));return m?Number(m[1])*60+Number(m[2]):0},x=p(a),y=p(b);return x&&y?(y-x+1440)%1440:0}
export async function getPublicFlight(token:string):Promise<PublicFlight|null>{if(!/^[A-Za-z0-9_-]{20,80}$/.test(token))return null;await ensureShares();const rows=await sql`SELECT s.user_id,s.flight_id,s.show_registration,s.show_date,s.show_track,f.date,f.departure,f.arrival,f.registration,f.aircraft_type,f.aircraft_make,f.aircraft_model,f.off_block,f.on_block,COALESCE(f.landings_day,0)+COALESCE(f.landings_night,0) landings FROM flight_public_shares s JOIN flights f ON f.id=s.flight_id AND f.user_id=s.user_id WHERE s.token_hash=${hash(token)} AND s.revoked_at IS NULL LIMIT 1` as Array<Record<string,unknown>>;const r=rows[0];if(!r)return null;const tracks=Boolean(r.show_track)?await getFlightTracks(Number(r.user_id),Number(r.flight_id)):[];return{departure:String(r.departure??""),arrival:String(r.arrival??""),date:Boolean(r.show_date)?String(r.date??""):"",aircraftType:[r.aircraft_make,r.aircraft_model].map(x=>String(x??"").trim()).filter(Boolean).join(" ")||String(r.aircraft_type??""),registration:Boolean(r.show_registration)?String(r.registration??""):"",blockMinutes:minutes(r.off_block,r.on_block),landings:Number(r.landings??0),distanceKm:tracks.reduce((s,t)=>s+t.distanceKm,0),points:tracks.flatMap(t=>t.points).slice(0,1800)} }
