import "server-only";
export type KmlPoint={lat:number;lon:number;alt:number|null;time:string|null};
const clean=(v:string)=>v.replace(/<!\[CDATA\[|\]\]>/g,"").trim();
function coord(value:string):KmlPoint|null{const p=clean(value).trim().replaceAll(","," ").split(/\s+/).map(Number);if(p.length<2||!Number.isFinite(p[0])||!Number.isFinite(p[1])||p[1]<-90||p[1]>90||p[0]<-180||p[0]>180)return null;return {lon:p[0],lat:p[1],alt:Number.isFinite(p[2])?p[2]:null,time:null};}
export function parseKml(source:string){const points:KmlPoint[]=[];const track=source.match(/<(?:\w+:)?Track\b[^>]*>([\s\S]*?)<\/(?:\w+:)?Track>/i)?.[1];if(track){const times=[...track.matchAll(/<when\b[^>]*>([\s\S]*?)<\/when>/gi)].map(m=>clean(m[1]));const coords=[...track.matchAll(/<(?:\w+:)?coord\b[^>]*>([\s\S]*?)<\/(?:\w+:)?coord>/gi)].map(m=>coord(m[1])).filter(Boolean) as KmlPoint[];coords.forEach((p,i)=>{p.time=times[i]||null;points.push(p)})}
  if(points.length<2){for(const pm of source.matchAll(/<Placemark\b[^>]*>([\s\S]*?)<\/Placemark>/gi)){const body=pm[1],match=body.match(/<coordinates\b[^>]*>([\s\S]*?)<\/coordinates>/i);if(!match)continue;const explicit=body.match(/<when\b[^>]*>([\s\S]*?)<\/when>/i)?.[1],fr24=body.match(/(\d{4}-\d{2}-\d{2})[ T](\d{2}:\d{2}:\d{2})\s*UTC/i);const time=explicit||(fr24?`${fr24[1]}T${fr24[2]}Z`:null);for(const token of clean(match[1]).split(/\s+/)){const p=coord(token);if(p){p.time=time;points.push(p)}}}}
  if(points.length<2){for(const block of source.matchAll(/<coordinates\b[^>]*>([\s\S]*?)<\/coordinates>/gi))for(const token of clean(block[1]).split(/\s+/)){const p=coord(token);if(p)points.push(p)}}
  const unique=points.filter((p,i,a)=>!i||p.lat!==a[i-1].lat||p.lon!==a[i-1].lon||p.time!==a[i-1].time);const timed=unique.filter(p=>p.time&&Number.isFinite(Date.parse(p.time)));if(timed.length>=2)unique.sort((a,b)=>(a.time?Date.parse(a.time):Infinity)-(b.time?Date.parse(b.time):Infinity));return unique;
}
const hav=(a:KmlPoint,b:KmlPoint)=>{const r=6371.0088,p=Math.PI/180,dlat=(b.lat-a.lat)*p,dlon=(b.lon-a.lon)*p,q=Math.sin(dlat/2)**2+Math.cos(a.lat*p)*Math.cos(b.lat*p)*Math.sin(dlon/2)**2;return 2*r*Math.asin(Math.sqrt(q))};
export function trackStats(points:KmlPoint[]){const alts=points.map(p=>p.alt).filter((v):v is number=>v!==null&&v!==0),timed=points.filter(p=>p.time);return {pointCount:points.length,distanceKm:points.slice(1).reduce((n,p,i)=>n+hav(points[i],p),0),startUtc:timed[0]?.time??null,endUtc:timed[timed.length-1]?.time??null,minAlt:alts.length?Math.min(...alts):null,maxAlt:alts.length?Math.max(...alts):null};}
export function overview(points:KmlPoint[],max=180){if(points.length<=max)return points;const step=Math.ceil(points.length/max);const out=points.filter((_,i)=>i===0||i===points.length-1||i%step===0);if(out.at(-1)!==points.at(-1))out.push(points.at(-1)!);return out.slice(0,max);}
export function localParts(iso:string|null){if(!iso)return null;const date=new Date(iso);if(Number.isNaN(date.getTime()))return null;const parts=Object.fromEntries(new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Prague",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(date).map(p=>[p.type,p.value]));return {date:`${parts.year}-${parts.month}-${parts.day}`,time:`${parts.hour}:${parts.minute}`};}
export function suggestedSplits(points:KmlPoint[]){const out:number[]=[];for(let i=1;i<points.length;i++){const a=points[i-1],b=points[i];if(!a.time||!b.time)continue;const seconds=(Date.parse(b.time)-Date.parse(a.time))/1000;if(!Number.isFinite(seconds)||seconds<600)continue;const endpoint=hav(a,b);if((seconds>=3600&&endpoint<=50)||(seconds>=1200&&endpoint<=12)||seconds>=5400)out.push(i-1)}return out.filter((v,i,a)=>!i||v-a[i-1]>=5);}
export function splitPoints(points:KmlPoint[],indices:number[]){if(!indices.length)return [points];const parts:KmlPoint[][]=[];let start=0;for(const raw of indices){const idx=Math.max(1,Math.min(points.length-2,raw)),part=points.slice(start,idx+1);if(part.length>=2)parts.push(part);start=idx+1}const tail=points.slice(start);if(tail.length>=2)parts.push(tail);return parts.length?parts:[points];}
