import "server-only";
export type KmlPoint={lat:number;lon:number;alt:number|null;time:string|null};
const clean=(v:string)=>v.replace(/<!\[CDATA\[|\]\]>/g,"").trim();
function coord(value:string):KmlPoint|null{const p=clean(value).trim().replaceAll(","," ").split(/\s+/).map(Number);if(p.length<2||!Number.isFinite(p[0])||!Number.isFinite(p[1])||p[1]<-90||p[1]>90||p[0]<-180||p[0]>180)return null;return {lon:p[0],lat:p[1],alt:Number.isFinite(p[2])?p[2]:null,time:null};}
export function parseKml(source:string){const points:KmlPoint[]=[];for(const match of source.matchAll(/<(?:\w+:)?Track\b[^>]*>([\s\S]*?)<\/(?:\w+:)?Track>/gi)){const track=match[1],times=[...track.matchAll(/<when\b[^>]*>([\s\S]*?)<\/when>/gi)].map(m=>clean(m[1]));const coords=[...track.matchAll(/<(?:\w+:)?coord\b[^>]*>([\s\S]*?)<\/(?:\w+:)?coord>/gi)].map(m=>coord(m[1])).filter(Boolean) as KmlPoint[];coords.forEach((p,i)=>{p.time=times[i]||null;points.push(p)})}
  if(points.length<2){for(const pm of source.matchAll(/<Placemark\b[^>]*>([\s\S]*?)<\/Placemark>/gi)){const body=pm[1],match=body.match(/<coordinates\b[^>]*>([\s\S]*?)<\/coordinates>/i);if(!match)continue;const explicit=body.match(/<when\b[^>]*>([\s\S]*?)<\/when>/i)?.[1],fr24=body.match(/(\d{4}-\d{2}-\d{2})[ T](\d{2}:\d{2}:\d{2})\s*UTC/i);const time=explicit||(fr24?`${fr24[1]}T${fr24[2]}Z`:null);for(const token of clean(match[1]).split(/\s+/)){const p=coord(token);if(p){p.time=time;points.push(p)}}}}
  if(points.length<2){for(const block of source.matchAll(/<coordinates\b[^>]*>([\s\S]*?)<\/coordinates>/gi))for(const token of clean(block[1]).split(/\s+/)){const p=coord(token);if(p)points.push(p)}}
  const unique=points.filter((p,i,a)=>!i||p.lat!==a[i-1].lat||p.lon!==a[i-1].lon||p.time!==a[i-1].time);const timed=unique.filter(p=>p.time&&Number.isFinite(Date.parse(p.time)));if(timed.length>=2)unique.sort((a,b)=>(a.time?Date.parse(a.time):Infinity)-(b.time?Date.parse(b.time):Infinity));return unique;
}
function parseGpx(source:string){const points:KmlPoint[]=[];for(const m of source.matchAll(/<(?:\w+:)?(?:trkpt|rtept)\b([^>]*)>([\s\S]*?)<\/(?:\w+:)?(?:trkpt|rtept)>/gi)){const attrs=m[1],body=m[2],lat=Number(attrs.match(/\blat=["']([^"']+)/i)?.[1]),lon=Number(attrs.match(/\blon=["']([^"']+)/i)?.[1]);if(!Number.isFinite(lat)||!Number.isFinite(lon)||Math.abs(lat)>90||Math.abs(lon)>180)continue;const alt=Number(body.match(/<(?:\w+:)?ele\b[^>]*>([^<]+)/i)?.[1]),time=clean(body.match(/<(?:\w+:)?time\b[^>]*>([^<]+)/i)?.[1]||"")||null;points.push({lat,lon,alt:Number.isFinite(alt)?alt:null,time})}return points}
function parseCsv(source:string){const lines=source.replace(/^\uFEFF/,"").split(/\r?\n/).filter(Boolean);if(lines.length<2)return[];const delimiter=(lines[0].match(/;/g)?.length||0)>(lines[0].match(/,/g)?.length||0)?";":lines[0].includes("\t")?"\t":",";const cells=(line:string)=>line.split(delimiter).map(v=>v.trim().replace(/^"|"$/g,"").replaceAll('""','"')),headers=cells(lines[0]).map(x=>x.toLowerCase().replace(/[^a-z0-9]/g,"")),at=(names:string[])=>headers.findIndex(h=>names.includes(h)),latI=at(["lat","latitude","latitudedeg"]),lonI=at(["lon","lng","longitude","longitudedeg"]),altI=at(["alt","altitude","elevation","ele","altm"]),timeI=at(["time","timestamp","datetime","utc","dateandtime"]);if(latI<0||lonI<0)return[];return lines.slice(1).map(line=>{const c=cells(line),lat=Number(c[latI]?.replace(",",".")),lon=Number(c[lonI]?.replace(",",".")),alt=Number(c[altI]?.replace(",",".")),time=c[timeI]?.trim()||null;if(!Number.isFinite(lat)||!Number.isFinite(lon)||Math.abs(lat)>90||Math.abs(lon)>180)return null;return{lat,lon,alt:Number.isFinite(alt)?alt:null,time}}).filter(Boolean) as KmlPoint[]}
export function parseTrackFile(source:string,fileName=""){const lower=fileName.toLowerCase(),points=lower.endsWith(".gpx")||/<(?:\w+:)?gpx\b/i.test(source)?parseGpx(source):lower.endsWith(".csv")||(!source.includes("<")&&/[;,\t]/.test(source.split(/\r?\n/,1)[0]))?parseCsv(source):parseKml(source);const unique=points.filter((p,i,a)=>!i||p.lat!==a[i-1].lat||p.lon!==a[i-1].lon||p.time!==a[i-1].time),timed=unique.filter(p=>p.time&&Number.isFinite(Date.parse(p.time!)));if(timed.length>=2)unique.sort((a,b)=>(a.time?Date.parse(a.time):Infinity)-(b.time?Date.parse(b.time):Infinity));return unique}
const hav=(a:KmlPoint,b:KmlPoint)=>{const r=6371.0088,p=Math.PI/180,dlat=(b.lat-a.lat)*p,dlon=(b.lon-a.lon)*p,q=Math.sin(dlat/2)**2+Math.cos(a.lat*p)*Math.cos(b.lat*p)*Math.sin(dlon/2)**2;return 2*r*Math.asin(Math.sqrt(q))};
export function trackStats(points:KmlPoint[]){const alts=points.map(p=>p.alt).filter((v):v is number=>v!==null&&v!==0),timed=points.filter(p=>p.time);return {pointCount:points.length,distanceKm:points.slice(1).reduce((n,p,i)=>n+hav(points[i],p),0),startUtc:timed[0]?.time??null,endUtc:timed[timed.length-1]?.time??null,minAlt:alts.length?Math.min(...alts):null,maxAlt:alts.length?Math.max(...alts):null};}
export function overview(points:KmlPoint[],max=180){if(points.length<=max)return points;const step=Math.ceil(points.length/max);const out=points.filter((_,i)=>i===0||i===points.length-1||i%step===0);if(out.at(-1)!==points.at(-1))out.push(points.at(-1)!);return out.slice(0,max);}
export function localParts(iso:string|null){if(!iso)return null;const date=new Date(iso);if(Number.isNaN(date.getTime()))return null;const parts=Object.fromEntries(new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Prague",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(date).map(p=>[p.type,p.value]));return {date:`${parts.year}-${parts.month}-${parts.day}`,time:`${parts.hour}:${parts.minute}`};}
function seconds(a:KmlPoint,b:KmlPoint){if(!a.time||!b.time)return 0;const n=(Date.parse(b.time)-Date.parse(a.time))/1000;return Number.isFinite(n)&&n>0?n:0;}
function speeds(points:KmlPoint[]){return points.map((p,i)=>{if(!i)return 0;const s=seconds(points[i-1],p);return s?Math.min(800,hav(points[i-1],p)/(s/3600)):0})}
function groundEvents(points:KmlPoint[]){const v=speeds(points),events:Array<{start:number;end:number;duration:number}>=[];let start=-1;for(let i=2;i<v.length-2;i++){const slow=v[i]<22;if(slow&&start<0&&v.slice(Math.max(0,i-8),i).some(x=>x>45))start=i;if(start>=0&&!slow&&v.slice(i,Math.min(v.length,i+8)).some(x=>x>45)){const duration=seconds(points[start],points[i]);if(duration>0)events.push({start,end:i,duration});start=-1}}return events;}
export function suggestedSplits(points:KmlPoint[]){const out:number[]=[];for(let i=1;i<points.length;i++){const a=points[i-1],b=points[i],gap=seconds(a,b);if(gap<600)continue;const endpoint=hav(a,b);if((gap>=3600&&endpoint<=50)||(gap>=1200&&endpoint<=12)||gap>=5400)out.push(i-1)}for(const event of groundEvents(points))if(event.duration>=90)out.push(Math.round((event.start+event.end)/2));return [...new Set(out)].sort((a,b)=>a-b).filter((v,i,a)=>v>2&&v<points.length-3&&(!i||v-a[i-1]>=5));}
export function landingCount(points:KmlPoint[]){const touches=groundEvents(points).filter(e=>e.duration>5&&e.duration<90).length;return Math.max(1,1+touches);}
export function splitPoints(points:KmlPoint[],indices:number[]){if(!indices.length)return [points];const parts:KmlPoint[][]=[];let start=0;for(const raw of indices){const idx=Math.max(1,Math.min(points.length-2,raw)),part=points.slice(start,idx+1);if(part.length>=2)parts.push(part);start=idx+1}const tail=points.slice(start);if(tail.length>=2)parts.push(tail);return parts.length?parts:[points];}
