"use server";import { revalidatePath } from "next/cache";import { requireUser } from "@/lib/auth/require-user";import { hashLegacyPassword,verifyLegacyPassword } from "@/lib/auth/password";import { sql } from "@/lib/db";import { normalizeLogbookPrintScope,parsePilotPreferences } from "@/lib/logbook-print";
const s=(f:FormData,k:string)=>String(f.get(k)??"").trim();
async function currentSettings(userId:number){const rows=await sql`SELECT timezone,currency,home_airport,default_role,preferences_json FROM user_settings WHERE user_id=${userId}` as Array<Record<string,unknown>>;const row=rows[0]??{};return{row,preferences:parsePilotPreferences(row.preferences_json)}}
const pick=(f:FormData,key:string,fallback:unknown)=>f.has(key)?s(f,key):String(fallback??"").trim();
export async function saveProfile(f:FormData){const {userId}=await requireUser();const name=s(f,"display_name"),email=s(f,"email").toLowerCase();if(!name||!email)return;await sql`UPDATE users SET display_name=${name},email=${email},updated_at=NOW() WHERE id=${userId}`;revalidatePath("/profile");revalidatePath("/print");}
export async function saveSettings(f:FormData){
  const {userId}=await requireUser(),current=await currentSettings(userId),existing=current.preferences,row=current.row;
  const easaAddress=pick(f,"easa_address",existing.easa_address??existing.pilot_address).slice(0,500),easaLicence=pick(f,"easa_licence_number",existing.easa_licence_number??existing.licence_number).slice(0,80),ullAddress=pick(f,"ull_address",existing.ull_address).slice(0,500),ullLicence=pick(f,"ull_licence_number",existing.ull_licence_number).slice(0,80);
  const includeAux=f.has("print_include_auxiliary_roles")?s(f,"print_include_auxiliary_roles")==="yes":Boolean(existing.print_include_auxiliary_roles);
  const preferences=JSON.stringify({...existing,default_evidence:pick(f,"default_evidence",existing.default_evidence)||"ULL",pilot_address:easaAddress,licence_number:easaLicence,easa_address:easaAddress,easa_licence_number:easaLicence,ull_address:ullAddress,ull_licence_number:ullLicence,print_default_scope:normalizeLogbookPrintScope(pick(f,"print_default_scope",existing.print_default_scope)),print_include_auxiliary_roles:includeAux});
  const timezone=pick(f,"timezone",row.timezone)||"Europe/Prague",currency=pick(f,"currency",row.currency)||"CZK",homeAirport=pick(f,"home_airport",row.home_airport).toUpperCase(),defaultRole=pick(f,"default_role",row.default_role)||"PIC";
  await sql`INSERT INTO user_settings(user_id,timezone,currency,home_airport,default_role,preferences_json,created_at,updated_at) VALUES(${userId},${timezone},${currency},${homeAirport},${defaultRole},${preferences},NOW(),NOW()) ON CONFLICT(user_id) DO UPDATE SET timezone=EXCLUDED.timezone,currency=EXCLUDED.currency,home_airport=EXCLUDED.home_airport,default_role=EXCLUDED.default_role,preferences_json=EXCLUDED.preferences_json,updated_at=NOW()`;
  revalidatePath("/profile");revalidatePath("/print");revalidatePath("/data");
}
export async function addExpiry(f:FormData){const {userId}=await requireUser();const label=s(f,"label"),date=s(f,"expiry_date");if(!label||!date)return;await sql`INSERT INTO user_expiries(user_id,category,label,expiry_date,warning_days,note,active,created_at,updated_at) VALUES(${userId},${s(f,"category")||"Document"},${label},${date},${Number(s(f,"warning_days"))||30},${s(f,"note")},1,NOW(),NOW())`;revalidatePath("/profile");}
export async function toggleExpiry(f:FormData){const {userId}=await requireUser();await sql`UPDATE user_expiries SET active=CASE WHEN active=1 THEN 0 ELSE 1 END,updated_at=NOW() WHERE id=${Number(s(f,"id"))} AND user_id=${userId}`;revalidatePath("/profile");}
export async function deleteExpiry(f:FormData){const {userId}=await requireUser();await sql`DELETE FROM user_expiries WHERE id=${Number(s(f,"id"))} AND user_id=${userId}`;revalidatePath("/profile");}
export async function changePassword(f:FormData){const {userId}=await requireUser();const current=s(f,"current_password"),next=s(f,"new_password"),confirm=s(f,"confirm_password");if(next.length<10||next!==confirm)return;const rows=await sql`SELECT password_hash FROM user_credentials WHERE user_id=${userId}` as Array<{password_hash:string}>;if(!rows[0]||!await verifyLegacyPassword(current,rows[0].password_hash))return;const hash=await hashLegacyPassword(next);await sql`UPDATE user_credentials SET password_hash=${hash},updated_at=NOW() WHERE user_id=${userId}`;}
