import { requireUser } from "@/lib/auth/require-user";
import { getProfileData } from "@/lib/data/profile";
import { EASA_ROLES } from "@/lib/easa-logbook";
import { LOGBOOK_PRINT_SCOPES,normalizeLogbookPrintScope,parsePilotPreferences } from "@/lib/logbook-print";
import { addExpiry,changePassword,deleteExpiry,saveProfile,saveSettings,toggleExpiry } from "./actions";
export const metadata={title:"Profile & settings | FlyTally"};
const t=(v:unknown)=>String(v??"");
function expiryState(value:unknown,warning:unknown){const days=Math.ceil((new Date(t(value)).getTime()-Date.now())/86400000);return {days,label:days<0?`Expired ${Math.abs(days)} days ago`:days===0?'Expires today':`${days} days`,className:days<0?'expired':days<=Number(warning||30)?'warning':'valid'};}

export default async function ProfilePage(){
  const {userId}=await requireUser();const d=await getProfileData(userId),preferences=parsePilotPreferences(d.settings.preferences_json);
  const easaAddress=t(preferences.easa_address)||t(preferences.pilot_address),easaLicence=t(preferences.easa_licence_number)||t(preferences.licence_number),ullAddress=t(preferences.ull_address),ullLicence=t(preferences.ull_licence_number),printScope=normalizeLogbookPrintScope(preferences.print_default_scope);
  return <>
    <header className="page-header"><div><p className="eyebrow">PILOT ACCOUNT</p><h1>Profile & settings</h1><p className="muted">Personal details, logbook identities, export defaults and account settings.</p></div></header>
    <section className="profile-stats"><div><span>Profile</span><strong>#{t(d.user.id)}</strong><small>{t(d.user.role)}</small></div><div><span>Flights</span><strong>{t(d.stats.flights)||'0'}</strong></div><div><span>Aircraft</span><strong>{t(d.stats.aircraft)||'0'}</strong></div><div><span>GPS</span><strong>{t(d.stats.tracks)||'0'}</strong></div></section>
    <section className="recency-grid"><article><span>Last flight</span><strong>{t(d.recency.last_flight)||'—'}</strong></article><article><span>ULL · 90 days</span><strong>{t(d.recency.ull_landings_90)||'0'} landings</strong><small>last {t(d.recency.last_ull)||'—'}</small></article><article><span>EASA · 90 days</span><strong>{t(d.recency.easa_landings_90)||'0'} landings</strong><small>last {t(d.recency.last_easa)||'—'}</small></article></section>

    <div className="profile-grid">
      <section className="panel"><p className="eyebrow">PROFILE</p><h2>Personal details</h2><form action={saveProfile} className="stack-form"><label>Name<input name="display_name" defaultValue={t(d.user.display_name)} required/></label><label>Email<input name="email" type="email" defaultValue={t(d.user.email)} required/></label><button className="primary-button">Save profile</button></form></section>
      <section className="panel"><p className="eyebrow">LOGBOOK IDENTITIES</p><h2>EASA and ULL</h2><form action={saveSettings} className="stack-form"><div className="settings-subsection"><strong>EASA logbook</strong><small>Used for EASA-only print and shown together with the ULL identity in combined exports.</small></div><label>EASA address<textarea name="easa_address" rows={3} defaultValue={easaAddress} placeholder="Address for the EASA pilot logbook"/></label><label>EASA licence number<input name="easa_licence_number" defaultValue={easaLicence} placeholder="EASA licence number"/></label><div className="settings-subsection"><strong>ULL logbook</strong><small>Separate address and licence / pilot certificate number for ULL records.</small></div><label>ULL address<textarea name="ull_address" rows={3} defaultValue={ullAddress} placeholder="Address for the ULL logbook"/></label><label>ULL licence number<input name="ull_licence_number" defaultValue={ullLicence} placeholder="ULL licence / pilot certificate number"/></label><button className="primary-button">Save logbook identities</button></form></section>
    </div>

    <section className="panel settings-panel"><div className="section-heading"><div><p className="eyebrow">DEFAULTS & EXPORT</p><h2>Logbook settings</h2></div></div><form action={saveSettings} className="form-grid settings-grid"><label>Home airport<input name="home_airport" defaultValue={t(d.settings.home_airport)} placeholder="LKLT"/></label><label>Default role<select name="default_role" defaultValue={t(d.settings.default_role)||'PIC'}>{EASA_ROLES.map(role=><option key={role} value={role}>{role}</option>)}</select></label><label>Default logbook<select name="default_evidence" defaultValue={t(preferences.default_evidence)||'ULL'}><option>ULL</option><option>EASA</option></select></label><label>Default printable logbook<select name="print_default_scope" defaultValue={printScope}>{LOGBOOK_PRINT_SCOPES.map(scope=><option key={scope.value} value={scope.value}>{scope.label}</option>)}</select></label><label>Auxiliary roles in official print<select name="print_include_auxiliary_roles" defaultValue={preferences.print_include_auxiliary_roles?"yes":"no"}><option value="no">Exclude Safety Pilot / PAX / Observer</option><option value="yes">Include for reference</option></select><small>FCL.050 does not list Safety Pilot as a pilot-function time category. Excluding auxiliary-only records is the safer default for an official logbook print.</small></label><label>Currency<select name="currency" defaultValue={t(d.settings.currency)||'CZK'}><option>CZK</option><option>EUR</option><option>USD</option><option>GBP</option></select></label><label>Time zone<input name="timezone" defaultValue={t(d.settings.timezone)||'Europe/Prague'}/><small>Stored flight and FCL.050 print times remain UTC.</small></label><div className="form-actions wide"><button className="primary-button">Save settings</button></div></form></section>

    <section className="panel expiry-panel"><div className="section-heading"><div><p className="eyebrow">EXPIRIES</p><h2>Documents and qualifications</h2></div></div><form action={addExpiry} className="inline-editor"><select name="category"><option>Document</option><option>Licence</option><option>Medical</option><option>Qualification</option><option>Insurance</option></select><input name="label" placeholder="Name" required/><label>Valid until<input type="date" name="expiry_date" required/></label><input type="number" name="warning_days" defaultValue="30" placeholder="Warning days"/><input name="note" placeholder="Notes"/><button className="primary-button">Add</button></form><div className="expiry-list">{d.expiries.map(e=>{const state=expiryState(e.expiry_date,e.warning_days);return <article key={t(e.id)} className={`expiry-card ${state.className}${Number(e.active)?'':' inactive'}`}><div><span>{t(e.category)}</span><strong>{t(e.label)}</strong><small>{t(e.note)}</small></div><div><b>{new Date(`${t(e.expiry_date)}T00:00:00`).toLocaleDateString('en-GB')}</b><small>{state.label}</small></div><div className="expiry-actions"><form action={toggleExpiry}><input type="hidden" name="id" value={t(e.id)}/><button className="secondary-link">{Number(e.active)?'Archive':'Activate'}</button></form><form action={deleteExpiry}><input type="hidden" name="id" value={t(e.id)}/><button className="icon-danger">Delete</button></form></div></article>})}{!d.expiries.length?<p className="empty-state">No expiry records.</p>:null}</div></section>
    <details className="panel security-panel"><summary>Account security</summary><form action={changePassword} className="stack-form narrow-form"><label>Current password<input type="password" name="current_password" autoComplete="current-password" required/></label><label>New password<input type="password" name="new_password" minLength={10} autoComplete="new-password" required/></label><label>Confirm new password<input type="password" name="confirm_password" minLength={10} autoComplete="new-password" required/></label><button className="primary-button">Change password</button></form></details>
  </>;
}
