"use server";

import { revalidatePath } from "next/cache";
import { requireUser } from "@/lib/auth/require-user";
import { sql } from "@/lib/db";
import { flightRestoreKey,parsePortableBackup,trackRestoreKey,type BackupRow,type PortableBackup } from "@/lib/portable-backup";
import { createStoredBackup,loadStoredBackup } from "@/lib/backup-center";
import { restoreDeletedFlightRecord } from "@/lib/flight-trash";

export type RestorePreview={digest:string;exportedAt:string;source:Record<string,number>;add:Record<string,number>;skip:Record<string,number>;settings:boolean;legacyPoints:number};
export type RestoreState={error?:string;success?:string;preview?:RestorePreview};
export type TrashRestoreState={error?:string;success?:string};
const text=(row:BackupRow,key:string,max=2000)=>String(row[key]??"").trim().slice(0,max),upper=(row:BackupRow,key:string,max=120)=>text(row,key,max).toUpperCase();
const nullableNumber=(value:unknown)=>value===null||value===undefined||value===""?null:Number.isFinite(Number(value))?Number(value):null;
const integer=(value:unknown,fallback=0)=>Number.isFinite(Number(value))?Math.trunc(Number(value)):fallback;
const jsonText=(value:unknown,fallback="[]")=>{if(typeof value==="string"){try{JSON.parse(value);return value}catch{return fallback}}try{return JSON.stringify(value??JSON.parse(fallback))}catch{return fallback}};
const isoTime=(value:unknown)=>{const raw=String(value??"").trim();if(!raw)return"";const date=new Date(raw);return Number.isNaN(date.getTime())?"":date.toISOString()};

async function readBackup(form:FormData){const file=form.get("backup");if(!(file instanceof File)||!file.size)throw new Error("Select a complete JSON backup.");if(file.size>150*1024*1024)throw new Error("File exceeds the 150 MB safety limit.");return parsePortableBackup(await file.text())}

async function buildPreview(userId:number,backup:PortableBackup,digest:string):Promise<RestorePreview>{
  const [flightRows,aircraftRows,rateRows,airportRows,expiryRows,trackRows]=await Promise.all([
    sql`SELECT date::text date,registration,off_block,departure,arrival FROM flights WHERE user_id=${userId}`,
    sql`SELECT registration FROM aircraft WHERE user_id=${userId}`,
    sql`SELECT registration,COALESCE(valid_from,'') valid_from FROM rates WHERE user_id=${userId}`,
    sql`SELECT ident FROM airports WHERE user_id=${userId}`,
    sql`SELECT category,label,expiry_date::text expiry_date FROM user_expiries WHERE user_id=${userId}`,
    sql`SELECT f.date::text date,f.registration,f.off_block,f.departure,f.arrival,t.file_name,t.start_utc::text start_utc,t.end_utc::text end_utc,t.point_count FROM flight_tracks t JOIN flights f ON f.id=t.flight_id AND f.user_id=t.user_id WHERE t.user_id=${userId}`,
  ]) as Array<Array<BackupRow>>;
  const existingFlights=new Set(flightRows.map(flightRestoreKey)),existingAircraft=new Set(aircraftRows.map(row=>upper(row,"registration"))),existingRates=new Set(rateRows.map(row=>`${upper(row,"registration")}|${text(row,"valid_from")}`)),existingAirports=new Set(airportRows.map(row=>upper(row,"ident"))),existingExpiries=new Set(expiryRows.map(row=>`${upper(row,"category")}|${upper(row,"label")}|${text(row,"expiry_date").slice(0,10)}`)),existingTracks=new Set(trackRows.map(row=>trackRestoreKey(flightRestoreKey(row),row)));
  const sourceFlights=new Map(backup.flights.map(row=>[String(row.id),flightRestoreKey(row)])),backupTrackKeys=backup.flight_tracks.map(row=>trackRestoreKey(sourceFlights.get(String(row.flight_id))??"",row));
  const counts={flights:backup.flights.length,aircraft:backup.aircraft.length,rates:backup.rates.length,airports:backup.airports.length,expiries:backup.expiries.length,flight_tracks:backup.flight_tracks.length};
  const add={flights:backup.flights.filter(row=>!existingFlights.has(flightRestoreKey(row))).length,aircraft:backup.aircraft.filter(row=>!existingAircraft.has(upper(row,"registration"))).length,rates:backup.rates.filter(row=>!existingRates.has(`${upper(row,"registration")}|${text(row,"valid_from")}`)).length,airports:backup.airports.filter(row=>!existingAirports.has(upper(row,"ident"))).length,expiries:backup.expiries.filter(row=>!existingExpiries.has(`${upper(row,"category")}|${upper(row,"label")}|${text(row,"expiry_date").slice(0,10)}`)).length,flight_tracks:backupTrackKeys.filter(key=>key&&!existingTracks.has(key)).length};
  const skip=Object.fromEntries(Object.entries(counts).map(([key,value])=>[key,value-(add[key as keyof typeof add]||0)]));
  return{digest,exportedAt:String(backup.exported_at||""),source:counts,add,skip,settings:Boolean(backup.settings[0]),legacyPoints:backup.track_points.length};
}

export async function restorePortableBackup(_:RestoreState,form:FormData):Promise<RestoreState>{
  const {userId}=await requireUser();let parsed;try{parsed=await readBackup(form)}catch(error){return{error:error instanceof Error?error.message:"Backup could not be read."}}
  const preview=await buildPreview(userId,parsed.backup,parsed.digest),intent=String(form.get("intent")||"preview");if(intent!=="restore")return{preview};
  if(String(form.get("preview_digest")||"")!==parsed.digest)return{error:"The file changed after preview. Validate it again."};
  if(String(form.get("confirm")||"").trim().toUpperCase()!=="RESTORE")return{error:"Type RESTORE to confirm.",preview};
  try{await createStoredBackup(userId,"pre_restore")}catch(error){console.error("pre-restore-backup-failed",error);return{error:"Restore was stopped because the safety backup could not be created. Existing data is unchanged.",preview}}
  const backup=parsed.backup,metadataQueries=[];
  const settings=backup.settings[0];if(settings)metadataQueries.push(sql`INSERT INTO user_settings(user_id,timezone,currency,home_airport,default_role,preferences_json,created_at,updated_at) VALUES(${userId},${text(settings,"timezone")||"Europe/Prague"},${text(settings,"currency")||"CZK"},${upper(settings,"home_airport")},${upper(settings,"default_role")||"PIC"},${jsonText(settings.preferences_json,"{}")},NOW(),NOW()) ON CONFLICT(user_id) DO UPDATE SET timezone=EXCLUDED.timezone,currency=EXCLUDED.currency,home_airport=EXCLUDED.home_airport,default_role=EXCLUDED.default_role,preferences_json=EXCLUDED.preferences_json,updated_at=NOW()`);
  for(const row of backup.aircraft){const registration=upper(row,"registration");if(!registration)continue;metadataQueries.push(sql`INSERT INTO aircraft(user_id,registration,aircraft_type,icao_type,aircraft_class,evidence,default_price_per_hour,default_role,billing_basis,active,note,created_at,updated_at) SELECT ${userId},${registration},${text(row,"aircraft_type",120)},${text(row,"icao_type",120)},${upper(row,"aircraft_class")},${upper(row,"evidence")},${nullableNumber(row.default_price_per_hour)},${upper(row,"default_role")||"PIC"},${text(row,"billing_basis",40)||"BLOCK"},${integer(row.active,1)},${text(row,"note")},NOW(),NOW() WHERE NOT EXISTS(SELECT 1 FROM aircraft WHERE user_id=${userId} AND UPPER(TRIM(registration))=${registration})`)}
  for(const row of backup.rates){const registration=upper(row,"registration"),valid=text(row,"valid_from").slice(0,10);if(!registration)continue;metadataQueries.push(sql`INSERT INTO rates(user_id,registration,aircraft_type,valid_from,price_per_hour,dry_price_per_hour,source) SELECT ${userId},${registration},${text(row,"aircraft_type",120)},${valid},${nullableNumber(row.price_per_hour)},${nullableNumber(row.dry_price_per_hour)},${text(row,"source",500)} WHERE NOT EXISTS(SELECT 1 FROM rates WHERE user_id=${userId} AND UPPER(TRIM(registration))=${registration} AND COALESCE(valid_from,'')=${valid})`)}
  for(const row of backup.airports){const ident=upper(row,"ident");if(!ident)continue;metadataQueries.push(sql`INSERT INTO airports(user_id,ident,name,municipality,iso_country,latitude_deg,longitude_deg,active,closed,source,updated_at) SELECT ${userId},${ident},${text(row,"name",500)},${text(row,"municipality",300)},${upper(row,"iso_country",20)},${nullableNumber(row.latitude_deg)},${nullableNumber(row.longitude_deg)},${integer(row.active,1)},${integer(row.closed,0)},${text(row,"source",200)||"Backup restore"},NOW() WHERE NOT EXISTS(SELECT 1 FROM airports WHERE user_id=${userId} AND UPPER(TRIM(ident))=${ident})`)}
  for(const row of backup.expiries){const category=text(row,"category",120)||"Document",label=text(row,"label",300),date=text(row,"expiry_date").slice(0,10);if(!label||!date)continue;metadataQueries.push(sql`INSERT INTO user_expiries(user_id,category,label,expiry_date,warning_days,note,active,created_at,updated_at) SELECT ${userId},${category},${label},${date},${integer(row.warning_days,30)},${text(row,"note")},${integer(row.active,1)},NOW(),NOW() WHERE NOT EXISTS(SELECT 1 FROM user_expiries WHERE user_id=${userId} AND UPPER(TRIM(category))=UPPER(${category}) AND UPPER(TRIM(label))=UPPER(${label}) AND expiry_date::text=${date})`)}
  const tracksByFlight=new Map<string,BackupRow[]>();for(const track of backup.flight_tracks){const key=String(track.flight_id),items=tracksByFlight.get(key)??[];items.push(track);tracksByFlight.set(key,items)}
  const flightBatches=[];for(const row of backup.flights){const sourceId=String(row.id),date=text(row,"date").slice(0,10),registration=upper(row,"registration"),offBlock=text(row,"off_block",20),departure=upper(row,"departure"),arrival=upper(row,"arrival");if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!registration)continue;const queries=[sql`INSERT INTO flights(user_id,date,evidence,registration,aircraft_type,aircraft_class,departure,arrival,off_block,takeoff,landing,on_block,starts,commander,instructor,role,task,price_per_hour,billing_basis,note) SELECT ${userId},${date},${upper(row,"evidence")},${registration},${text(row,"aircraft_type",120)},${upper(row,"aircraft_class")},${departure},${arrival},${offBlock},${text(row,"takeoff",20)},${text(row,"landing",20)},${text(row,"on_block",20)},${integer(row.starts,0)},${text(row,"commander",300)},${text(row,"instructor",300)},${upper(row,"role")},${text(row,"task",1000)},${nullableNumber(row.price_per_hour)},${text(row,"billing_basis",40)||"BLOCK"},${text(row,"note")} WHERE NOT EXISTS(SELECT 1 FROM flights WHERE user_id=${userId} AND date::text=${date} AND UPPER(TRIM(registration))=${registration} AND COALESCE(off_block,'')=${offBlock} AND UPPER(TRIM(COALESCE(departure,'')))=${departure} AND UPPER(TRIM(COALESCE(arrival,'')))=${arrival})`];for(const track of tracksByFlight.get(sourceId)??[]){const fileName=text(track,"file_name",240),start=isoTime(track.start_utc),end=isoTime(track.end_utc),pointCount=Math.max(0,integer(track.point_count,0));queries.push(sql`INSERT INTO flight_tracks(user_id,flight_id,file_name,imported_at,point_count,distance_km,start_utc,end_utc,min_alt_m,max_alt_m,coordinates_json,overview_coordinates_json,overview_version) SELECT ${userId},f.id,${fileName},NOW(),${pointCount},${nullableNumber(track.distance_km)||0},${start||null},${end||null},${nullableNumber(track.min_alt_m)},${nullableNumber(track.max_alt_m)},${jsonText(track.coordinates_json)},${jsonText(track.overview_coordinates_json)},${Math.max(1,integer(track.overview_version,1))} FROM flights f WHERE f.user_id=${userId} AND f.date::text=${date} AND UPPER(TRIM(f.registration))=${registration} AND COALESCE(f.off_block,'')=${offBlock} AND UPPER(TRIM(COALESCE(f.departure,'')))=${departure} AND UPPER(TRIM(COALESCE(f.arrival,'')))=${arrival} AND NOT EXISTS(SELECT 1 FROM flight_tracks t WHERE t.user_id=${userId} AND t.flight_id=f.id AND COALESCE(t.file_name,'')=${fileName} AND LEFT(REPLACE(COALESCE(t.start_utc::text,''),'T',' '),19)=LEFT(REPLACE(${start},'T',' '),19) AND LEFT(REPLACE(COALESCE(t.end_utc::text,''),'T',' '),19)=LEFT(REPLACE(${end},'T',' '),19) AND COALESCE(t.point_count,0)=${pointCount}) ORDER BY f.id LIMIT 1`)}flightBatches.push({label:`${date} · ${registration} · ${departure||"—"} → ${arrival||"—"}`,queries})}
  const operationCount=metadataQueries.length+flightBatches.reduce((sum,batch)=>sum+batch.queries.length,0);if(operationCount>5000)return{error:"This backup requires more than 5,000 database operations. Contact an administrator.",preview};
  try{if(metadataQueries.length)await sql.transaction(metadataQueries)}catch(error){console.error("portable-backup-metadata-restore-failed",error);const code=String((error as {code?:unknown})?.code||"");return{error:`Restore stopped while processing account settings${code?` (database ${code})`:""}. No flights were changed.`,preview}}
  let completed=0;for(const batch of flightBatches){try{await sql.transaction(batch.queries);completed++}catch(error){console.error("portable-backup-flight-restore-failed",{label:batch.label,index:completed+1,error});for(const path of ["/data","/export","/dashboard","/flights","/database","/profile","/map","/print"])revalidatePath(path);const code=String((error as {code?:unknown})?.code||"");return{error:`Restore stopped at flight ${completed+1}/${flightBatches.length}: ${batch.label}${code?` (database ${code})`:""}. ${completed} previous flights were completed safely. Validate the backup again to continue.`,preview}}}
  for(const path of ["/data","/export","/dashboard","/flights","/database","/profile","/map","/print"])revalidatePath(path);
  const added=Object.values(preview.add).reduce((sum,value)=>sum+value,0);return{success:`Restore completed. Added ${added} missing records; existing flights and historical rates were not changed.`};
}

export async function createManualBackup(){const {userId}=await requireUser();await createStoredBackup(userId,"manual");revalidatePath("/data");revalidatePath("/export")}

export async function restoreStoredBackup(_:RestoreState,form:FormData):Promise<RestoreState>{
  const {userId}=await requireUser(),id=Number(form.get("backup_id"));if(!Number.isSafeInteger(id)||id<=0)return{error:"Select a stored backup."};
  let stored;try{stored=await loadStoredBackup(userId,id)}catch(error){return{error:error instanceof Error?error.message:"Stored backup could not be read."}}
  const forwarded=new FormData();forwarded.set("backup",new File([stored.json],`stored-backup-${id}.json`,{type:"application/json"}));forwarded.set("intent",String(form.get("intent")||"preview"));forwarded.set("preview_digest",String(form.get("preview_digest")||""));forwarded.set("confirm",String(form.get("confirm")||""));return restorePortableBackup({},forwarded);
}

export async function restoreDeletedFlight(_:TrashRestoreState,form:FormData):Promise<TrashRestoreState>{
  const {userId}=await requireUser(),id=Number(form.get("trash_id"));if(!Number.isSafeInteger(id)||id<=0)return{error:"Select a deleted flight."};
  let result;try{result=await restoreDeletedFlightRecord(userId,id)}catch(error){console.error("flight-trash-restore-failed",error);return{error:"The flight could not be restored. Existing data is unchanged."}}
  if(result.error)return{error:result.error};
  for(const path of ["/data","/export","/dashboard","/flights","/database","/map","/print"])revalidatePath(path);
  return{success:`Flight restored as record ${result.flightId}.`};
}
