import { requireUser } from "@/lib/auth/require-user";
import { sql } from "@/lib/db";
import { PilotConnectionSearch } from "@/components/pilot-connection-search";
import { acceptConnection,cancelConnection,declineConnection,removeConnection,updateConnection } from "./actions";
import Link from "next/link";

export const metadata={title:"Connections | FlyTally"};
const text=(value:unknown)=>String(value??"");
const roleLabel=(value:unknown)=>{const label=text(value).trim().toLowerCase();return label==="instructor"?"Instructor":label==="student"?"Student":"Friend"};

export default async function ConnectionsPage(){
  const session=await requireUser(),userId=session.userId;
  const[incoming,outgoing,connected,flightRequests,sharedInvites,approvedReady]=await Promise.all([
    sql`SELECT c.id,c.relationship,c.requester_label,c.recipient_label,c.created_at,u.display_name,COALESCE(s.home_airport,'') home_airport FROM pilot_connections c JOIN users u ON u.id=c.requester_user_id LEFT JOIN user_settings s ON s.user_id=u.id WHERE c.recipient_user_id=${userId} AND c.status='pending' ORDER BY c.created_at DESC` as Promise<Array<Record<string,unknown>>>,
    sql`SELECT c.id,c.relationship,c.requester_label,c.recipient_label,c.created_at,u.display_name,COALESCE(s.home_airport,'') home_airport FROM pilot_connections c JOIN users u ON u.id=c.recipient_user_id LEFT JOIN user_settings s ON s.user_id=u.id WHERE c.requester_user_id=${userId} AND c.status='pending' ORDER BY c.created_at DESC` as Promise<Array<Record<string,unknown>>>,
    sql`SELECT c.id,c.requester_user_id,c.recipient_user_id,c.relationship,c.requester_label,c.recipient_label,c.requester_shares_logbook,c.recipient_shares_logbook,c.accepted_at,u.display_name,COALESCE(s.home_airport,'') home_airport FROM pilot_connections c JOIN users u ON u.id=CASE WHEN c.requester_user_id=${userId} THEN c.recipient_user_id ELSE c.requester_user_id END LEFT JOIN user_settings s ON s.user_id=u.id WHERE c.status='accepted' AND (c.requester_user_id=${userId} OR c.recipient_user_id=${userId}) ORDER BY u.display_name` as Promise<Array<Record<string,unknown>>>,
    sql`SELECT a.id,f.date::text date,f.registration,f.departure,f.arrival,f.role,u.display_name FROM instructor_flight_approvals a JOIN flights f ON f.id=a.flight_id JOIN users u ON u.id=a.student_user_id
      WHERE a.instructor_user_id=${userId} AND a.status='pending' AND f.certified_at IS NOT NULL AND COALESCE(f.record_revision,1)=a.record_revision AND f.certification_hash=a.flight_hash ORDER BY a.requested_at DESC` as Promise<Array<Record<string,unknown>>>,
    sql`SELECT p.id,f.date::text date,f.registration,f.departure,f.arrival,p.participant_role,u.display_name FROM flight_participations p JOIN flights f ON f.id=p.source_flight_id JOIN users u ON u.id=p.source_user_id
      WHERE p.participant_user_id=${userId} AND p.status='pending' AND f.certified_at IS NOT NULL AND COALESCE(f.record_revision,1)=p.source_revision AND f.certification_hash=p.source_hash ORDER BY p.created_at DESC` as Promise<Array<Record<string,unknown>>>,
    sql`SELECT a.id,f.date::text date,f.registration,f.departure,f.arrival,f.role,u.display_name FROM instructor_flight_approvals a JOIN flights f ON f.id=a.flight_id JOIN users u ON u.id=a.student_user_id
      LEFT JOIN flight_participations p ON p.source_flight_id=a.flight_id AND p.source_revision=a.record_revision AND p.participant_role='INSTRUCTOR' AND p.participant_user_id=a.instructor_user_id
      WHERE a.instructor_user_id=${userId} AND a.status='approved' AND p.participant_flight_id IS NULL AND f.certified_at IS NOT NULL AND COALESCE(f.record_revision,1)=a.record_revision AND f.certification_hash=a.flight_hash ORDER BY a.decided_at DESC` as Promise<Array<Record<string,unknown>>>,
  ]);
  const reviewCount=flightRequests.length+sharedInvites.length+approvedReady.length;
  return <>
    <header className="page-header"><div><p className="eyebrow">PILOT NETWORK</p><h1>Connections</h1><p className="muted">Keep a simple private network of friends, students and instructors.</p></div></header>
    {reviewCount?<section className="panel connection-inbox"><div className="section-heading"><div><p className="eyebrow">FLIGHTS TO REVIEW</p><h2>Shared flights</h2></div><span className="status-on">{reviewCount} pending</span></div><div className="connection-list">
      {flightRequests.map(row=><article className="connection-card" key={`approval-${text(row.id)}`}><div className="pilot-avatar" aria-hidden="true">{text(row.display_name).slice(0,1).toUpperCase()||"P"}</div><div className="connection-identity"><strong>{text(row.display_name)}</strong><span>Instructor approval · {text(row.registration)} · {text(row.date)}</span><small>{text(row.departure)} → {text(row.arrival)} · {text(row.role)}</small></div><Link className="primary-button" href={`/connections/flight/${text(row.id)}`}>Review flight</Link></article>)}
      {approvedReady.map(row=><article className="connection-card" key={`add-${text(row.id)}`}><div className="pilot-avatar" aria-hidden="true">{text(row.display_name).slice(0,1).toUpperCase()||"P"}</div><div className="connection-identity"><strong>{text(row.display_name)}</strong><span>Approved · ready for your logbook</span><small>{text(row.registration)} · {text(row.date)} · {text(row.departure)} → {text(row.arrival)}</small></div><Link className="primary-button" href={`/connections/flight/${text(row.id)}`}>Add flight</Link></article>)}
      {sharedInvites.map(row=><article className="connection-card" key={`shared-${text(row.id)}`}><div className="pilot-avatar" aria-hidden="true">{text(row.display_name).slice(0,1).toUpperCase()||"P"}</div><div className="connection-identity"><strong>{text(row.display_name)}</strong><span>Invites you as {text(row.participant_role)}</span><small>{text(row.registration)} · {text(row.date)} · {text(row.departure)} → {text(row.arrival)}</small></div><Link className="primary-button" href={`/connections/shared/${text(row.id)}`}>Review &amp; add</Link></article>)}
    </div></section>:null}
    {incoming.length?<section className="panel connection-inbox"><div className="section-heading"><div><p className="eyebrow">ACTION REQUIRED</p><h2>Connection requests</h2></div><span className="status-on">{incoming.length} pending</span></div><div className="connection-list">{incoming.map(row=><article className="connection-card" key={text(row.id)}><div className="pilot-avatar" aria-hidden="true">{text(row.display_name).slice(0,1).toUpperCase()||"P"}</div><div className="connection-identity"><strong>{text(row.display_name)||"Pilot"}</strong><span>Wants to connect as your {roleLabel(row.recipient_label).toLowerCase()}</span><small>{text(row.home_airport)?`Home airport ${text(row.home_airport)}`:"Home airport not set"}</small></div><div className="connection-actions"><form action={acceptConnection}><input type="hidden" name="connection_id" value={text(row.id)}/><button className="primary-button">Accept</button></form><form action={declineConnection}><input type="hidden" name="connection_id" value={text(row.id)}/><button className="secondary-button">Decline</button></form></div></article>)}</div></section>:null}
    <div className="connections-layout"><section className="panel"><p className="eyebrow">FIND A PILOT</p><h2>New connection</h2><p className="muted">Use the exact account email. Choose whether that person is your friend, student or instructor.</p><PilotConnectionSearch/></section><section className="panel connection-privacy"><p className="eyebrow">PRIVATE BY DEFAULT</p><h2>Your logbook stays private</h2><p className="muted">A connection sees only your display name, home airport and relationship until you explicitly enable read-only logbook sharing.</p></section></div>
    <section className="panel"><div className="section-heading"><div><p className="eyebrow">CONNECTED</p><h2>Your pilots</h2><p className="muted">Relationship and logbook access can be changed anytime.</p></div><span>{connected.length}</span></div>{connected.length?<div className="connection-list">{connected.map(row=>{const requester=Number(row.requester_user_id)===userId,label=text(requester?row.requester_label:row.recipient_label).toLowerCase()||"friend",share=Boolean(requester?row.requester_shares_logbook:row.recipient_shares_logbook),otherShares=Boolean(requester?row.recipient_shares_logbook:row.requester_shares_logbook);return <details className="connection-card connection-manager" key={text(row.id)}><summary><div className="pilot-avatar" aria-hidden="true">{text(row.display_name).slice(0,1).toUpperCase()||"P"}</div><div className="connection-identity"><strong>{text(row.display_name)||"Pilot"}</strong><span>{roleLabel(label)} · {share?"Can view your logbook":"Logbook private"}</span><small>{text(row.home_airport)?`Home airport ${text(row.home_airport)}`:"Home airport not set"}</small></div><span aria-hidden="true">⌄</span></summary><div className="connection-editor"><form action={updateConnection} className="stack-form"><input type="hidden" name="connection_id" value={text(row.id)}/><label>Relationship<select name="relationship_label" defaultValue={label}><option value="friend">Friend</option><option value="student">Student</option><option value="instructor">Instructor</option></select></label><label className="check-row"><input type="checkbox" name="share_logbook" value="yes" defaultChecked={share}/> Allow read-only logbook view</label><small>Price, private notes and GPS stay hidden.</small><button className="primary-button">Save access</button></form><div>{otherShares?<Link className="secondary-button" href={`/connections/logbook/${text(row.id)}`}>View logbook</Link>:null}<details className="confirm-action"><summary>Remove connection…</summary><div><p>Future access and requests stop. Historical signed or accepted flight records remain preserved.</p><form action={removeConnection}><input type="hidden" name="connection_id" value={text(row.id)}/><button className="icon-danger">Remove connection</button></form></div></details></div></div></details>})}</div>:<p className="empty-state">No accepted connections yet.</p>}</section>
    {outgoing.length?<section className="panel"><div className="section-heading"><div><p className="eyebrow">SENT</p><h2>Pending requests</h2></div><span>{outgoing.length}</span></div><div className="connection-list">{outgoing.map(row=><article className="connection-card" key={text(row.id)}><div className="pilot-avatar" aria-hidden="true">{text(row.display_name).slice(0,1).toUpperCase()||"P"}</div><div className="connection-identity"><strong>{text(row.display_name)||"Pilot"}</strong><span>Invited as your {roleLabel(row.requester_label).toLowerCase()}</span><small>Waiting for approval</small></div><form action={cancelConnection}><input type="hidden" name="connection_id" value={text(row.id)}/><button className="secondary-button">Cancel request</button></form></article>)}</div></section>:null}
  </>;
}
