import { requireUser } from "@/lib/auth/require-user";
import { sql } from "@/lib/db";
import { PilotConnectionSearch } from "@/components/pilot-connection-search";
import { acceptConnection,cancelConnection,declineConnection,removeConnection } from "./actions";
import Link from "next/link";

export const metadata={title:"Connections | FlyTally"};
const text=(value:unknown)=>String(value??"");
const requestLabel=(relationship:unknown)=>relationship==="requester_instructor"?"Wants to connect as your instructor":relationship==="recipient_instructor"?"Wants you as their instructor":"Wants to connect as a fellow pilot";
const outgoingLabel=(relationship:unknown)=>relationship==="requester_instructor"?"You will be their instructor":relationship==="recipient_instructor"?"They will be your instructor":"Fellow pilot request";
const acceptedLabel=(row:Record<string,unknown>,userId:number)=>{
  if(row.relationship==="pilot")return"Fellow pilot";
  const instructor=row.relationship==="requester_instructor"?Number(row.requester_user_id):Number(row.recipient_user_id);
  return instructor===userId?"You are instructor":"Your instructor";
};

export default async function ConnectionsPage(){
  const session=await requireUser(),userId=session.userId;
  const[incoming,outgoing,connected,flightRequests]=await Promise.all([
    sql`SELECT c.id,c.relationship,c.created_at,u.display_name,COALESCE(s.home_airport,'') home_airport FROM pilot_connections c JOIN users u ON u.id=c.requester_user_id LEFT JOIN user_settings s ON s.user_id=u.id WHERE c.recipient_user_id=${userId} AND c.status='pending' ORDER BY c.created_at DESC` as Promise<Array<Record<string,unknown>>>,
    sql`SELECT c.id,c.relationship,c.created_at,u.display_name,COALESCE(s.home_airport,'') home_airport FROM pilot_connections c JOIN users u ON u.id=c.recipient_user_id LEFT JOIN user_settings s ON s.user_id=u.id WHERE c.requester_user_id=${userId} AND c.status='pending' ORDER BY c.created_at DESC` as Promise<Array<Record<string,unknown>>>,
    sql`SELECT c.id,c.requester_user_id,c.recipient_user_id,c.relationship,c.accepted_at,u.display_name,COALESCE(s.home_airport,'') home_airport FROM pilot_connections c JOIN users u ON u.id=CASE WHEN c.requester_user_id=${userId} THEN c.recipient_user_id ELSE c.requester_user_id END LEFT JOIN user_settings s ON s.user_id=u.id WHERE c.status='accepted' AND (c.requester_user_id=${userId} OR c.recipient_user_id=${userId}) ORDER BY u.display_name` as Promise<Array<Record<string,unknown>>>,
    sql`SELECT a.id,f.date::text date,f.registration,f.departure,f.arrival,f.role,u.display_name FROM instructor_flight_approvals a JOIN flights f ON f.id=a.flight_id JOIN users u ON u.id=a.student_user_id
      WHERE a.instructor_user_id=${userId} AND a.status='pending' AND f.certified_at IS NOT NULL AND COALESCE(f.record_revision,1)=a.record_revision AND f.certification_hash=a.flight_hash ORDER BY a.requested_at DESC` as Promise<Array<Record<string,unknown>>>,
  ]);
  return <>
    <header className="page-header"><div><p className="eyebrow">PILOT NETWORK</p><h1>Connections</h1><p className="muted">Connect privately with pilots and establish instructor–student relationships.</p></div></header>
    {flightRequests.length?<section className="panel connection-inbox"><div className="section-heading"><div><p className="eyebrow">FLIGHTS TO REVIEW</p><h2>Instructor approvals</h2></div><span className="status-on">{flightRequests.length} pending</span></div><div className="connection-list">{flightRequests.map(row=><article className="connection-card" key={text(row.id)}><div className="pilot-avatar" aria-hidden="true">{text(row.display_name).slice(0,1).toUpperCase()||"P"}</div><div className="connection-identity"><strong>{text(row.display_name)}</strong><span>{text(row.registration)} · {text(row.date)}</span><small>{text(row.departure)} → {text(row.arrival)} · {text(row.role)}</small></div><Link className="primary-button" href={`/connections/flight/${text(row.id)}`}>Review flight</Link></article>)}</div></section>:null}
    {incoming.length?<section className="panel connection-inbox"><div className="section-heading"><div><p className="eyebrow">ACTION REQUIRED</p><h2>Connection requests</h2></div><span className="status-on">{incoming.length} pending</span></div><div className="connection-list">{incoming.map(row=><article className="connection-card" key={text(row.id)}><div className="pilot-avatar" aria-hidden="true">{text(row.display_name).slice(0,1).toUpperCase()||"P"}</div><div className="connection-identity"><strong>{text(row.display_name)||"Pilot"}</strong><span>{requestLabel(row.relationship)}</span><small>{text(row.home_airport)?`Home airport ${text(row.home_airport)}`:"Home airport not set"}</small></div><div className="connection-actions"><form action={acceptConnection}><input type="hidden" name="connection_id" value={text(row.id)}/><button className="primary-button">Accept</button></form><form action={declineConnection}><input type="hidden" name="connection_id" value={text(row.id)}/><button className="secondary-button">Decline</button></form></div></article>)}</div></section>:null}
    <div className="connections-layout"><section className="panel"><p className="eyebrow">FIND A PILOT</p><h2>New connection</h2><p className="muted">Use the exact account email. The other pilot must approve before either profile is connected.</p><PilotConnectionSearch/></section><section className="panel connection-privacy"><p className="eyebrow">PRIVATE BY DEFAULT</p><h2>Your logbook stays private</h2><p className="muted">Connections can see only your display name, home airport and agreed relationship. Flights, totals, licences and GPS tracks are never shared by this feature.</p></section></div>
    <section className="panel"><div className="section-heading"><div><p className="eyebrow">CONNECTED</p><h2>Your pilots</h2></div><span>{connected.length}</span></div>{connected.length?<div className="connection-list">{connected.map(row=><article className="connection-card" key={text(row.id)}><div className="pilot-avatar" aria-hidden="true">{text(row.display_name).slice(0,1).toUpperCase()||"P"}</div><div className="connection-identity"><strong>{text(row.display_name)||"Pilot"}</strong><span>{acceptedLabel(row,userId)}</span><small>{text(row.home_airport)?`Home airport ${text(row.home_airport)}`:"Home airport not set"}</small></div><details className="confirm-action"><summary>Remove…</summary><div><p>This ends the connection. No logbook records are changed.</p><form action={removeConnection}><input type="hidden" name="connection_id" value={text(row.id)}/><button className="icon-danger">Remove connection</button></form></div></details></article>)}</div>:<p className="empty-state">No accepted connections yet.</p>}</section>
    {outgoing.length?<section className="panel"><div className="section-heading"><div><p className="eyebrow">SENT</p><h2>Pending requests</h2></div><span>{outgoing.length}</span></div><div className="connection-list">{outgoing.map(row=><article className="connection-card" key={text(row.id)}><div className="pilot-avatar" aria-hidden="true">{text(row.display_name).slice(0,1).toUpperCase()||"P"}</div><div className="connection-identity"><strong>{text(row.display_name)||"Pilot"}</strong><span>{outgoingLabel(row.relationship)}</span><small>Waiting for approval</small></div><form action={cancelConnection}><input type="hidden" name="connection_id" value={text(row.id)}/><button className="secondary-button">Cancel request</button></form></article>)}</div></section>:null}
  </>;
}
