import { getSession } from "@/lib/auth/session";import { sql } from "@/lib/db";
export const dynamic="force-dynamic";
const esc=(v:unknown)=>`"${String(v??"").replaceAll('"','""')}"`;const xml=(v:unknown)=>String(v??"").replace(/[<>&'\"]/g,c=>({"<":"&lt;",">":"&gt;","&":"&amp;","'":"&apos;",'"':"&quot;"}[c]!));
const columns=["date","evidence","registration","aircraft_type","aircraft_class","departure","arrival","off_block","takeoff","landing","on_block","block_time","air_time","starts","commander","instructor","role","task","price_per_hour","billing_basis","note","track_count","gps_km"];
export async function GET(request:Request){const session=await getSession();if(!session)return new Response("Unauthorized",{status:401});const url=new URL(request.url),format=url.searchParams.get("format")||"csv";
  const rows=await sql`WITH t AS (SELECT flight_id,COUNT(*)::int track_count,COALESCE(SUM(distance_km),0) gps_km FROM flight_tracks WHERE user_id=${session.userId} GROUP BY flight_id) SELECT f.*,CASE WHEN off_block ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$' AND on_block ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$' THEN (MOD((split_part(on_block,':',1)::int*60+split_part(on_block,':',2)::int)-(split_part(off_block,':',1)::int*60+split_part(off_block,':',2)::int)+1440,1440)/60)::text||':'||LPAD((MOD((split_part(on_block,':',1)::int*60+split_part(on_block,':',2)::int)-(split_part(off_block,':',1)::int*60+split_part(off_block,':',2)::int)+1440,1440)%60)::text,2,'0') ELSE '' END block_time,CASE WHEN takeoff ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$' AND landing ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$' THEN (MOD((split_part(landing,':',1)::int*60+split_part(landing,':',2)::int)-(split_part(takeoff,':',1)::int*60+split_part(takeoff,':',2)::int)+1440,1440)/60)::text||':'||LPAD((MOD((split_part(landing,':',1)::int*60+split_part(landing,':',2)::int)-(split_part(takeoff,':',1)::int*60+split_part(takeoff,':',2)::int)+1440,1440)%60)::text,2,'0') ELSE '' END air_time,COALESCE(t.track_count,0) track_count,COALESCE(t.gps_km,0) gps_km FROM flights f LEFT JOIN t ON t.flight_id=f.id WHERE f.user_id=${session.userId} ORDER BY date,off_block,id` as Array<Record<string,unknown>>;
  const stamp=new Date().toISOString().slice(0,10);
  if(format==="json"){const [aircraft,rates,airports,expiries,settings]=await Promise.all([sql`SELECT * FROM aircraft WHERE user_id=${session.userId}`,sql`SELECT * FROM rates WHERE user_id=${session.userId}`,sql`SELECT * FROM airports WHERE user_id=${session.userId}`,sql`SELECT * FROM user_expiries WHERE user_id=${session.userId}`,sql`SELECT * FROM user_settings WHERE user_id=${session.userId}`]);return new Response(JSON.stringify({version:1,exported_at:new Date().toISOString(),flights:rows,aircraft,rates,airports,expiries,settings},null,2),{headers:{"content-type":"application/json; charset=utf-8","content-disposition":`attachment; filename=logbook-backup-${stamp}.json`}})}
  if(format==="xls"){const header=columns.map(c=>`<Cell><Data ss:Type="String">${xml(c)}</Data></Cell>`).join("");const body=rows.map(r=>`<Row>${columns.map(c=>`<Cell><Data ss:Type="String">${xml(r[c])}</Data></Cell>`).join("")}</Row>`).join("");const data=`<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Worksheet ss:Name="Logbook"><Table><Row>${header}</Row>${body}</Table></Worksheet></Workbook>`;return new Response(data,{headers:{"content-type":"application/vnd.ms-excel; charset=utf-8","content-disposition":`attachment; filename=logbook-${stamp}.xls`}})}
  const csv='\ufeff'+columns.join(';')+'\n'+rows.map(r=>columns.map(c=>esc(r[c])).join(';')).join('\n');return new Response(csv,{headers:{"content-type":"text/csv; charset=utf-8","content-disposition":`attachment; filename=logbook-${stamp}.csv`}});
}
