import Link from "next/link";
import { notFound } from "next/navigation";
import { revalidatePath } from "next/cache";
import { requireUser } from "@/lib/auth/require-user";
import { sql } from "@/lib/db";
import { ensureDatabaseOptimizations } from "@/lib/db-optimization";
import { ensureV132Schema } from "@/lib/v132-schema";
import { ReadonlyLogbookEntry } from "@/components/readonly-logbook-entry";
import { acceptSharedFlight,declineSharedFlight,signAndAddInstructorParticipation,signOnlyInstructorParticipation } from "@/app/(protected)/flights/shared-actions";
import { revokeFlightVerification } from "@/app/(protected)/flights/instructor-actions";
import { crewRoleCredits } from "@/lib/crew";

const text=(value:unknown)=>String(value??"").trim();

function Workflow({status}:{status:"pending"|"accepted"|"added"|"certified"|"declined"|"stale"}){
  const added=["added","certified"].includes(status),certified=status==="certified",reviewed=status!=="pending"&&status!=="stale";
  return <div className="shared-flight-progress" aria-label="Shared flight workflow">
    <div className={`shared-flight-step ${reviewed?"done":status==="pending"?"current":""}`}><span>1</span><div><strong>Review</strong><small>Certified source</small></div></div>
    <div className={`shared-flight-step ${added?"done":status==="accepted"?"current":""}`}><span>2</span><div><strong>Add</strong><small>Your own draft</small></div></div>
    <div className={`shared-flight-step ${certified?"done":added?"current":""}`}><span>3</span><div><strong>Certify</strong><small>Your logbook entry</small></div></div>
  </div>;
}

export default async function SharedFlightReview({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{error?:string}>}){
  const {userId}=await requireUser(),participationId=Number((await params).id),query=await searchParams;if(!Number.isSafeInteger(participationId)||participationId<=0)notFound();
  await ensureDatabaseOptimizations();await ensureV132Schema();
  const rows=await sql`SELECT p.id participation_id,p.status,p.participant_role,p.source_revision,p.source_hash,p.participant_flight_id,p.decision_note,f.*,u.display_name pilot_name,participant.display_name participant_name,
    verify.verification_id,verify.verification_status,verify.signed_at,verify.revocation_reason,own.certified_at participant_certified_at,
    (SELECT NULLIF(TRIM(ac.icao_type),'') FROM aircraft ac WHERE ac.user_id=f.user_id AND UPPER(TRIM(ac.registration))=UPPER(TRIM(f.registration)) ORDER BY ac.id DESC LIMIT 1) icao_type,
    CASE WHEN f.off_block~'^([01][0-9]|2[0-3]):[0-5][0-9]$' AND f.on_block~'^([01][0-9]|2[0-3]):[0-5][0-9]$' THEN MOD((split_part(f.on_block,':',1)::int*60+split_part(f.on_block,':',2)::int)-(split_part(f.off_block,':',1)::int*60+split_part(f.off_block,':',2)::int)+1440,1440) ELSE 0 END::int block_minutes
    FROM flight_participations p JOIN flights f ON f.id=p.source_flight_id AND f.user_id=p.source_user_id JOIN users u ON u.id=p.source_user_id JOIN users participant ON participant.id=p.participant_user_id
    LEFT JOIN flights own ON own.id=p.participant_flight_id AND own.user_id=p.participant_user_id
    LEFT JOIN LATERAL(SELECT v.id verification_id,v.status verification_status,v.signed_at,v.revocation_reason FROM flight_verifications v WHERE v.flight_id=f.id AND v.flight_user_id=f.user_id AND v.signer_user_id=p.participant_user_id AND v.record_revision=p.source_revision AND v.flight_hash=p.source_hash AND v.verification_role IN ('INSTRUCTOR','SUPERVISING PIC') ORDER BY v.id DESC LIMIT 1) verify ON TRUE
    WHERE p.id=${participationId} AND p.participant_user_id=${userId} LIMIT 1` as Array<Record<string,unknown>>;
  const row=rows[0];if(!row)notFound();
  const current=Boolean(row.certified_at)&&Number(row.record_revision)===Number(row.source_revision)&&text(row.certification_hash)===text(row.source_hash),hasOwnEntry=Boolean(row.participant_flight_id),participantCertified=Boolean(row.participant_certified_at),participantRole=text(row.participant_role).toUpperCase(),instructor=participantRole==="INSTRUCTOR",verificationStatus=text(row.verification_status).toLowerCase(),signed=verificationStatus==="signed",revoked=verificationStatus==="revoked",logbookRole=instructor?"FI":participantRole;
  const accept=acceptSharedFlight.bind(null,participationId),decline=declineSharedFlight.bind(null,participationId),signOnly=signOnlyInstructorParticipation.bind(null,participationId),signAdd=signAndAddInstructorParticipation.bind(null,participationId);
  async function revoke(form:FormData){"use server";await revokeFlightVerification(form);revalidatePath(`/connections/shared/${participationId}`)}
  const credit=crewRoleCredits(row.participant_role,Number(row.block_minutes)),ownPic=instructor||participantRole==="EXAMINER";
  const safeRow={...row,role:logbookRole,commander:ownPic?row.participant_name:row.pilot_name,instructor:"",pic_minutes:credit.pic,copilot_minutes:credit.copilot,dual_minutes:0,instructor_minutes:credit.instructor,note:""};
  const stale=!current&&["pending","accepted"].includes(text(row.status));
  const workflowStatus:"pending"|"accepted"|"added"|"certified"|"declined"|"stale"=stale?"stale":text(row.status)==="declined"?"declined":participantCertified?"certified":hasOwnEntry?"added":text(row.status)==="accepted"?"accepted":"pending";
  const revokeControl=signed?<details className="confirm-action"><summary className="secondary-link">Revoke verification…</summary><form action={revoke}><input type="hidden" name="verification_id" value={text(row.verification_id)}/><label>Reason<textarea name="reason" rows={2} minLength={5} maxLength={500} required placeholder="Why is this verification being revoked?"/></label><p className="muted">Revocation is preserved in the audit trail. It does not delete or rewrite the pilot&apos;s certified flight.</p><button className="danger-button">Revoke verification</button></form></details>:null;
  return <>
    <header className="page-header"><div><p className="eyebrow">FLIGHT REQUEST</p><h1>{text(row.registration)} · {text(row.date)}</h1><p className="muted">{text(row.pilot_name)} · {instructor?"Instructor verification":`Invited as ${text(row.participant_role)}`}</p></div><Link className="secondary-link" href="/connections">← Connections</Link></header>
    {query.error?<p className="form-error">{query.error==="duplicate"?"A matching flight already exists in your logbook.":query.error==="signature-required"?"Instructor requests must be signed before an FI entry can be created.":"This request no longer matches the current certified flight."}</p>:null}
    {!instructor?<Workflow status={workflowStatus}/>:null}
    <ReadonlyLogbookEntry row={safeRow} pilotName={text(row.participant_name)} certified={false} easa={text(row.evidence).toUpperCase()==="EASA"} preview/>
    {instructor?<section className={`panel instructor-decision-panel ${signed?"approved":revoked?"revoked":text(row.status)}`}><div><p className="eyebrow">INSTRUCTOR VERIFICATION</p><h2>{stale?"Request is no longer current":signed&&hasOwnEntry?"SIGNED · FI ENTRY ADDED":signed?"SIGNED IN FLYTALLY":revoked?"VERIFICATION REVOKED":row.status==="declined"?"Verification declined":"Review certified revision"}</h2><p className="muted">{stale?"The source pilot corrected this flight after this request was created. This revision cannot be signed; a new request is required for the current revision.":signed&&hasOwnEntry?"Your signature remains attached to the student's exact revision and your separate FI/PIC record is linked in your own logbook.":signed?"The student's revision is signed. Adding an FI entry to your own logbook remains optional.":revoked?`Your previous verification was revoked${text(row.revocation_reason)?`: ${text(row.revocation_reason)}`:""}. The certified source record was not changed. You may sign this current revision again.`:row.status==="declined"?"No signature or FI entry was created.":"Sign this exact certified revision. You can keep only the verification, or also create your own FI/PIC logbook entry."}</p></div>
      {stale?<Link className="secondary-button" href="/connections">Back to Connections</Link>:signed&&hasOwnEntry?<div className="instructor-decision-actions"><Link className="primary-button" href={`/flights/${text(row.participant_flight_id)}`}>Open my FI entry</Link>{revokeControl}</div>:signed?<div className="instructor-decision-actions"><Link className="secondary-button" href="/connections">Done</Link><form action={signAdd}><button className="primary-button">Add FI entry to my logbook</button></form>{revokeControl}</div>:revoked?<div className="instructor-decision-actions">{hasOwnEntry?<Link className="secondary-button" href={`/flights/${text(row.participant_flight_id)}`}>Open my FI entry</Link>:null}<form action={signOnly}><button className="secondary-button">Sign again</button></form>{!hasOwnEntry?<form action={signAdd}><button className="primary-button">Sign again &amp; add FI entry</button></form>:null}</div>:row.status==="pending"?<div className="instructor-decision-actions"><form action={signOnly}><button className="secondary-button">Sign only</button></form><form action={signAdd}><button className="primary-button">Sign &amp; add FI entry</button></form><form action={decline}><button className="secondary-button">Decline</button></form></div>:null}
    </section>:<section className={`panel instructor-decision-panel ${workflowStatus}`}><div><p className="eyebrow">YOUR LOGBOOK · {workflowStatus.toUpperCase()}</p><h2>{workflowStatus==="stale"?"Request is no longer current":workflowStatus==="certified"?"Certified in your logbook":workflowStatus==="added"?"Added to your logbook":workflowStatus==="declined"?"Invitation declined":workflowStatus==="accepted"?"Accepted · copy missing":"Review & add this flight"}</h2><p className="muted">{workflowStatus==="stale"?"The source pilot corrected this flight after this request was created. A new invitation is required for the current revision.":workflowStatus==="certified"?"Your separate logbook record is certified. The source pilot's record remains independent.":workflowStatus==="added"?"Your separate draft is ready. Open it, check your own logbook data and certify it when complete.":workflowStatus==="declined"?"No entry was added to your logbook.":workflowStatus==="accepted"?"The invitation was accepted earlier, but your separate copy is no longer present. You can restore it without changing the source record.":`Check the certified source data above. FlyTally will then create your own editable ${logbookRole} draft; the source flight remains owned by ${text(row.pilot_name)}.`}</p></div>
      {workflowStatus==="stale"?<Link className="secondary-button" href="/connections">Back to Connections</Link>:hasOwnEntry?<Link className="primary-button" href={`/flights/${text(row.participant_flight_id)}`}>{participantCertified?"Open certified flight":"Open my draft"}</Link>:["pending","accepted"].includes(workflowStatus)?<div className="instructor-decision-actions"><form action={accept}><button className="primary-button">{workflowStatus==="accepted"?"Restore to my logbook":"Add to my logbook"}</button></form>{workflowStatus==="pending"?<form action={decline}><button className="secondary-button">Decline</button></form>:null}</div>:null}
    </section>}
  </>;
}
