import { PrintButton } from "@/components/print-button";
import { requireUser } from "@/lib/auth/require-user";
import { formatDuration } from "@/lib/data/dashboard";
import { sql } from "@/lib/db";
import { LOGBOOK_PRINT_SCOPES,logbookPrintScopeLabel,matchesLogbookPrintScope,normalizeLogbookPrintScope,parsePilotPreferences,pilotInCommandName,withAccumulatedFlightTime } from "@/lib/logbook-print";
import styles from "./print.module.css";

export const metadata={title:"Print logbook | FlyTally"};
export const dynamic="force-dynamic";

type Params={scope?:string};
type FlightPrintRow=Record<string,unknown>&{
  id:number|string;date:string;evidence:string;registration:string;aircraft_type:string;aircraft_make:string;aircraft_model:string;aircraft_variant:string;
  aircraft_class:string;operation_type:string;engine_type:string;departure:string;arrival:string;off_block:string;on_block:string;landings_day:number|string;landings_night:number|string;
  night_minutes:number|string;ifr_minutes:number|string;pic_minutes:number|string;copilot_minutes:number|string;dual_minutes:number|string;instructor_minutes:number|string;
  commander:string;instructor:string;role:string;verification_name:string;verification_reference:string;task:string;note:string;certified_at:string|null;certification_hash:string;block_minutes:number|string;
  accumulated_minutes?:number;
};
type FstdPrintRow=Record<string,unknown>&{id:number|string;session_date:string;device_type:string;qualification_number:string;instruction:string;total_minutes:number|string;remarks:string;certified_at:string|null;certification_hash:string;accumulated_fstd_minutes?:number};
type PrintEvent={kind:"flight";date:string;sort:string;flight:FlightPrintRow}|{kind:"fstd";date:string;sort:string;fstd:FstdPrintRow};
type Totals={spSe:number;spMe:number;mp:number;total:number;ldgDay:number;ldgNight:number;night:number;ifr:number;pic:number;copilot:number;dual:number;instructor:number;fstd:number};

const PAGE_ROWS=16;
const text=(value:unknown)=>String(value??"").trim();
const duration=(value:unknown)=>formatDuration(Math.max(0,Number(value)||0));
const dmy=(value:unknown)=>{const raw=text(value);if(!/^\d{4}-\d{2}-\d{2}$/.test(raw))return raw||"—";const [year,month,day]=raw.split("-");return `${day}/${month}/${year.slice(-2)}`};
const aircraftIdentity=(row:FlightPrintRow)=>[row.aircraft_make,row.aircraft_model||row.aircraft_type,row.aircraft_variant].map(text).filter(Boolean).join(" ")||"—";
const verification=(row:FlightPrintRow)=>[text(row.verification_name),text(row.verification_reference)].filter(Boolean).join(" · ");
const remarks=(row:FlightPrintRow)=>{const items:string[]=[],role=text(row.role).toUpperCase(),verify=verification(row);if(role&&role!=="PIC")items.push(role);if(text(row.task))items.push(text(row.task));if(text(row.note))items.push(text(row.note));if(verify)items.push(verify);items.push(row.certified_at?`CERT ${text(row.certification_hash).slice(0,10)}`:"DRAFT");return items.join(" · ")};
const emptyTotals=():Totals=>({spSe:0,spMe:0,mp:0,total:0,ldgDay:0,ldgNight:0,night:0,ifr:0,pic:0,copilot:0,dual:0,instructor:0,fstd:0});
function eventTotals(events:PrintEvent[]):Totals{
  const result=emptyTotals();
  for(const event of events){
    if(event.kind==="fstd"){result.fstd+=Math.max(0,Number(event.fstd.total_minutes)||0);continue}
    const row=event.flight,minutes=Math.max(0,Number(row.block_minutes)||0),operation=text(row.operation_type).toUpperCase()==="MP"?"MP":"SP",engine=text(row.engine_type).toUpperCase()==="ME"?"ME":"SE";
    result.total+=minutes;if(operation==="MP")result.mp+=minutes;else if(engine==="ME")result.spMe+=minutes;else result.spSe+=minutes;
    result.ldgDay+=Math.max(0,Number(row.landings_day)||0);result.ldgNight+=Math.max(0,Number(row.landings_night)||0);result.night+=Math.max(0,Number(row.night_minutes)||0);result.ifr+=Math.max(0,Number(row.ifr_minutes)||0);result.pic+=Math.max(0,Number(row.pic_minutes)||0);result.copilot+=Math.max(0,Number(row.copilot_minutes)||0);result.dual+=Math.max(0,Number(row.dual_minutes)||0);result.instructor+=Math.max(0,Number(row.instructor_minutes)||0);
  }
  return result;
}
function TotalsRow({label,value,className}:{label:string;value:Totals;className:string}){return <tr className={className}><td colSpan={7}>{label}</td><td>{duration(value.spSe)}</td><td>{duration(value.spMe)}</td><td>{duration(value.mp)}</td><td>{duration(value.total)}</td><td></td><td>{value.ldgDay||""}</td><td>{value.ldgNight||""}</td><td>{duration(value.night)}</td><td>{duration(value.ifr)}</td><td>{duration(value.pic)}</td><td>{duration(value.copilot)}</td><td>{duration(value.dual)}</td><td>{duration(value.instructor)}</td><td></td><td></td><td>{duration(value.fstd)}</td><td></td></tr>}
function FlightRow({row,pilotName,index}:{row:FlightPrintRow;pilotName:string;index:number}){const operation=text(row.operation_type).toUpperCase()==="MP"?"MP":"SP",engine=text(row.engine_type).toUpperCase()==="ME"?"ME":"SE",block=Math.max(0,Number(row.block_minutes)||0),picName=pilotInCommandName(row,pilotName);return <tr key={`flight-${row.id}-${index}`}><td>{dmy(row.date)}</td><td>{text(row.departure)||"—"}</td><td>{text(row.off_block)||"—"}</td><td>{text(row.arrival)||"—"}</td><td>{text(row.on_block)||"—"}</td><td>{aircraftIdentity(row)}</td><td>{text(row.registration)||"—"}</td><td>{operation==="SP"&&engine==="SE"?duration(block):""}</td><td>{operation==="SP"&&engine==="ME"?duration(block):""}</td><td>{operation==="MP"?duration(block):""}</td><td><b>{duration(block)}</b><small>Σ {duration(row.accumulated_minutes)}</small></td><td>{picName||"—"}</td><td>{Number(row.landings_day)||""}</td><td>{Number(row.landings_night)||""}</td><td>{Number(row.night_minutes)?duration(row.night_minutes):""}</td><td>{Number(row.ifr_minutes)?duration(row.ifr_minutes):""}</td><td>{Number(row.pic_minutes)?duration(row.pic_minutes):""}</td><td>{Number(row.copilot_minutes)?duration(row.copilot_minutes):""}</td><td>{Number(row.dual_minutes)?duration(row.dual_minutes):""}</td><td>{Number(row.instructor_minutes)?duration(row.instructor_minutes):""}</td><td></td><td></td><td></td><td>{remarks(row)}</td></tr>}
function FstdRow({row,index}:{row:FstdPrintRow;index:number}){const device=[text(row.device_type),text(row.qualification_number)?`(${text(row.qualification_number)})`:""].filter(Boolean).join(" "),remark=[text(row.instruction),text(row.remarks),row.certified_at?`CERT ${text(row.certification_hash).slice(0,10)}`:"DRAFT"].filter(Boolean).join(" · ");return <tr key={`fstd-${row.id}-${index}`} className={styles.fstdRow}><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>{dmy(row.session_date)}</td><td>{device||"—"}</td><td><b>{duration(row.total_minutes)}</b><small>Σ {duration(row.accumulated_fstd_minutes)}</small></td><td>{remark||"—"}</td></tr>}

export default async function PrintPage({searchParams}:{searchParams:Promise<Params>}){
  const {userId}=await requireUser(),params=await searchParams,scope=normalizeLogbookPrintScope(params.scope);
  const [rawFlights,rawFstd,profiles]=await Promise.all([
    sql`SELECT id,date::text date,evidence,registration,aircraft_type,aircraft_make,aircraft_model,aircraft_variant,aircraft_class,operation_type,engine_type,departure,arrival,off_block,on_block,landings_day,landings_night,night_minutes,ifr_minutes,pic_minutes,copilot_minutes,dual_minutes,instructor_minutes,commander,instructor,role,verification_name,verification_reference,task,note,certified_at,certification_hash,CASE WHEN off_block ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$' AND on_block ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$' THEN MOD((split_part(on_block,':',1)::int*60+split_part(on_block,':',2)::int)-(split_part(off_block,':',1)::int*60+split_part(off_block,':',2)::int)+1440,1440) ELSE 0 END block_minutes FROM flights WHERE user_id=${userId} ORDER BY date,off_block,id` as Promise<FlightPrintRow[]>,
    sql`SELECT id,session_date::text session_date,device_type,qualification_number,instruction,total_minutes,remarks,certified_at,certification_hash FROM fstd_sessions WHERE user_id=${userId} ORDER BY session_date,id` as Promise<FstdPrintRow[]>,
    sql`SELECT u.display_name,u.email,s.preferences_json FROM users u LEFT JOIN user_settings s ON s.user_id=u.id WHERE u.id=${userId}` as Promise<Array<Record<string,unknown>>>,
  ]);
  const profile=profiles[0]??{},preferences=parsePilotPreferences(profile.preferences_json),pilotName=text(profile.display_name),pilotAddress=text(preferences.pilot_address),licenceNumber=text(preferences.licence_number);
  const flights=withAccumulatedFlightTime(rawFlights.filter(row=>matchesLogbookPrintScope(row.evidence,scope))) as FlightPrintRow[];
  let fstdAccumulated=0;const fstd:FstdPrintRow[]=scope==="ull"?[]:rawFstd.map(row=>{fstdAccumulated+=Math.max(0,Number(row.total_minutes)||0);return{...row,accumulated_fstd_minutes:fstdAccumulated}});
  const events:PrintEvent[]=[];for(const flight of flights)events.push({kind:"flight",date:text(flight.date),sort:text(flight.off_block)||"00:00",flight});for(const session of fstd)events.push({kind:"fstd",date:text(session.session_date),sort:"23:59",fstd:session});events.sort((a,b)=>a.date.localeCompare(b.date)||a.sort.localeCompare(b.sort)||a.kind.localeCompare(b.kind));
  const pages:PrintEvent[][]=[];for(let start=0;start<events.length;start+=PAGE_ROWS)pages.push(events.slice(start,start+PAGE_ROWS));
  const uncertified=events.filter(event=>event.kind==="flight"?!event.flight.certified_at:!event.fstd.certified_at).length,allTotals=eventTotals(events);
  return <div className="print-logbook easa-print">
    <section className={`${styles.controls} print-trigger`} aria-label="Print options"><form method="get"><label>Logbook content<select name="scope" defaultValue={scope}>{LOGBOOK_PRINT_SCOPES.map(item=><option key={item.value} value={item.value}>{item.label}</option>)}</select></label><button className="secondary-button">Apply</button></form><PrintButton/></section>
    {!pilotAddress?<p className={`${styles.missing} print-trigger`}>Pilot address is not set. Add it in Profile before producing an official logbook copy.</p>:null}
    {uncertified?<p className={`${styles.missing} print-trigger`}>{uncertified} included {uncertified===1?"record is":"records are"} not electronically pilot-certified. The printout marks those entries as DRAFT.</p>:null}
    {!events.length?<p className="empty-state">No logbook records match this print selection.</p>:null}
    {pages.map((page,pageIndex)=>{const pageTotal=eventTotals(page),running=eventTotals(events.slice(0,(pageIndex+1)*PAGE_ROWS));return <section className={styles.logbookPage} key={pageIndex}><header className={styles.header}><div><p className="eyebrow">PILOT LOGBOOK · FCL.050</p><h1>Pilot logbook</h1><p className={styles.scope}>{logbookPrintScopeLabel(scope)} · Page {pageIndex+1} of {pages.length}</p></div></header><section className={styles.identity}><div><span>Holder’s name(s)</span><strong>{pilotName||"—"}</strong></div><div><span>Holder’s address</span><strong className={styles.address}>{pilotAddress||"—"}</strong></div><div><span>Holder’s licence number</span><strong>{licenceNumber||"—"}</strong></div></section><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th rowSpan={2}>1<br/>Date</th><th colSpan={2}>2 · Departure</th><th colSpan={2}>3 · Arrival</th><th colSpan={2}>4 · Aircraft</th><th colSpan={2}>5 · Single-pilot time</th><th rowSpan={2}>MP</th><th rowSpan={2}>6 · Total time</th><th rowSpan={2}>7 · Name(s) PIC</th><th colSpan={2}>8 · Landings</th><th colSpan={2}>9 · Operational condition</th><th colSpan={4}>10 · Pilot function time</th><th colSpan={3}>11 · FSTD session</th><th rowSpan={2}>12 · Remarks / endorsements</th></tr><tr><th>Place</th><th>UTC</th><th>Place</th><th>UTC</th><th>Make, model, variant</th><th>Registration</th><th>SE</th><th>ME</th><th>Day</th><th>Night</th><th>Night</th><th>IFR</th><th>PIC</th><th>Co-pilot</th><th>Dual</th><th>Instructor</th><th>Date</th><th>Type / qualification</th><th>Total</th></tr></thead><tbody>{page.map((event,index)=>event.kind==="flight"?<FlightRow key={`flight-${event.flight.id}-${index}`} row={event.flight} pilotName={pilotName} index={index}/>:<FstdRow key={`fstd-${event.fstd.id}-${index}`} row={event.fstd} index={index}/>)}</tbody><tfoot><TotalsRow label="Page total" value={pageTotal} className={styles.pageTotal}/><TotalsRow label="Accumulated / carry forward" value={running} className={styles.runningTotal}/></tfoot></table></div><section className={styles.certification}><div><span>Page totals certified by pilot</span><strong>{pilotName||"Pilot"}</strong></div><div><span>Date</span><strong>________________</strong></div><div><span>Signature</span><strong>____________________________</strong></div></section><footer>FlyTally · FCL.050 logbook format · UTC times · Page {pageIndex+1}/{pages.length}</footer></section>})}
    {events.length?<section className={`${styles.overall} print-trigger`}><span>Records <b>{events.length}</b></span><span>Flight time <b>{duration(allTotals.total)}</b></span><span>FSTD <b>{duration(allTotals.fstd)}</b></span><span>PIC <b>{duration(allTotals.pic)}</b></span></section>:null}
  </div>;
}
