import { PrintButton } from "@/components/print-button";
import { requireUser } from "@/lib/auth/require-user";
import { formatDuration } from "@/lib/data/dashboard";
import { sql } from "@/lib/db";
import { LOGBOOK_PRINT_SCOPES,logbookPrintScopeLabel,matchesLogbookPrintScope,normalizeLogbookPrintScope,parsePilotPreferences,pilotInCommandName,withAccumulatedFlightTime } from "@/lib/logbook-print";
import styles from "./print.module.css";
export const metadata={title:"Print logbook | FlyTally"};
export const dynamic="force-dynamic";
type Params={scope?:string};
type PrintEvent={kind:"flight"|"fstd";date:string;sort:string;row:Record<string,unknown>};
const PAGE_ROWS=16;
const text=(value:unknown)=>String(value??"").trim();
const duration=(value:unknown)=>formatDuration(Math.max(0,Number(value)||0));
const dmy=(value:unknown)=>{const raw=text(value);if(!/^\d{4}-\d{2}-\d{2}$/.test(raw))return raw||"—";const [y,m,d]=raw.split("-");return `${d}/${m}/${y.slice(-2)}`};
function verification(row:Record<string,unknown>){const name=text(row.verification_name),reference=text(row.verification_reference);return [name,reference].filter(Boolean).join(" · ")}
function aircraftIdentity(row:Record<string,unknown>){return [text(row.aircraft_make),text(row.aircraft_model)||text(row.aircraft_type),text(row.aircraft_variant)].filter(Boolean).join(" ")||"—"}
function remarks(row:Record<string,unknown>){const parts:string[]=[],role=text(row.role).toUpperCase(),verify=verification(row);if(role&&role!=="PIC")parts.push(role);if(text(row.task))parts.push(text(row.task));if(text(row.note))parts.push(text(row.note));if(verify)parts.push(verify);parts.push(row.certified_at?`CERT ${text(row.certification_hash).slice(0,10)}`:"DRAFT");return parts.join(" · ")}
function totals(events:PrintEvent[]){
  const flights=events.filter(event=>event.kind==="flight").map(event=>event.row),fstd=events.filter(event=>event.kind==="fstd").map(event=>event.row),sum=(rows:Record<string,unknown>[],key:string)=>rows.reduce((total,row)=>total+Math.max(0,Number(row[key])||0),0);
  return{spSe:flights.reduce((t,r)=>t+(text(r.operation_type).toUpperCase()!=="MP"&&text(r.engine_type).toUpperCase()!=="ME"?Math.max(0,Number(r.block_minutes)||0):0),0),spMe:flights.reduce((t,r)=>t+(text(r.operation_type).toUpperCase()!=="MP"&&text(r.engine_type).toUpperCase()==="ME"?Math.max(0,Number(r.block_minutes)||0):0),0),mp:flights.reduce((t,r)=>t+(text(r.operation_type).toUpperCase()==="MP"?Math.max(0,Number(r.block_minutes)||0):0),0),total:sum(flights,"block_minutes"),ldgDay:sum(flights,"landings_day"),ldgNight:sum(flights,"landings_night"),night:sum(flights,"night_minutes"),ifr:sum(flights,"ifr_minutes"),pic:sum(flights,"pic_minutes"),copilot:sum(flights,"copilot_minutes"),dual:sum(flights,"dual_minutes"),instructor:sum(flights,"instructor_minutes"),fstd:sum(fstd,"total_minutes")};
}

export default async function PrintPage({searchParams}:{searchParams:Promise<Params>}){
  const {userId}=await requireUser(),params=await searchParams,scope=normalizeLogbookPrintScope(params.scope);
  const [rawRows,rawFstd,profiles]=await Promise.all([
    sql`SELECT id,date::text date,evidence,registration,aircraft_type,aircraft_make,aircraft_model,aircraft_variant,aircraft_class,operation_type,engine_type,departure,arrival,off_block,takeoff,landing,on_block,landings_day,landings_night,night_minutes,ifr_minutes,pic_minutes,copilot_minutes,dual_minutes,instructor_minutes,commander,instructor,role,verification_name,verification_reference,task,note,certified_at,certification_hash,CASE WHEN off_block ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$' AND on_block ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$' THEN MOD((split_part(on_block,':',1)::int*60+split_part(on_block,':',2)::int)-(split_part(off_block,':',1)::int*60+split_part(off_block,':',2)::int)+1440,1440) ELSE 0 END block_minutes FROM flights WHERE user_id=${userId} ORDER BY date,off_block,id` as Promise<Array<Record<string,unknown>>>,
    sql`SELECT id,session_date::text session_date,device_type,qualification_number,instruction,total_minutes,remarks,certified_at,certification_hash FROM fstd_sessions WHERE user_id=${userId} ORDER BY session_date,id` as Promise<Array<Record<string,unknown>>>,
    sql`SELECT u.display_name,u.email,s.preferences_json FROM users u LEFT JOIN user_settings s ON s.user_id=u.id WHERE u.id=${userId}` as Promise<Array<Record<string,unknown>>>,
  ]);
  const profile=profiles[0]??{},preferences=parsePilotPreferences(profile.preferences_json),pilotName=text(profile.display_name),pilotAddress=text(preferences.pilot_address),licenceNumber=text(preferences.licence_number);
  const rows=withAccumulatedFlightTime(rawRows.filter(row=>matchesLogbookPrintScope(row.evidence,scope)));
  let fstdAccumulated=0;const fstd=scope==="ull"?[]:rawFstd.map(row=>{fstdAccumulated+=Math.max(0,Number(row.total_minutes)||0);return{...row,accumulated_fstd_minutes:fstdAccumulated}});
  const events:PrintEvent[]=[...rows.map(row=>({kind:"flight" as const,date:text(row.date),sort:text(row.off_block)||"00:00",row})),...fstd.map(row=>({kind:"fstd" as const,date:text(row.session_date),sort:"23:59",row}))].sort((a,b)=>a.date.localeCompare(b.date)||a.sort.localeCompare(b.sort)||a.kind.localeCompare(b.kind));
  const pages=Array.from({length:Math.ceil(events.length/PAGE_ROWS)},(_,index)=>events.slice(index*PAGE_ROWS,(index+1)*PAGE_ROWS)),uncertified=events.filter(event=>!event.row.certified_at).length,allTotals=totals(events);
  return <div className="print-logbook easa-print">
    <section className={`${styles.controls} print-trigger`} aria-label="Print options"><form method="get"><label>Logbook content<select name="scope" defaultValue={scope}>{LOGBOOK_PRINT_SCOPES.map(item=><option key={item.value} value={item.value}>{item.label}</option>)}</select></label><button className="secondary-button">Apply</button></form><PrintButton/></section>
    {!pilotAddress?<p className={`${styles.missing} print-trigger`}>Pilot address is not set. Add it in Profile before producing an official logbook copy.</p>:null}
    {uncertified?<p className={`${styles.missing} print-trigger`}>{uncertified} included {uncertified===1?"record is":"records are"} not electronically pilot-certified. The printout marks those entries as DRAFT.</p>:null}
    {!events.length?<p className="empty-state">No logbook records match this print selection.</p>:null}
    {pages.map((page,pageIndex)=>{const pageTotal=totals(page),running=totals(events.slice(0,(pageIndex+1)*PAGE_ROWS));return <section className={styles.logbookPage} key={pageIndex}>
      <header className={styles.header}><div><p className="eyebrow">PILOT LOGBOOK · FCL.050</p><h1>Pilot logbook</h1><p className={styles.scope}>{logbookPrintScopeLabel(scope)} · Page {pageIndex+1} of {pages.length}</p></div></header>
      <section className={styles.identity}><div><span>Holder’s name(s)</span><strong>{pilotName||"—"}</strong></div><div><span>Holder’s address</span><strong className={styles.address}>{pilotAddress||"—"}</strong></div><div><span>Holder’s licence number</span><strong>{licenceNumber||"—"}</strong></div></section>
      <div className={styles.tableWrap}><table className={styles.table}>
        <thead><tr><th rowSpan={2}>1<br/>Date</th><th colSpan={2}>2 · Departure</th><th colSpan={2}>3 · Arrival</th><th colSpan={2}>4 · Aircraft</th><th colSpan={2}>5 · Single-pilot time</th><th rowSpan={2}>MP</th><th rowSpan={2}>6 · Total time</th><th rowSpan={2}>7 · Name(s) PIC</th><th colSpan={2}>8 · Landings</th><th colSpan={2}>9 · Operational condition</th><th colSpan={4}>10 · Pilot function time</th><th colSpan={3}>11 · FSTD session</th><th rowSpan={2}>12 · Remarks / endorsements</th></tr><tr><th>Place</th><th>UTC</th><th>Place</th><th>UTC</th><th>Make, model, variant</th><th>Registration</th><th>SE</th><th>ME</th><th>Day</th><th>Night</th><th>Night</th><th>IFR</th><th>PIC</th><th>Co-pilot</th><th>Dual</th><th>Instructor</th><th>Date</th><th>Type / qualification</th><th>Total</th></tr></thead>
        <tbody>{page.map((event,index)=>{if(event.kind==="fstd"){const row=event.row,device=[text(row.device_type),text(row.qualification_number)?`(${text(row.qualification_number)})`:""].filter(Boolean).join(" "),remark=[text(row.instruction),text(row.remarks),row.certified_at?`CERT ${text(row.certification_hash).slice(0,10)}`:"DRAFT"].filter(Boolean).join(" · ");return <tr key={`fstd-${text(row.id)}-${index}`} className={styles.fstdRow}><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>{dmy(row.session_date)}</td><td>{device||"—"}</td><td><b>{duration(row.total_minutes)}</b><small>Σ {duration(row.accumulated_fstd_minutes)}</small></td><td>{remark||"—"}</td></tr>}
          const row=event.row,operation=text(row.operation_type).toUpperCase()==="MP"?"MP":"SP",engine=text(row.engine_type).toUpperCase()==="ME"?"ME":"SE",block=Math.max(0,Number(row.block_minutes)||0),picName=pilotInCommandName(row,pilotName);return <tr key={`flight-${text(row.id)}-${index}`}><td>{dmy(row.date)}</td><td>{text(row.departure)||"—"}</td><td>{text(row.off_block)||"—"}</td><td>{text(row.arrival)||"—"}</td><td>{text(row.on_block)||"—"}</td><td>{aircraftIdentity(row)}</td><td>{text(row.registration)||"—"}</td><td>{operation==="SP"&&engine==="SE"?duration(block):""}</td><td>{operation==="SP"&&engine==="ME"?duration(block):""}</td><td>{operation==="MP"?duration(block):""}</td><td><b>{duration(block)}</b><small>Σ {duration(row.accumulated_minutes)}</small></td><td>{picName||"—"}</td><td>{Number(row.landings_day)||""}</td><td>{Number(row.landings_night)||""}</td><td>{Number(row.night_minutes)?duration(row.night_minutes):""}</td><td>{Number(row.ifr_minutes)?duration(row.ifr_minutes):""}</td><td>{Number(row.pic_minutes)?duration(row.pic_minutes):""}</td><td>{Number(row.copilot_minutes)?duration(row.copilot_minutes):""}</td><td>{Number(row.dual_minutes)?duration(row.dual_minutes):""}</td><td>{Number(row.instructor_minutes)?duration(row.instructor_minutes):""}</td><td></td><td></td><td></td><td>{remarks(row)}</td></tr>})}</tbody>
        <tfoot><tr className={styles.pageTotal}><td colSpan={7}>Page total</td><td>{duration(pageTotal.spSe)}</td><td>{duration(pageTotal.spMe)}</td><td>{duration(pageTotal.mp)}</td><td>{duration(pageTotal.total)}</td><td></td><td>{pageTotal.ldgDay||""}</td><td>{pageTotal.ldgNight||""}</td><td>{duration(pageTotal.night)}</td><td>{duration(pageTotal.ifr)}</td><td>{duration(pageTotal.pic)}</td><td>{duration(pageTotal.copilot)}</td><td>{duration(pageTotal.dual)}</td><td>{duration(pageTotal.instructor)}</td><td></td><td></td><td>{duration(pageTotal.fstd)}</td><td></td></tr><tr className={styles.runningTotal}><td colSpan={7}>Accumulated / carry forward</td><td>{duration(running.spSe)}</td><td>{duration(running.spMe)}</td><td>{duration(running.mp)}</td><td>{duration(running.total)}</td><td></td><td>{running.ldgDay||""}</td><td>{running.ldgNight||""}</td><td>{duration(running.night)}</td><td>{duration(running.ifr)}</td><td>{duration(running.pic)}</td><td>{duration(running.copilot)}</td><td>{duration(running.dual)}</td><td>{duration(running.instructor)}</td><td></td><td></td><td>{duration(running.fstd)}</td><td></td></tr></tfoot>
      </table></div>
      <section className={styles.certification}><div><span>Page totals certified by pilot</span><strong>{pilotName||"Pilot"}</strong></div><div><span>Date</span><strong>________________</strong></div><div><span>Signature</span><strong>____________________________</strong></div></section>
      <footer>FlyTally · FCL.050 logbook format · UTC times · Page {pageIndex+1}/{pages.length}</footer>
    </section>})}
    {events.length?<section className={`${styles.overall} print-trigger`}><span>Records <b>{events.length}</b></span><span>Flight time <b>{duration(allTotals.total)}</b></span><span>FSTD <b>{duration(allTotals.fstd)}</b></span><span>PIC <b>{duration(allTotals.pic)}</b></span></section>:null}
  </div>;
}
